### ISSUE TITLE
.tsx support

### ISSUE THREAD

**Issue by kyo-ago** [sverweij/dependency-cruiser#10]
Hi!
The test fails with this code.
```
import {A as B} from "target";
```
dependency-cruiser is support `{A as B}` format?

### Expected Behavior
Test successful

### Current Behavior
```
error not-to-unresolvable: src/renderer.ts → ./process/renders/main/ui/render
```

### Steps to Reproduce (for bugs)
1. depcruise --init-rules
2. `import {render as appRender} from './process/renders/main/ui/render';` in `src/renderer.ts`
3. `export async function render(container: Element | null) {}` in `./process/renders/main/ui/render.ts`
4. depcruise --validate .dependency-cruiser.json src

### Your Environment

* Version used: 2.3.2
* Node version: v8.5.0
* Operating System and version: Mac OSX 10.12.6
* Link to your project: https://github.com/kyo-ago/lifter/tree/save-settings

**Comment by sverweij** [comment]
Hi @kyo-ago, thanks for reporting this! 
I'll investigate & come back to you

**Comment by sverweij** [comment]
@kyo-ago I found the root-cause: dependency-cruiser doesn't support `.tsx` (or `.jsx`) yet - and that's what the import in `renderer.ts` resolves to (`./process/renders/main/ui/render.tsx` - thanks for providing the link to your project!).

I've added support for `.tsx` (and will look into `jsx` support later on) in version `2.4.0` - by the time you read this it will probably have been released on npmjs.org. 

Please let me know whether this indeed resolved your issue

**Comment by kyo-ago** [comment]
I confirmed the fix.
Thanks a lot!
