### ISSUE TITLE
API to make changes to the generated dot file (and others)

### ISSUE THREAD

**Issue by Ivanca** [sverweij/dependency-cruiser#103]
Thank you for your work. About the issue: Right now (AFAIK) there is no way to change the color of the background nodes or other visual aspects, for example if I want files with more than one class to show with red background there is no way to do it, I think there should be an _api_ to easily customize the `dot` output based on logic written in a JavaScript file.

### Possible Solution

An API with a good enough abstraction for such changes, something like
```js
cruise.on('file-parsed', e => {
    if (e.file.defined.classes.length > 2) {
        e.file.output.fillcolor = 'red';
        e.file.output.label += ' [WARNING: MORE THAN 1 CLASS DEFINED ON THIS FILE]';
    }
})
```
The properties needed for such `file` object the most in my opinion are `numberOfLines`, `defined.classes`, `defined.functions`, `exported.functions`, `exported.classes`, `exported.values` (as in non-classes-and-non-function variables)

**Comment by sverweij** [comment]
hey @Ivanca - thanks for your interest in dependency-cruiser!

It seems you're asking for two things:
1.  new properties on files (or dependencies) - and the ability to use them in rules
2. conditional, configurable colouring

#### new properties on files & using them in rules
Detecting new properties in files beyond dependencies doesn't currently fall within dependency-cruiser's scope. It's non-trivial to pursue and it's something that's already covered by linters like eslint and tslint (e.g. in eslint: [max-lines](https://eslint.org/docs/rules/max-lines#enforce-a-maximum-file-length-max-lines), [max-classes](https://eslint.org/docs/rules/max-classes-per-file#enforce-a-maximum-number-of-classes-per-file-max-classes-per-file))

That said, both eslint and tslint can emit json, so it is possible to integrate their output into dependency-cruiser's and use dependency-cruiser's (e.g.) `dot` reporter to plot that. It'd mean a scope expansion to a more generic source code visualiser. 

#### conditional, configurable colouring
Internally the colouring is set up to be configurable based on a javascript object (there's a [boring](https://github.com/sverweij/dependency-cruiser/blob/develop/src/report/dot/common/boringModuleColorScheme.json) and a [rich](https://github.com/sverweij/dependency-cruiser/blob/develop/src/report/dot/common/richModuleColorScheme.json) (the default) variant). At the moment it's not exposed externally. The main reason is that there was no demand for it, but I also think the format isn't mature enough to expose yet.

#### Some questions
- How would you use this?
- What is the reason you request this to be part of the the API, and not as part of the cli?

**Comment by Ivanca** [comment]
* How would you use this?
Code review done right; easily see what matters to the project, for example I have a project where the folder classes should have only one class per file; and I want imports not being used to be hidden (or near-transparent) among many other things.

* What is the reason you request this to be part of the the API, and not as part of the cli?
API can be integrated into webpack/build scripts in a readable manner, as well as with any other node package, and this are the kind of logic that requires a lot of lines and putting such lines in the CLI would create way-to-long commands

**Comment by sverweij** [comment]
#### @ usage
I assume you're using a linter already to do this already as well? It ticks all of the boxes as far as I can see. What are linters lacking (apart from plotting them in the graph visualisation?)

#### @ api only
When I'm speaking of the cli, it doesn't mean everything should go into a command line invocation :-) All dependency-cruiser's command line options (+ a few extra)  are available in the dependency-cruiser config format; conditional color coding can go in there as well (either verbatim or by reference), potentially even with attributes from other linters.

The advantage would be that it'd be configuration, as opposed to coding.

That said, in both cases the API would need expanding anyway.

I've put both suggestions on the roadmap's backlog for consideration:
- [incorporating output from other analysis tools in the graph visualisation](https://github.com/sverweij/dependency-cruiser/projects/1#card-18335318)
- [user configurable color coding](https://github.com/sverweij/dependency-cruiser/projects/1#card-18335430)

**Comment by Ivanca** [comment]
About **@ usage**

Dependency graphs are made to understand the current state of an application; but the understanding of an application are heavily based on what it is aiming to help understand, if a linter can help or not toward similar goals should be a decision of the project leaders. 

More specifically, that example is just one of many, if tomorrow I want to add logic to one of the "arrows" where I want relationships that just use primitives from another file to be almost invisible then how would that go in a linter? It couldn't.
