### ISSUE TITLE
Breaking change regarding symlinks in latest release

### ISSUE THREAD

**Issue by ajafff** [sverweij/dependency-cruiser#115]
Updating to the latest release is breaking my build: https://circleci.com/gh/fimbullinter/wotan/11618

It seems that symlinks are resolved before looking up the package in package.json.

`packages/bifrost/src/index.js` imports from `@fimbul/ymir` where `node_modules/@fimbul/ymir` is a symlink to `packages/ymir`.

Before: `packages/bifrost/src/index.js → node_modules/@fimbul/ymir/src/index.js`
Now: `packages/bifrost/src/index.js → packages/ymir/src/index.js`

Therefore I now get tons of `error no-non-package-json`

I guess this is caused by your recent switch to `pnp` to resolve dependencies.

### Steps to Reproduce (for bugs)
1. check out https://github.com/fimbullinter/wotan/commit/176571ee83120a2720f6ac7bc9d6cb9b0d0fc0a3
2. `yarn`
3. `yarn check-dependencies`

### Your Environment

* Version used: 4.15.0 (before 4.14.0)
* Node version: 10 LTS
* Operating System and version: Ubuntu?
* Link to your project: see above

**Comment by sverweij** [comment]
Thanks @ajafff - it's not supposed to do that :-/  I'll check tonight where this broke. 

From the diff (thanks!) I see wotan migrated from dependency-cruiser@4.14.0 to dependency-cruiser@4.15.0. Is my assumption correct symlinks still worked correctly in 4.14.0?

**Comment by ajafff** [comment]
Everything worked fine on 4.14.0

**Comment by sverweij** [comment]
Thanks - that'll help narrowing it down!

(I added some [boolean juggling](https://github.com/sverweij/dependency-cruiser/blame/develop/src/main/resolveOptions/normalize.js#L73) to fit node's `preserveSymlinks` and webpack's `symlink` on each other - that seems to be the culprit. Unit tests seemed to prove I covered all bases, but apparently I missed some spots still).

**Comment by sverweij** [comment]
hi @ajafff I've created a patch and published as beta (4.15.1-beta-1) on npm. I've ran it against fimbullineter/wotan - and it works again as expected. I hope to publish it as a regular version tomorrow 🤞.

**Comment by sverweij** [comment]
I've published v4.15.1 to npm - thanks for raising this issue!
