### ISSUE TITLE
Not working on TypeScript classes

### ISSUE THREAD

**Issue by Ivanca** [sverweij/dependency-cruiser#121]
Tried to use the tool without much success

![image](https://user-images.githubusercontent.com/907138/56087727-3c095400-5e36-11e9-8089-e2a78f0b7de5.png)

It shows that little despite AppManager having dozens of imports

![image](https://user-images.githubusercontent.com/907138/56087735-6eb34c80-5e36-11e9-99f1-31fb13716101.png)

For reference the command I'm using is 
```
depcruise --max-depth 99 --output-type dot .\src\scripts\main.ts | dot -T svg > dependencygraph.svg
```

When I try to use it on the all folder the result is empty, meaning when I run:
```
depcruise --max-depth 99 --output-type dot src/scripts | dot -T svg > dependencygraph.svg
```

### Expected Behavior
It should show dependencies

### Current Behavior
It doesn't show dependencies

**Comment by sverweij** [comment]
From the diagram it seems the AppManager module cannot be found. This can have several causes. Assuming that AppManager exists, and the import reference in `src/scripts/main` is correct it might be dependency-cruiser can't find the typescript compiler (it searches for it in the same spot it's installed). 

What does `depcruise --info` tell in your installation?

**Comment by Ivanca** [comment]
Typescript shows with ✖ but typescript is already installed in node_modules? (I verified using npm list)

I tried installing dependency-cruiser locally to see if that would help but did nothing.

**Comment by sverweij** [comment]
- If you've installed dependency-cruiser globally typescript needs to be installed globally as well in order for dependency-cruiser to find it. Judging from the command line script in your issue, you're using that.
- If you run dependency-cruiser from a local install (so it's in your projects' `node_modules` and the binary is in `./node_nodules/.bin/depcruise`) and typescript is installed locally, dependency-cruiser picks up that one.

Note that if you use `depcruise` on the command line you're using the globally installed one. So even if you install dependency-cruiser locally, it'll use the global one, and pick up any global compiler.

So you can do one of two things:
- install typescript globally as well if you use the global depcruise
- make sure to run the local depcruise script - either by calling call `./node_modules/.bin/depcruise` directly (it's where the _scripts_ section of your package.json will look) or use npm's npx : `npx depcruise ...`

HTH

**Comment by sverweij** [comment]
Hi @Ivanca I assume the answer in the previous comment sufficed to resolve the issue. If that isn't the case, feel free to re-open the issue with more details.

I'll add an entry to the FAQ as this is bound to come up more often.
