### ISSUE TITLE
Include line numbers

### ISSUE THREAD

**Issue by alecf** [sverweij/dependency-cruiser#125]
### Expected Behavior
I'd like to see line numbers for the original source

### Current Behavior
No line numbers

### Possible Solution
a `"line": N,` entry in the JSON output, and a `<filename>:N` in the normal text output

### Context
I've got this one case that I can't figure out where a file has a bunch of imports and the last entry in the JSON output is:
```json
        {
          "resolved": "✖",
          "coreModule": false,
          "followable": false,
          "couldNotResolve": true,
          "dependencyTypes": [
            "unknown"
          ],
          "module": "✖",
          "moduleSystem": "es6",
          "matchesDoNotFollow": false,
          "circular": false,
          "valid": false,
          "rules": [
            {
              "severity": "error",
              "name": "not-to-unresolvable"
            }
          ]
        }
```

I have no idea what this is and looking at the source files, everything looks good.

**Comment by sverweij** [comment]
Hi @alecf That's likely a dynamic import. 

* If your project is a javascript project:  acorn (the parser dependency-cruiser uses) doesn't support em yet (last time I looked - I'll look again later tonight and maybe there are alternative solutions out there). 
* If it's a typescript project there's a two things that might resolve the issue
  * use --ts-pre-compilation-deps on the command line (or "tsPreCompilationDeps": true in the options section of the config). It might return a bunch of dependencies you might not particularly be interested in though (see [the doc](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/cli.md#--ts-pre-compilation-deps-typescript-only) for the lowdown on that).
  * use a tsconfig (as documented in the FAQ)[https://github.com/sverweij/dependency-cruiser/blob/develop/doc/faq.md#typescript-dynamic-imports-show-up-as-x--whats-up-there]

... but including linenumbers might be useful for other purposes as well.

If there is no dynamic import in the module these things are dependencies of, than you've hit a bug and I'll be _very_ interested in the source code (minimalized/ anonymized if necessary) so I can fix it a.s.a.p. 

> Notes to self
> - document the first typescript solution mentioned above in the FAQ
> - document a way to prevent false positives like this
> - again look into js dynamic import support

**Comment by sverweij** [comment]
@alecf I've added support for dynamic imports  in dependency-cruiser@4.17.0-beta-1. Without any of the workarounds mentioned above your dependency should now show up with its regular name (making it far easier to find - even without line numbers) and/ or the false positive should will have disappeared.
