### ISSUE TITLE
false positive on no-orphans when file is only used for TypeScript types

### ISSUE THREAD

**Issue by manuelbieh** [sverweij/dependency-cruiser#127]
### Expected Behavior

A file should not be marked as `no-orphans` if it only exports types when these type exports are imported in other files.

### Current Behavior

`no-orphans` is true if only types are imported from a file. There is **no** warning if the file also exports any other values but as long as types are the only thing that's exported from a file depcruise shows a `no-orphans` warning.

### Possible Solution

depcruise should also check if **types** are imported and/or exported and not consider a file as orphaned if types are referenced

### Steps to Reproduce (for bugs)

I found the bug(?) in a public repo of mine. Here is the file with the type exports:
https://github.com/manuelbieh/react-ssr-setup/blob/master/src/shared/store/app/types.ts

they are imported here: https://github.com/manuelbieh/react-ssr-setup/blob/master/src/shared/store/app/actions.ts#L1
and here: https://github.com/manuelbieh/react-ssr-setup/blob/master/src/shared/store/app/reducer.ts#L3

yet depcruise gives me the following result:

```
$ depcruise -c .dependency-cruiser.js --ts-config tsconfig.json src/
  warn no-orphans: src/shared/store/app/types.ts → src/shared/store/app/types.ts
× 1 dependency violations (0 errors, 1 warnings). 50 modules cruised.
```

1. `git clone git@github.com:manuelbieh/react-ssr-setup.git`
2. `cd react-ssr-setup`
3. `yarn install`
4. `yarn lint:deps`

### Context

It's not really affecting me in a very dramatical way but it would still be nice if it worked without a warning

### Your Environment

* Version used: 4.16.0
* Node version: 10.15.3
* Operating System and version: Windows 10, latest stable build
* Link to your project: https://github.com/manuelbieh/react-ssr-setup

**Comment by sverweij** [comment]
Hi @manuelbieh thanks for raising this.

By default dependency-cruiser only takes dependencies into account that are there only _after_ compilation (for some background see [this paragraph](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/faq.md#some-typescript-dependencies-id-expect-dont-show-up-what-gives) or [this epistle](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/cli.md#--ts-pre-compilation-deps-typescript-only)).

If you want to also take dependencies into account that exist before compilation you can enable them by switching tsPreCompilationDeps in the [config to true](https://github.com/manuelbieh/react-ssr-setup/blob/master/.dependency-cruiser.js#L117) - or by passing --ts-pre-compilation-deps as a  command line parameter.

I've made a PR (see 👇 ) on your repo that should mend it

**Comment by manuelbieh** [comment]
Should have read the docs thoroughly 🤦🏻‍♂️ Sorry for that, great work, love this tool! 🚀

**Comment by sverweij** [comment]
No problem @manuelbieh - it just tells me I should improve the access paths to the documentation and/ or (for this specific issue) detect/ ask this in the initialisation wizard.
