### ISSUE TITLE
API: Subsequent calls to cruise will return same result even when file changed

### ISSUE THREAD

**Issue by wongjasont** [sverweij/dependency-cruiser#128]
I am not exactly sure if this is a BUG;

I'm trying to use dependency cruiser in a server that watches for file changes. On every file change, "cruise" will be called on all the files in the directory; however it doesn't change the final result of the call (even if the dependencies are modified in any way)

### Expected Behavior

"cruise" call should return a correct scan result that reflects the current state of the modified files

### Current Behavior

"cruise" call returns the scan result of the FIRST run. It seems that it keeps a cache of all scanned files.

**Comment by ajafff** [comment]
So you are using the API, right? There are some global caches in there that are never cleared unless you start a new process.
AFAICT it'd be a fairly large refactoring correctly clear those caches.

**Comment by wongjasont** [comment]
You are correct I am using the API. It seems to be that way. Any workaround to force it to not use the cache you mentioned? Perhaps one of the keys in options?

Restarting the process again will be a solution yes but it defeats the purpose of the optimization tool i am building. Any suggestion is appreciated.

Thanks

**Comment by sverweij** [comment]
Hi @wongjasont interesting use case :-) 

It's as @ajafff says - dependency-cruiser caches a lot to be performant. That said, the situation is not as dire as implied above :-) - dependency-cruiser has more situations which need cache busting (unit & integration tests for instance).
- Caching is implemented with memoization over the function that does the actual work. In a most cases the unmemoized function is available already - just not exposed in the API. It'll be some work to expose that in the API, but I expect it to be straightforward. 
- The (webpack enhanced-resolve) has it's own caching mechanism - but I've implemented a `bustTheCache` resolve option to be able to do exactly that.

(OTOH implementing a cache invalidation mechanism that only invalidates that which is strictly necessary will indeed be harder...)

**Comment by sverweij** [comment]
@wongjasont version `dependency-cruiser@4.18.0-beta-1` should solve this issue - could you give it a spin?

(I've made a first implementation of cache invalidation that should work in your use case - it was easier to cook than expected 😍 @ lodash).

**Comment by wongjasont** [comment]
@sverweij Tried it and this works perfectly! Really appreciate the quick turnaround 👍

**Comment by sverweij** [comment]
Hi @wongjasont - I've published 4.18.0 as a regular version on npm. It contains the resolution for this issue you tested earlier. A.c.t. the version you tested I found I missed a a cache clean call to the (webpack enhanced-resolve cached filesystem) resolver. 4.18.0 contains the fix for that as well (details in PR #129).
