### ISSUE TITLE
Feature request: TeamCity inspection format output

### ISSUE THREAD

**Issue by ulrichb** [sverweij/dependency-cruiser#133]
For all TeamCity users, it would be cool to have a "TeamCity inspections" output, like [`eslint-teamcity`](https://github.com/andreogle/eslint-teamcity#readme) produces.

Example output (from es-lint): https://i.imgur.com/JXzBuaV.png

### Context
Better discoverability / readability of the dependency violations. Further, if the file paths are reported, TeamCity renders links to them, so you could open the files in different IDEs (for example WebStorm).

### Expected Behavior
Output dependency violations in the ["TeamCity inspections service message" format](https://www.jetbrains.com/help/teamcity/build-script-interaction-with-teamcity.html#BuildScriptInteractionwithTeamCity-ReportingInspections). (Optionally, using the `--format` CLI parameter.)

### Current Behavior
Only plain text.

### Possible Solution
Either directly implement the TC format (e.g. using [this package](https://www.npmjs.com/package/teamcity-service-messages)), or implement the `eslint` formatter contract, so that we could use [`eslint-teamcity`](https://github.com/andreogle/eslint-teamcity#readme) or other formatter plugin libraries.

**Comment by sverweij** [comment]
hi @ulrichb thanks for the suggestion! I see the benefits of output that is easy to navigate in a CI as well, so I'll look into this (later this week, likely). I have never used team city yet - so I'll need some help with the validation 

The reporter mechanism is made to be easily extensible (though not pluggable (yet) - the html and dot output to wit) so adding a new reporter (or 'formatter' as eslint calls it) should be fairly straightforward.

**Comment by ulrichb** [comment]
Okay, cool!

> so I'll need some help with the validation

Np. Can test it for you and send some screens.

**Comment by sverweij** [comment]
hi @ulrichb - dependency-cruiser@4.21.0-beta-1 now has a teamcity reporter - see #138 for details. It'd be great if you could give it a spin and let me know how it works for you.

As you can see in the PR I have one doubt - the reporter logs _all_ rules as inspectionType, which should be correct assuming the collection of inspectionTypes function as as a reference table (which what I inferred from the documentation). It could be that in practice it just generates noise in the TeamCity feedback. If that's indeed happening, let me know - it's a fairly small adjustment.

> There's a PR for an eslint-json reporter as well, but it's not in the published version.
> I'm going to kick it out a.o. as the goal was to make a reporter for TeamCity anyway,

**Comment by sverweij** [comment]
Thanks again for the validation & suggestions during development - `dependency-cruiser@4.21.0` with this feature should be on npm in a few minutes.
