### ISSUE TITLE
"not-reachable" rule

### ISSUE THREAD

**Issue by ulrichb** [sverweij/dependency-cruiser#140]
### **Question (or feature request if it isn't possible at the moment)**

Is it possible to declare an "not-reachable" rule, which is an extension of the "no-orphans" rule, but also checks for modules with outgoing imports. This rule would require to specify a list of "entry points".

### Example

Given

```plain
src/index.js       -> src/mod_a.js
src/mod_a.js       -> src/mod_b.js
src/mod_orphan.js  -> src/mod_b.js
```

Then this rule should report `src/mod_orphan.js` as "not reachable" (given `["src/index.js"]` as "entry point list").

**Comment by sverweij** [comment]
hello again @ulrichb. At this moment this is indeed not possible, but it'd be a useful extension of the orphan rule as a 'dead wood detector'. 

I'll have to mull over what an intuitive interface and a reasonable implementation would be - but it's likely to be doable. 

Kicking around some ideas for a configured rule like that:
```js
{
  forbidden: [{
    name: "only-reachables-from-index",
    from: {
      path: "src/index.ts" // should we limit this to single files or would wildcards yield sensible results?
    },
    to: {
      pathNot: "\\.spec\\.ts$", // we probably want to exclude test specs
      reachable: false // new 'to restriction' property or call it 'notReachable'? What would give the least mental mapping?
    }
  }]
}
```

and/ or as an `allowed` rule, which might be 
```js
{
  allowed: [{
    from: {
      path: "src/index.ts"
    },
    to: {
      reachable: true 
    }
  }]
}
```

**Comment by ulrichb** [comment]
Hi again too :)

> should we limit this to single files or would wildcards yield sensible results?

In one of my projects I indeed will have a list of entry points, but this should be doable using regexps:

```js
    from: {
      path: "^(/src/BackEnd/index.ts|/src/Cli/index.ts|/src/FrontEnd/index.tsx)$"
    },
```

----

> pathNot: "\\.spec\\.ts$", // we probably want to exclude test specs

Good point! => Your `pathNot`/`reachable: false` combination should be definitely possible.

----

Regarding `allowed` vs. `forbidden`: Although I'm using `allowed` heavily, I think in this case a negative `forbidden`-rule is more clear. Therefore I also tend to `notReachable: true` (or maybe better `unreachable: true`, or maybe `unconnected: true` see https://en.wikipedia.org/wiki/Connectivity_(graph_theory)#Connected_graph).

**Comment by sverweij** [comment]
hi @ulrichb I've put out a beta for the next version of dependency-cruiser (dependency-cruiser@4.22.0-beta-1) that has a `reachable` attribute you can use to detect unreachable - details in [pull request 142](https://github.com/sverweij/dependency-cruiser/pull/142) above and in the [documentation](https://github.com/sverweij/dependency-cruiser/blob/feature/dead-wood-detector/doc/rules-reference.md#reachable---detecting-dead-wood).  It works both in `forbidden` and `allowed` rules and you can pass a plethora of files in the from both with `path` and `pathNot`.

<img width="533" alt="dependencies unreachable from src/index.js - reachable rule on" src="https://user-images.githubusercontent.com/4822597/59158784-114b1d00-8ac0-11e9-9e14-dc03def90c6b.png">

There's some work on the PR still (a little tech debt, likely a performance improvement) which I'll work on in parallel, but it's usable already, so if you want to you can take it for a test drive. I'm especially interested in (1) whether the DX is ok for you and (2) if the performance is acceptable.

> As you can see I went with _reachable_ in the end - a.o. to remain consistent with other boolean
> attributes in rules (`orphan`, `circular`), to avoid having to deal with double negations and 
> to have the attribute usable in both forbidden and allowed contexts.
> I've thought about using terms from graph theory (vertex, edge) in stead of 
> the ones use now (module, dependency) - but decided against it so the user doesn't have
> to map it in their minds. That said - I like _connected_  just as well as _reachable_...

**Comment by ulrichb** [comment]
=> I've added a comment to the PR.

**Comment by sverweij** [comment]
hi @ulrichb  - dependency-cruiser@4.22.0 that includes this feature is on npm since ~30min.

**Comment by ulrichb** [comment]
@sverweij Great! 🎉 

Any many thanks!
