### ISSUE TITLE
Feature request: "depth" option

### ISSUE THREAD

**Issue by brian428** [sverweij/dependency-cruiser#16]
I think it would be useful to have a "depth" option, to limit how deep dependency-cruiser goes to crawl the dependency tree?

e.g.: If "depth" is 3, it will only traverse from the root node down to 3 levels of dependencies.

The reason for this is that sometimes I'd like to see a higher-level view of the dependencies without needing to know every single "deep" dependency. Perhaps to get a feel for whether some set of files need to be broken out into a separate module. For large projects, seeing every dependency can create quite an overwhelming graph.

Thoughts?

**Comment by sverweij** [comment]
@brian428 that is a very good suggestion! 

I'm looking into alternative ways to represent larger code bases graphically - adding a max depth seems(!) to be one simple (to implement) and effective way to do so.

**Comment by sverweij** [comment]
@brian428 Preliminary results with the new `--max-depth` command line option (with dependency cruiser cruising itself below. Is this what you had in mind?

`--max-depth 1`
![1](https://user-images.githubusercontent.com/4822597/32019943-f8c89c1c-b9ce-11e7-9543-94c46cedf64f.png)

`--max-depth 2`
![2](https://user-images.githubusercontent.com/4822597/32019954-fff3aeb4-b9ce-11e7-9000-751b8fe39768.png)

`--max-depth 3`
![3](https://user-images.githubusercontent.com/4822597/32020013-1f3ba2e0-b9cf-11e7-893a-b92c64fd5cfa.png)

`--max-depth 4`
![4](https://user-images.githubusercontent.com/4822597/32020025-28f73c22-b9cf-11e7-8a21-1df86376561d.png)

no max-depth specified:
![0](https://user-images.githubusercontent.com/4822597/32020077-4c879420-b9cf-11e7-93aa-55dc03961f5c.png)

**Comment by sverweij** [comment]
@brian428 I've released version 2.6.0 of dependency-cruiser to npm, which includes a --max-depth option. Could you give it a spin and let me know what you think?

**Comment by brian428** [comment]
Will do!

**Comment by sverweij** [comment]
(FYI: I've been working on a --do-not-follow option that might also help you in exploring (/ validating) bigger code bases. It needs to marinate a night or so, though before I publish it - see #18 ).
