### ISSUE TITLE
Typescript triple slash reference directives not supported?

### ISSUE THREAD

**Issue by cdalexndr** [sverweij/dependency-cruiser#160]
Resulting file output has no dependencies in a project where all Typescript files have dependencies declared using `///<reference path=""/>` style.

**Comment by sverweij** [comment]
hi @cdalexndr thanks for taking the time to raise this. 

It's some time ago I built triple slash directive support into dependency-cruiser, so it took some time to dig up how to tickle it to cough them up. Which likely means I need to document this better.

- d.c. considers triple slash directives as used in typescript a separate module system, which it abbreviate to `tsd` ('typescript dependency') (next to e.g. commonjs, es and amd). For backwards compatibility reasons it isn't cruised by default, but they can be included with the `moduleSystems` option (/`--module-systems` cli parameter)
- the triple slash directives often (if not always) only exist _before_ compilation into javascript. By default d.c. disregards these (backwards compatibility reasons as well ...). You can influence that behaviour by setting the `tsPreCompilationDeps` option to `true` (or by passing `--ts-pre-compilation-deps` on the command line.

For the options I've included a [zip file with a simple sample project](https://github.com/sverweij/dependency-cruiser/files/3347298/dependency-cruiser-issue-160-sample.zip). If you want to try it with a simple command line invocation - here's one that should generate the dependency graph in the src folder:

```sh
depcruise --ts-pre-compilation-deps --module-systems amd,cjs,es6,tsd --output-type dot src | dot -T svg > deps.svg
```

HTH

B.t.w. what's the reason your project is using triple slash directives? Is it just historical, or is there another reason?

**Comment by cdalexndr** [comment]
Thanks for the answer.
Indeed, the provided command works as expected.

My project uses _triple slash directives_ for historical reasons and will be migrated to the _import_ statements.
