### ISSUE TITLE
Only display file names, not TypeScript classes

### ISSUE THREAD

**Issue by sroze** [sverweij/dependency-cruiser#182]
### Expected Behavior

When running the following command:
```
npx depcruise -T dot -x node_modules -v -- src/index.ts | dot -T svg > dependencygraph.svg
```

I expect the Graph to display the TypeScript classes 

### Current Behavior

But it isn't, it just displays the file names:
<img width="1084" alt="Screenshot 2019-08-13 at 08 20 03" src="https://user-images.githubusercontent.com/804625/62922396-30597a00-bda3-11e9-8a06-941eb706f378.png">

### Possible Solution

No idea, am I missing something? 🤷‍♂ 

### Steps to Reproduce (for bugs)
1. `npx depcruise -T dot -x node_modules -v -- src/index.ts | dot -T svg > dependencygraph.svg` on a TypeScript project
2. See "current behaviour"

### Context

Just after initialization like this:
```
npx depcruise --init
? What format do you want your config file to be in? JSON
? Do you want to use a preset or a self-contained configuration? preset
? Pick a preset recommended, warn only (good starter choice)
? Looks like you're using TypeScript. Use a 'tsconfig.json'? Yes
? Full path to 'tsconfig.json': ./tsconfig.json
? Also regard TypeScript dependencies that exist only before compilation? Yes

  Successfully created '.dependency-cruiser.json'
```

### Your Environment

* Version used: `dependency-cruiser@5.0.1`
* Node version: `v8.16.0`
* Operating System and version: OSX latest.
* Link to your project: ø

**Comment by sverweij** [comment]
hi @sroze dependency-cruiser checks and reports on dependencies between modules, which, in typescript (and the other supported languages) indeed happen to correspond to files. More fine grained dependencies, like those between classes, interfaces, functions etc. are currently not in scope. 

For what would you use class (/ interface) level checks and visualisations?

**Comment by sroze** [comment]
If it's expected, fair enough 🙃. To be honest, my experience with other programming languages (Java, PHP) was that every tool like this would be based on classes, not files, simply because for whatever reason, a file could expose multiple of them.

**Comment by shouse** [comment]
I would incredibly love the capability to viz interfaces, and this is by far the best I've seen in the JS land.  I admit that my main usage of this library is to get visualizations of how code interacts, and showing classes would allow this to be in a build script and generate some amazing visual documentation.  Sometimes it's important to note where / why the dependencies are used and if we could have a flag to enable classes showing then that is a huge level added to the introspection capabilities.
