### ISSUE TITLE
Ignore Files

### ISSUE THREAD

**Issue by squeedee** [sverweij/dependency-cruiser#183]
I would like to ignore `*.test.js` files

From what I can tell `-x` doesn't match on filenames, only module names. It'd be nice not to see my test files without having to place them in a separate package.

**Comment by squeedee** [comment]
I did work out that for now, I can grep them out of the dot file:

```
depcruise -x "node_modules" -T dot src/iconnect/**/*.js src/midi/**/*.js | grep -v ".test.js" | dot -T svg | browser
```

**Comment by sverweij** [comment]
Hi @squeedee the --exclude (-x) , --do-not-follow (-X)  and --include-only parameters do match file names, but - different from the arguments - take regular expressions instead of globs. 

To exclude node_modules and all files with names ending on test.js from being scanned you can use:

```sh
depcruise -x "node_modules|test\\.js$" -T dot src/iconnect/**/*.js src/midi/**/*.js | dot -T svg | browser
```
