### ISSUE TITLE
handlebars dependency has npm audit vulnerability

### ISSUE THREAD

**Issue by fabb** [sverweij/dependency-cruiser#189]
https://www.npmjs.com/advisories/1164

Please update the `handlebars` dependency to >= `4.3.0`, or even better use `ˆ` for more flexible dependency resolution at clients.

**Comment by sverweij** [comment]
Update is done and was ready to push - had hardware trouble last night though (macs ...). Will push & publish update tonight with from an alternate machine.

(I don't use ^/ ~/ * as there's too much else that can go wrong with that)

**Comment by sverweij** [comment]
I've published dependency-cruiser@5.1.2 which updates a.o. all dependencies to latest (and includes re-pre-compiled templates) see the [5.1.2 release notes](https://github.com/sverweij/dependency-cruiser/releases/tag/v5.1.2) for details.
