### ISSUE TITLE
Feature request: Option to show full path to reachable and circular dependencies

### ISSUE THREAD

**Issue by abierbaum** [sverweij/dependency-cruiser#191]
I have a large codebase (angular application and shared libraries) that is somehow including a large external dependency into the core application.  In this case the dependency is `leaflet`, but it could generally be any library I don't want to end up in the core bundle.  (I am using angular lazy loading to bring in sub-areas of the application)

What I would like to do is provide dependency-cruiser the application entry point file and then have it tell me both if and `import {} from 'leaflet'` is reachable from the base application but also if it is then tell me that dependency chain from the entry point onward that got to leaflet (ie. the list of all imports in order starting from the initial file).

I think I have a rule that will detect the reachability:

```
    {
            name: 'not-to-leaflet',
            comment: 'got leaflet',
            severity: 'error',
            from: {},
            to: {
               "path": "^leaflet$",
               "reachable": true
            }
        },
```

But it ends up being triggered on many modules and I can't find a way to have it simply tell me the path that got there from the initial entrypoint file I gave dependency-cruiser.

Note: in my specific case I don't needs _all_ the paths that get there, just one is enough.  Because after I remove that one, then if there is another I would use the script to tell me that one as well.

Is there a way to do this type of thing and see the full dependency chain?

Note: This would also be *very* useful when used to track down circular dependencies.  On a large code base, the current system is nearly impossible for me to trace through and try to find the actual path that I need to break to fix the circular imports.

**Comment by sverweij** [comment]
If you want to detect which module(s) are directly using `leaflet` - a rule like this in the `forbidden` section should do the trick already:

```javascript
{
  name: 'not-to-leaflet',
  severity: 'error',
  from: {}.
  to: {
   /* 
      path is the _resolved_ path so typically something like 
      node_modules/leaflet/dist/index.js or something; putting just 
      leaflet in here for sake of example - you could consider 
      making it more unique, though
    */
    path: 'leaflet' 
  }
}
```

This rule would flag all modules that directly import/ require leaflet. Does this solve your use case?

(Regardless whether it does - emitting paths for _circular_ and potentially _reachable_ is still a good idea, though. For both there's some brushing up of graph theory to do...).

**Comment by abierbaum** [comment]
@sverwij That doesn't really solve my case.  I know the file that is importing leaflet, what I don't know is the chain of files from the main entrypoint onward that is leading to that file being imported.  So that is where it is like a circular import chain.  I need something like what the 
 https://github.com/aackerman/circular-dependency-plugin does for webpack.  When there is a cyclic dependency it shows all the detected path loops to help the user track down how to break the chain.

so in my case having something like:

```
leaflet-reachable: path to leaflet found

main-entry.ts --> app.module.ts --> helper.srv.ts --> second.srv.ts --> leaflet_helpers.ts --> leaflet
```
I think this would help tremendously in figuring out why a failure has been found and how to resolve it.

**Comment by sverweij** [comment]
The current 'reachable' rule is from the point of view of the `to` part of dependencies (main goal: detect if the `to` part is dead wood - unused by modules matching `from` (typically an application entry point). 

If I understand you correctly your need is the other way 'round; you want to detect if a module is able to reach the leaflet module (it's something not in dependency-cruiser - yet):

```javascript
{
  name: 'not-to-leaflet',
  severity: 'error',
  from: {
    reaches: true
  },
  to: {
    path: '^node_modules/leaflet'
  }
```

If that's indeed what you need (check?) I can indeed put it on the backlog.

B.t.w. I'm working on emitting the full paths for the `circular` option. I've had several requests for that over time already. Once that's in place I expect doing the same for a `reaches` rule could follow quickly.

**Comment by sverweij** [comment]
hi @abierbaum - I've added circular paths to the output of some of the reporters (a.o. the default one - see #194 for details) and published it to npm as `dependency-cruiser@5.2.0-beta-0`. If you want to give it a spin: I'd love to hear any feedback on it. 

Going to work on a _reaches_ rule now (if that's indeed what you need) :-)

**Comment by abierbaum** [comment]
@sverweij That output looks great.  Exactly what I was thinking of.   The only improvement I could think is if there was logic to only report each cycle once if they are duplicates.  But that is really just a nicety on top of what you already have.  Awesome work!!

**Comment by jomi-se** [comment]
Hello there @sverweij 👋

I'm currently facing a similar use case than the originally described (having a "reaches") option.

Did you ever get around to investigating if that is doable?

In my current use-case, I'd like to forbid some files (that define static schemas) of indirectly importing some other files that contain implementation code.

I tried something like:
```javascript
        {
            name: 'implementation-not-reachable-from-info-ts',
            comment: "Don't allow importing database implementation files for schema declaration files",
            severity: 'error',
            from: { path: '\\.info\\.ts$' },
            to: {
                path: '^src/libs/database/',
                reachable: true
            }
        },
```

But it doesn't do what I was expecting it to, and from reading this issue it seems that this is not currently doable with dependency-cruiser

Btw, thanks a **ton** for this library. I really appreciate your work on it and it being very helpful at work.

**Comment by sverweij** [comment]
Hi @jomi-se thanks for bumping this issue. The initial reason to have the reachable rule was to do advanced orphan-checks (e.g. you have one or two entry points in your package and everything that's not reachable from these entry points can be trash canned even though these little islands might still have external dependencies or dependencies among themselves).

The reverse case doesn't work correctly (you do have the syntax right b.t.w.), and I indeed haven't come around to fix it. 

Because of your question I have tonight been digging into what needs to be done to get it to work and I have isolated where it's going wrong - it looks like it's less hard to fix than I initially thought (no ETA, but I'll move the story to the top of the backlog)

> Btw, thanks a **ton** for this library. I really appreciate your work on it and it is being very helpful at work.

Thanks for the compliment 😊 , I'm glad its helpful

**Comment by jomi-se** [comment]
Great! Thanks for the update!

**Comment by sverweij** [comment]
hi @jomi-se I've published a beta version that handles transitive dependencies in rules (like the one in your example). As far as I have been able to test (unit & integration tests...) it works correctly: `dependency-cruiser@8.3.0-beta-2`

=> Could you give it a spin?

**Comment by jomi-se** [comment]
Hello @sverweij that was quick! Thank you for looking into it. 

I tried it out in a private repo ad it didn't seem to return the errors I was expecting. I made up a reproduction setup in the following repo+branch https://github.com/jomi-se/ts-scripting-env/tree/depcruiser-test-case

Using a similar rule to the one described above, it does indeed find a dependency violation. However, it only outputs the file that matches in the `to` part of the rule, but what I'm mostly interested is the `from` file (and ideally the whole path to it 😅 ). My reasoning behind this is that I already know that `someDBFile.ts` is problematic because importing it has side-effects, so I'd like to catch in dependency paths from files that should never have side-effects to this one. Des it make sense?

The output I get is this:
```
z$ yarn depcheck                                                                                                                              [20-04-12 10:31]
yarn run v1.17.3
$ depcruise --validate .dependency-cruiser.js src

  error implementation-not-reachable-from-info-ts: src/database/someDBFile.ts

✖ 1 dependency violations (1 errors, 0 warnings). 3 modules, 2 dependencies cruised.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by sverweij** [comment]
Hi @jomi-se thanks - that's useful feedback.

> but what I'm mostly interested is the from file (and ideally the whole path to it 😅)

Yeah - that makes perfect sense. And probably best _all_ from modules reaching it, and not just one. 🤔 - I'll see if I can cobble something together.

(If I see correctly with 8.3.0-beta-2 there's not any false positives anymore, b.t.w. so at least that's a _little_ progress)

**Comment by sverweij** [comment]
@jomi-se a bit of an in-between update: there's a new beta version (`dependency-cruiser@8.3.0-beta-3`) that emits both the _from_ and the _to_ modules. It's bare bones, but it works. 

=> If you have time - could you check if it works for you?

Things I'd like to polish before releasing it to the _latest_ I still want to (1) give each  _from_ module should an annotation with the module it shouldn't reach, (2) I'm not sure it's still necessary to flag the _to_ side as well - (3) despite 100% coverage it still needs a bunch of unit tests. Later on I'd like to add one of the paths from the _from_ to the _to_ as well.

E.g. given this rule set:

```javascript
module.exports = {
  forbidden: [
    {
      name: "utl-not-reachable-from-report",
      severity: "error",
      from: { path: "^src/report/[^.]+\\.js$" },
      to: { path: "^src/utl", reachable: true }
    }
  ]
};
```

and this dependency-graph:

<img width="400" src="https://user-images.githubusercontent.com/4822597/79077138-6cacf380-7cff-11ea-88e9-0676e53e87e5.png">

(:point_up: you already see the two modules in `report` flagged that reach `utl`)

On the command line it'll emit:

<img width="840" alt="image" src="https://user-images.githubusercontent.com/4822597/79077214-1ab89d80-7d00-11ea-904c-1e5be75dfdfe.png">

And in the err-html report:
<img width="596" alt="image" src="https://user-images.githubusercontent.com/4822597/79077284-c366fd00-7d00-11ea-8f2c-9b33de31da88.png">

**Comment by sverweij** [comment]
@jomi-se  `dependency-cruiser@8.3.0-beta-4` is less bare bones now and shows the from and to and makes the difference between 'regular' violations and 'transitive' ones more clear (by showing _(via via)_ on the latter - can later be replaced with the whole path between them).

<img width="793" alt="image" src="https://user-images.githubusercontent.com/4822597/79127801-cca8a600-7da2-11ea-997c-8d602d7be83e.png">

<img width="677" alt="image" src="https://user-images.githubusercontent.com/4822597/79127988-17c2b900-7da3-11ea-80fc-c6eef79dc79c.png">

**Comment by jomi-se** [comment]
@sverweij Thank you so much again!

The results I'm getting seem sane for both a real repository and the reproduction one I tried earlier 🎉 🎉 This will be reaally useful in managing a big and convoluted repository.

I was wondering why you want to include the target files in the final report though:
![image](https://user-images.githubusercontent.com/27727379/79130864-f0221f80-7da7-11ea-97b3-5c00e22fc464.png)
Or maybe it's just the behaviour of dependency-cruiser's codebase in its current shape.

In any case, thanks a lot, I really appreciate it!

**Comment by sverweij** [comment]
@jomi-se thanks for validating & for your feedback!

> I was wondering why you want to include the target files in the final report though:
you mean the first line in the picture of the report you've included (the one that has `src/database/someDBFile.ts` in the from)? In that case I'm indeed toying with the thought to kick them out as it's redundant. It's not hard to do (two lines of code to do that + updating a bunch of unit tests), but I want to make sure I know what breaks in existing uses of dependency-cruiser when I do so (might be nothing, but then I want to be sure as well).

**Comment by sverweij** [comment]
Version `dependency-cruiser@8.3.0-beta-5` now also includes a path (one per violation) in the _err_ and _err-html_ reporters, instead of the hand-wavy "(via via)". I do have performance concerns for bigger repos, though, so I'll have to do some load & performance testing (and adjustments) over the weekend. In the mean time you can check whether the functionality is how you'd expect it.

Sample terminal output now:
<img width="907" alt="image" src="https://user-images.githubusercontent.com/4822597/79601609-5d57ec80-80e9-11ea-8bbd-e169bc66c6c0.png">

**Comment by jomi-se** [comment]
Cool stuff @sverweij 🎉👏

I just tried it out on a big codebase and timed it comparing it against `beta-4`
Ran it using `npm run test:dependencies`

beta-5:
```
✖ 326 dependency violations (126 errors, 200 warnings). 2266 modules, 8156 dependencies cruised.
npm run test:dependencies  68.73s user 3.78s system 125% cpu 58.001 total
```

beta-4:
```
326 dependency violations (126 errors, 200 warnings). 2266 modules, 8156 dependencies cruised.
npm run test:dependencies  76.71s user 4.73s system 128% cpu 1:03.25 total
```

So it doesn't seem particularly slower on a big repo (or at least _this specific_ big repo), it even went faster than beta-4 in a single run (but that could well be random).

The output is top notch 👍 If I was being pedantic, what would be cool is if the path would stop at the first dependency that broke a rule instead of going down to the sub-dependencies. Eg. I have some errors that show something like this:
```
  error database-files-not-reachable-from-info-ts: src/libs/endpoints/account/someDir/<from-matching-file>.info.ts → src/libs/<to-matching-directory>/<another-directory>/<some-internal-file>.ts
      src/libs/endpoints/account/someDir/CreateUser.info.ts →
      src/libs/<anotherDir>/user.ts →
      src/libs/<to-matching-directory>/<entry-file>.ts →
      src/libs/<to-matching-directory>/<another-directory>/file1.ts →
      src/libs/<to-matching-directory>/<another-directory>/file2.ts →
      src/libs/<to-matching-directory>/<another-directory>/file3.ts
```

But honestly, it's already more than good enough for me. Thanks a lot for your time 👏

**Comment by sverweij** [comment]
hi @jomi-se I've done a few load tests on react and I'm getting similar results - it's just as fast as 8.2.0, 8.3.0-beta-1 and 8.3.0-beta-4 (on average 71s over 10 runs (after 2 warmups) - 5774 modules, 12818 dependencies, with 6 rules on reachability). Surprising, but apparently the optimisation in the BFS algorithm that was in there until 8.3.0-beta-4 wasn't that optimal itself...

As to why sub-dependencies also get flagged - in your example I bet there's also four `database-files-not-reachable-from-info-ts` violations for the `<from-matching-file>.info.ts`, each for modules it can transitively reach in the `<to-matching-directory>`

![image](https://user-images.githubusercontent.com/4822597/79684453-cba7c680-8231-11ea-8815-7761d306c29a.png)

```
  warn no-info-to-db: src/naughty.info.js → src/db/two.js
      src/naughty.info.js →
      src/in.js →
      src/between.js →
      src/db/index.js →
      src/db/one.js →
      src/db/two.js
  warn no-info-to-db: src/naughty.info.js → src/db/one.js
      src/naughty.info.js →
      src/in.js →
      src/between.js →
      src/db/index.js →
      src/db/one.js
  warn no-info-to-db: src/naughty.info.js → src/db/index.js
      src/naughty.info.js →
      src/in.js →
      src/between.js →
      src/db/index.js
```

I do understand the need to summarise these a bit (like with the cycles that are repeated for each module in the cycle) or to find the first via culprit, I'll leave that for a future feature.
(Thanks for voicing that concern b.t.w. - it's feedback like this that helps a lot in improving the tool.)

B.t.w. there's a summarising ('collapsing') feature in the _dot_ and _archi_ reporters  (see below) already that might (1) helpful in getting a bit of overview (2) (note to self) be useful to port over/ move to other parts of dependency-cruiser:

![image](https://user-images.githubusercontent.com/4822597/79684615-27268400-8233-11ea-9a3b-5c80fecce5de.png)
