### ISSUE TITLE
Feature request: except a specific path from exclude

### ISSUE THREAD

**Issue by holmberd** [sverweij/dependency-cruiser#192]
I'm looking for a way to exclude all `node_modules` dependencies except for a specific one. 

### Context
This is an issue when trying to map dependencies for applications that depends heavily on message passing over a dependency library, e.g. Electron IPC-messaging, where the Electron library is imported directly. 

### Expected Behavior
I would like to be able to include that specific dependency but exclude all other `node_modules`. Regex negative look-ahead will not run because of performance issues, and including all `node_modules` for a large code-base is not possible.

### Current Behavior
Currently no way to exclude all `node_modules` expect for one/some.

### Possible Solution
Introduce an `except` command that takes precedence over `exclude`

This is a great tool that is very versatile, thank you.

**Comment by sverweij** [comment]
hi @holmberd - would the [`includeOnly`](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/rules-reference.md#includeonly-only-include-modules-satisfying-a-pattern) option work for your use case?

E.g. assuming your source resides in `src` and the external module you want to _not exclude_ (= include) is `ipc-messaging-module`, on the command line you could ...
```
depcruise --validate --include-only "^(src|node_modules/ipc-messaging-module)" src
``` 

... or with  the options section of the dependency-cruiser config ...

```js
...
  options: {
    includeOnly: "^(src|node_modules/ipc-messaging-module)"
  }
...
```

(And thanks for the compliment 😃)

**Comment by holmberd** [comment]
@sverweij looks like I jumped the gun here. Funny enough I tried `includeOnly` earlier today and I couldn't get it to work, and I try it now and of course it works :)

Thank you for the quick reply and for maintaining this project --I've tried various other similar tools, but none holds as close the the Unix philosophy as this one.
