### ISSUE TITLE
Vue Single File Component. Ignore imports in style part.

### ISSUE THREAD

**Issue by AlexanderShushunov** [sverweij/dependency-cruiser#220]
I use [SFC](https://vuejs.org/v2/guide/single-file-components.html) in Vue.

I try to analyze my project with the tool. It works fine!
But if I use @import statement with alias in `style` section I get an error.
E.g.
```
no-non-package-json: src/Component.vue → styleGuide/vars/colors
```
How can I tell  dependency-cruiser do not resolve @import statement?

**Comment by sverweij** [comment]
Hi @AlexanderShushunov thanks for raising this - that sounds like unexpected behaviour. Could you share the contents of `src/Component.vue`?

**Comment by AlexanderShushunov** [comment]
@sverweij, I will make a demo project.

**Comment by AlexanderShushunov** [comment]
@sverweij, it is more difficult than I thought. Small example works perfect. But my project is not ( I can not share my whole project. So I will try extract "broken" part and share it.

**Comment by AlexanderShushunov** [comment]
I have found the problem.

For sass `@import "_vars.scss"; @import "vars.scss"; @import "vars";` are same imports.
But dependency-cruiser can handle only `@import "_vars.scss";` 

[repo](https://github.com/AlexanderShushunov/dependency-cruiser-import-in-sass)

**Comment by sverweij** [comment]
Thanks @AlexanderShushunov - super clear repo! The fact dependency-cruiser is _considering_ `@import`s is unexpected - my guess is the 'loose' javascript parser it uses identifies these as es6 imports.

I'll dive into it.

**Comment by sverweij** [comment]
@AlexanderShushunov - my guess was correct. dependency-cruiser assumed it could parse `.vue` as regular javascript. This fails - and by default it then falls back to the 'loose' version of the javascript parser. The parser does an admirable job, but it shouldn't be used for .vue in the first place - that should be left to the vue template compiler.

So I've added that to dependency-cruiser (see PR #221). It needs polishing, but it works (verified against your repo) - you can try for yourself by using dependency-cruiser@beta (currently at `5.6.0-beta-0` - but it might bump to higher betas later this week). dependency-cruiser now only looks to the `script` part of the SFC

2 questions:
- Can you help me verify whether this beta version works on your original project?
- I'm not actively using vue a.t.m. Is it possible to have a `.vue` file _without_ it being an SFC? (in that case I'l need to add some additional magic)

**Comment by AlexanderShushunov** [comment]
@sverweij, I checked dependency-cruiser on my original project - it works correct! Moreover, your PR fixes one more bug! I wanted to report it later )

Also I updated the [repo](https://github.com/AlexanderShushunov/dependency-cruiser-vue-sfc). Actually I converted it to set of SFC to check  dependency-cruiser work.

@sverweij, tnx for quick fix 👍

**Comment by sverweij** [comment]
Thanks for validating @AlexanderShushunov  - I'll try to merge it and publish it as `@latest` (version 6.0.0, most probably) later this week.

**Comment by sverweij** [comment]
(It's published)
