### ISSUE TITLE
Clarify importing files that can resolve to multiple existing files

### ISSUE THREAD

**Issue by davidparkagoda** [sverweij/dependency-cruiser#244]
In our project we are using css modules

so for a scss file
`component.scss`
it will generate a `.d.ts` file
`component.scss.d.ts`
which contain the class names

The current resolving behavior will import the file `component.scss` even though you meant `component.scss.d.ts`.

### Expected Behavior
resolve `import * as styles from 'component.scss'` to file `component.scss.d.ts`.

### Current Behavior
resolves `import * as styles from 'component.scss'` to file `component.scss`.

### Possible Solution
Right now i am supplying a webpack config which contains this
```
module.exports  = {
    resolve: {
        enforceExtension: true,
        extensions: [".js", ".json", ".node", ".ts", ".tsx", ".d.ts", ""] // empty string is needed for node modules
    },
};
```

Not the prettiest solution but it is a workaround

### Steps to Reproduce (for bugs)

1.
2.
3.
4.

### Your Environment

* Version used:
* Node version:
* Operating System and version:
* Link to your project:

**Comment by sverweij** [comment]
hi @davidparkagoda thanks for raising this issue. 

It seems the current behaviour is in line with how both node and the typescript compiler (and, by extension enhanced-resolve in its default configuration) handle extension resolution. Both first look for a file that matches the pattern entered, and only if they can't find that start applying extensions.

In your case it's what I'd expect to happen as well - your tsx includes a stylesheet (`component.scss`) the resolver finds the file and calls it a day - In the same fashion regular typescript module resolution works. If you'd include `./helper` - the resolver will look for a file called `./helper`, and then for `./helper.js`, `./helper.json` etc until it finds `./helper.ts. Might there be a .d.ts as well, it won't regard it. This is what you'd want from runtime perspective as well. 

In both cases the type checker and your IDE's auto-completion still uses the .d.ts for type information about your scss module, though.

**Comment by davidparkagoda** [comment]
Okay then I will close this as it seems like a non-issue. Hopefully other people can use the workaround if they run into the same issue
