### ISSUE TITLE
Bug with paths in tsconfig

### ISSUE THREAD

**Issue by dmytro-lymarenko** [sverweij/dependency-cruiser#248]
Looks like depcruise doens't go deeper after reaching alias described inside tsconfig.json file

### Expected Behavior
It should go to the file imported with alias and write its dependencies

### Current Behavior
When depcruise finds an import with alias it then outputs in json file only this module with zero dependencies

### Steps to Reproduce (for bugs)
I use this command:
yarn depcruise --exclude "^node_modules" --output-type json -f dependencies.json src
### Your Environment

* Version used: v6.3.0
* Node version: v12.13.0
* Operating System and version: Ubuntu 18.04
* Link to your project: private (sorry), typescript project

**Comment by dmytro-lymarenko** [comment]
Here is the example of what I get now:
![image](https://user-images.githubusercontent.com/14829154/72911090-27050e00-3d42-11ea-978b-320947b24c51.png)

**Comment by dmytro-lymarenko** [comment]
So, I expect:
  - "source": "src/client/index.ts" should have "src/client/models/BookList.ts" as dependency,
  - "source": "src/client/models/BookList.ts" should have "src/client/models/Book.ts" as dependency.

But currently they are empty arrays ;(

**Comment by dmytro-lymarenko** [comment]
and this is my tsconfig.json file:
{
  "compilerOptions": {
    "target": "es2018",
    "module": "esnext",
    "allowJs": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "strictFunctionTypes": false,
    "removeComments": false,
    "preserveConstEnums": true,
    "sourceMap": true,
    "skipLibCheck": true,
    "baseUrl": ".",
    "paths": {
      "@client/*": ["src/client/*"]
    },
    "strict": true,
    "lib": ["dom", "es2015", "es2016", "es2017", "es7", "esnext"],
    "incremental": true,
    "tsBuildInfoFile": "./buildcache/ts"
  },
  "exclude": ["node_modules"],
  "include": ["src/**/*"]
}

**Comment by sverweij** [comment]
Hi @dmytro-lymarenko thanks for taking the time to raise this issue!

From your screenshot it seems that the dependencies of `index.ts` only contain types, which only exist before compilation from typescript to javascript. By default - for backwards compatibility reasons - dependency-cruiser skips those, but they can be enabled by a flag (either on the command line or in a config).

Could you retry with the same command line invocation, but add the `--ts-pre-compilation-deps` flag? E.g.

```sh
yarn depcruise --exclude "^node_modules" --output-type json --ts-pre-compilation-deps -f dependencies.json src
```

> You can also use a .dependency-cruiser.js config - if you `depcruise --init` it'll detect you're
> in a typescript project and ask you if you want to include pre compilation dependencies.

Let me know if you still miss dependencies after retrying with this

**Comment by dmytro-lymarenko** [comment]
@sverweij Thanks for replying.
I tried your suggestion and I noticed that after I add --ts-pre-compilation-deps flag I get some dependencies but when I tried the same with adding `tsPreCompilationDeps: true` to .dependency-cruiser.js I don't get any dependencies. Looks like tsPreCompilationDeps in .dependency-cruiser.js is not taken into consideration.

**Comment by sverweij** [comment]
Did you tell the cli to read the  dependency-cruiser config (with `--config`)?

**Comment by dmytro-lymarenko** [comment]
@sverweij yes

**Comment by sverweij** [comment]
hi @dmytro-lymarenko I've tried to reproduce the issue (see the [dependency-cruiser-issue-248](https://github.com/sverweij/dependency-cruiser-issue-248) issue and the outcome of running the command in the [github action](https://github.com/sverweij/dependency-cruiser-issue-248/runs/407779411?check_suite_focus=true) (under _Install & build_)), but couldn't.

I did notice two things, though:
- the path alias in https://github.com/sverweij/dependency-cruiser/issues/248#issuecomment-577261080 didn't work for mee - when I ran `tsc` it complained with _src/client/models/BookList.ts:1:22 - error TS2307: Cannot find module '@client/models/Book'._    
(I solved that by changing it to `"@client/*": ["src/client/*"]` - [see here](https://github.com/sverweij/dependency-cruiser-issue-248/blob/master/tsconfig.json#L18))
- dependency-cruiser didn't complain when I passed it a non-existing parameter (by making a typo)
