### ISSUE TITLE
Resolve relative dependencies

### ISSUE THREAD

**Issue by dhuReply** [sverweij/dependency-cruiser#268]
In my project I have two modules within different locations but with the same path/name:
```
content/src/model/baby.ts
src/model/baby.ts
```

With a module and an import like this
```
src/bla/index.ts
import * as x from '../xyz/baby'
```

If I run your awesome tool, dependency-cruiser/extract/resolve/index.js resolve the dependency as `content/src/xyz`

Since I define the import inside `src/bla/index.ts` and not in `content/*` I would expect `src/xyz/baby.ts`.

I could fix this 'issue' by using the module path and not the resolved path:
```
      lResolvedModule.resolved = pathToPosix(
        path.relative(
          pBaseDir,
          fs.realpathSync(path.resolve(pBaseDir, lResolvedModule.module))
        )
      );
```

I hope this is a valid scenario for you and the fix is not that stupid ;-)

### Environment
* Version used: 7.2.0
* Node version: v10.19.0
* Operating System and version: Mac Catalina 10.15.3

**Comment by sverweij** [comment]
Hi @dhuReply thanks for raising this issue. 

The behaviour you describe should already be the default. I've tried to reproduce it locally, but couldn't (see overview below). This means that there's some difference between our set ups. 

Could you share your tsconfig and (if you use that) webpack config? These might explain the differences.

(Screenshot of my local setup below):

<img width="1251" alt="image" src="https://user-images.githubusercontent.com/4822597/75385414-00f20100-58e0-11ea-9542-2fc13a7f3ed1.png">
