### ISSUE TITLE
Show dependencies as simple text output

### ISSUE THREAD

**Issue by afonsomatos** [sverweij/dependency-cruiser#275]
Is there a way just to see the dependencies as a text output without any fancy graphics?
I don't want just the violated dependencies, but everything.

**Comment by sverweij** [comment]
@afonsomatos Not yet, unless you count the JSON format (which might be a bit verbose, depending on the purpose you have). Good suggestion, though!

What would you use the dependencies text only output for?

**Comment by afonsomatos** [comment]
Madge already does this and it's very helpful.

To see which files depend from/on a certain file. For example, in a project I'm working, I'm replacing certain parts of the project and I want to be sure there are no dependencies on the old parts.

**Comment by sverweij** [comment]
@afonsomatos I've published dependency-cruiser 8.1.0 - which includes the fix for this issue. Again thhanks for raising it - and for confirming the fix!
