### ISSUE TITLE
npm audit vulnerability because of handlebars > optimist > minimist

### ISSUE THREAD

**Issue by fabb** [sverweij/dependency-cruiser#277]
dependency-cruiser 8.0.2 depends on `handlebars@4.7.3` which depends on `optimist@^0.6.1` which depends on a vulnerable version of `minimist@0.0.*`.

Currently there is no new handlebars version available that does not produce vulnerability errors, but there already is an open ticket for that: https://github.com/wycats/handlebars.js/issues/1658

Once there is a new handlebars version available, please update the dependency on `handlebars` in dependency cruiser. Or, maybe even better, change the dependency right away to a semantic version range like `^4.7.3`.

**Comment by sverweij** [comment]
I'm acutely aware and am following wycats/handlebars.js#1658 with interest. Might be some time it gets merged, though - the maintainer currently has [more pressing things to attend to](https://github.com/wycats/handlebars.js/pull/1662#issuecomment-602259092) - as might I, f.tm. ...

B.t.w. on runtime dependency-cruiser does not use handlebars' cli, so strictly speaking it's a false positive (as it is for most installations using handlebars, I guess).

> I have a strict policy to not trust semantic version ranges of third party packages beyond what 
> I can run on a ci. As in normal circumstances dependency-cruiser gets updated every one 
> or two weeks (which includes updates to external dependencies) and faster in case of 
> security issues this should be good enough to go.

**Comment by sverweij** [comment]
@fabb - I saw you helped out handlebars with a bunch of unit tests so they could move on to yargs -> thanks!!! 🙏 . 

I'll release an updated dependency-cruiser tonight!

**Comment by sverweij** [comment]
published as 8.1.1 
<img width="556" alt="image" src="https://user-images.githubusercontent.com/4822597/78283938-df0f1e00-751e-11ea-8fdd-e422baae08b2.png">
