### ISSUE TITLE
wrong priority of extensions

### ISSUE THREAD

**Issue by neelance** [sverweij/dependency-cruiser#291]
Each of our UI components consist of a `.ts` and a `.vue` file with the same name. An import without an extension prefers the `.ts` file. The `.ts` file then imports the `.vue` file with explicit extension. Dependency cruiser seems to default to the `.vue` files, so the dependency graph has edges to the `.vue` files instead of the `.ts` files.

**Comment by neelance** [comment]
Hi @sverweij. Thanks for the quick response and your work on the project. I'll wait for your fix and I'm looking forward to using dependency cruiser.

**Comment by sverweij** [comment]
hi @neelance I've put up dependency-cruiser@9.0.1-beta-1 which should fix the issue. Could you give it a spin? If it works for you I'll integrate it into the next release.

**Comment by neelance** [comment]
Thanks @sverweij, it works well.

**Comment by sverweij** [comment]
Thanks for letting me know! I'll merge it so it'll be in the next release.

**Comment by sverweij** [comment]
@neelance The fix has just been released as part of the regular dependency-cruiser@9.1.0 release
