### ISSUE TITLE
Feature request: exit code for depcruise-fmt

### ISSUE THREAD

**Issue by neelance** [sverweij/dependency-cruiser#296]
I figured out to first use `depcruise --output-type json` to do the analysis and then invoke `depcruise-fmt` two times to generate a dependency graph and an error log. What I couldn't figure out is how to still get a proper exit code that makes our CI system fail if dependency rules are violated. Is this a missing feature of `depcruise-fmt`?

**Comment by sverweij** [comment]
@neelance hmm - indeed, makes sense. Never thought to use `depcruise-fmt` that way. 

So `depcruise-fmt` will have that feature in the next version :-) . You can try it in `dependency-cruiser@9.1.0-beta-3` by passing `-e` (or `--exit-code`) to `depcruise-fmt` (the new option is necessary to remain backwards compatible). 

```sh
depcruise-fmt -e youroutput.json
```

or

```sh
depcruise-fmt --exit-code --output-type err-long youroutput.json
```

**Comment by sverweij** [comment]
@neelance I trust the addition of the -e option fixes this issue - LMK if you have other or additional expectations!

**Comment by sverweij** [comment]
@neelance The feature is now part of dependency-cruiser@9.1.0, which has just been released - enjoy!

**Comment by neelance** [comment]
We're now using this together with #297. Thanks.
