### ISSUE TITLE
Feature request: hide nodes from dot output without fully excluding them

### ISSUE THREAD

**Issue by neelance** [sverweij/dependency-cruiser#297]
I would like to exclude nodes from the dot graph, but still validate rules on them. Is this already possible? I think the easiest way would be to do so via `reporterOptions`.

I see two alternatives:
- Manually filter the output json before passing it to `depcruise-fmt`. An option would be simpler.
- Run `depcruise` twice with different configs. This is slower because of duplicate work.

**Comment by sverweij** [comment]
Hi again @neelance - you're on a roll today 😄 !

- It depends a bit on what you want to achieve. For `dot`, `archi` and `ddot` the `collapsePattern` attribute makes possible to summarise a bunch of modules into one node - which makes high level dependency graphs like [this one of react](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/real-world-samples.md#react) and [this one of yarn](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/real-world-samples.md#yarn-2-berry) possible. 
- Filtering  (e.g. to weed out all `.spec.ts` and `.mock.ts` files sprinkled throughout the `src` tree), is currently only possible directly from `depcruise` and not yet after. I can see how that'd make sense, though. Either as part of `depcruise-fmt` or pre-baked in the reporterOptions.

Agree b.t.w. that manual filtering and running depcruise twice are sub optimal. That last one especially on humongous monorepos.

=> What is the type of filtering you're looking for? What is it you want to achieve?

**Comment by neelance** [comment]
I want to apply checks (rules) on where certain npm dependencies get used, but omit them from the dependency graph since they get used a lot and just clutter the graph without giving much information. Same goes for some internal utility modules.

The goal of the dependency graph is to help us with giving our application a proper overall structure. External npm packages and internal utility modules usually have a clear semantic boundary (no outgoing dependencies to other parts of our app (which I want to check)), so I don't worry about them that much with regards to the overall structure.

Does this answer help?

**Comment by sverweij** [comment]
@neelance that context definitely helps! If I summarise correctly filtering after a cruise has taken place would go a long way of fulfilling your need. (B.t.w. I've used almost exactly the same pattern in my last gig - be it I ran the cruise twice, thinking my use case was unique, but it turns out it isn't, so it's _feature-time_ :-) )

I'll see what I can whip up in the coming days - I'll keep you posted in this thread.

**Comment by sverweij** [comment]
Hi @neelance - I've published dependency-cruiser@9.3.0-beta-1. It has a feature that enables you to specify filters specific for reporters. See #302 for details.

=> Could you let me know how that fits your use case?

**Comment by neelance** [comment]
This works great. Thanks! 👍

**Comment by sverweij** [comment]
Thanks for confirming @neelance! And good to hear the --exit-code is working for you as well 👍 

I'll release it to the regular ('latest') channel soon - most likely as version 9.3.0.

**Comment by sverweij** [comment]
(9.3.0 with this feature in it is now published to npmjs)
