### ISSUE TITLE
Question: how to use multiple values for path or pathNot in rules?

### ISSUE THREAD

**Issue by bendanye** [sverweij/dependency-cruiser#301]
Is there a way for "pathNot" to have multiple values?

I have a use case here that i not sure how to write the rules:

Folder structure:
```
node_modules
src
--common
----common.js
--db
----User.model.js
----db.js
--businesscomponent
```

Rules:
1) Codes in db folder can only access common and node_modules folder
2) Codes in db folder can access db folder itself

I tried to write the rules as follow but getting false positive result like 
→ node_modules/mongoose/index.js
```json
{
      "name": "not-from-database",
      "comment": "don't allow dependencies from database to anywhere else except common",
      "severity": "error",
      "from": { "path": "^src/db" },
      "to": { 
        "pathNot": "^src/common" 
      }
 }
```

**Comment by sverweij** [comment]
hi @bendanye - you can use the _choice_ [1]  feature  of regular expressions for that;  if you have more than one pattern you want to match, separate them with a `|` symbol. In your case that could be `"^src/common|node_modules"` (or `"^src/common|^node_modules"` if you want to match only node_modules in your root folder):

```json
{
      "name": "not-from-database",
      "comment": "don't allow dependencies from database to anywhere else except common",
      "severity": "error",
      "from": { "path": "^src/db" },
      "to": { 
        "pathNot": "^src/common|node_modules" 
      }
 }
```

HTH


[1]: you might also know the feature as _alternation_ or _set union_

**Comment by bendanye** [comment]
@sverweij it works! thank you so much!

**Comment by sverweij** [comment]
For people landing here after June 2020 from dependency-cruiser 9.7.0 it's possible to specify multiple values for (a.o.) `path` and `pathNot` as an array, like so:

```javascript
{
      "name": "not-from-database",
      "comment": "don't allow dependencies from database to anywhere else except common",
      "severity": "error",
      "from": { "path": "^src/db" },
      "to": { 
        "pathNot": [
          "^src/common",
          "node_modules"
        ]
      }
 }
```
