### ISSUE TITLE
Issue: Resolving incorrect modules when multiple node_modules directories exist

### ISSUE THREAD

**Issue by richardwillars** [sverweij/dependency-cruiser#303]
When there's multiple node_modules directories which contain different versions of a library, it seems to resolve the incorrect one.
   
I'm using Yarn Workspaces, which results in a file structure that looks like this:

```
root
   node_modules
      date-fns@2.X
   packages
      packageA
         index.ts
         node_modules
            date-fns@1.X
      packageB
```

The code in packageA utilises date-fns@1.X. However, when I run dependency cruiser on it it resolves to date-fns@2.X, which is located in the root node_modules directory.

### Current Behaviour

E.g.
```
    {
      resolved: '../../node_modules/date-fns/getISODay/index.js',
      coreModule: false,
      followable: true,
      couldNotResolve: false,
      dependencyTypes: [Array],
      module: '../getISODay/index.js',
      moduleSystem: 'cjs',
      dynamic: false,
      exoticallyRequired: false,
      matchesDoNotFollow: false,
      circular: false,
      valid: true
    }
```

I know this is pointing to the wrong location as date-fns/getISODay/index.js doesn't exist in date-fns@1.X, it is date-fns/get_iso_day/index.js

### Your Environment
NodeJS 12, running dependency-cruiser@9.3.0 on a TypeScript project on Mac OSX 10.14.6

**Comment by sverweij** [comment]
Hi @richardwillars thanks for raising this issue. 

I've tried to reproduce it (see [dependency-cruiser-repro-repo/303](https://github.com/sverweij/dependency-cruiser-repro-repo/tree/master/303)), but could not - The `date-fns` in `packages/packageA/index.ts` resolves to the one in `packages/packageA/node_modules/date-fns` (as I would expect it to).

This just means there's a difference between your and my setup.

=> Could you help with providing a minimal reproduction example (that includes your .dependency-cruiser.js, tsconfig.json, any webpack config)?

**Comment by richardwillars** [comment]
No problem, I'll put one together shortly
