### ISSUE TITLE
Feature request: Circular runtime dependencies

### ISSUE THREAD

**Issue by RunDevelopment** [sverweij/dependency-cruiser#305]
The [`no-circular`](https://github.com/sverweij/dependency-cruiser/blob/develop/configs/rules/no-circular.js) rule errors on any kind of circular dependency. 
[TypeScript's type imports](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-exports) are optimized away by the compiler during transportation to JavaScript, so they essentially don't exist.

### Context

I want to use dependency-cruiser to validate that I didn't mess up any dependencies between files in my TypeScript project.

However, the `no-circular` also errors on type imports that are guaranteed to be removed during compilation.

> `import type` only imports declarations to be used for type annotations and declarations. It _always_ gets fully erased, so there’s no remnant of it at runtime.
[Source](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-exports)

In my case, I have two classes in separate files that both have static constructor methods that convert one into the other ([1](https://github.com/RunDevelopment/refa/blob/1b17bba07e57f0fa1d85469079833348039c81ab/src/nfa.ts#L586), [2](https://github.com/RunDevelopment/refa/blob/1b17bba07e57f0fa1d85469079833348039c81ab/src/dfa.ts#L329)). Both class files use `import type` imports to avoid circular dependencies during runtime ([1](https://github.com/RunDevelopment/refa/blob/1b17bba07e57f0fa1d85469079833348039c81ab/src/nfa.ts#L7), [2](https://github.com/RunDevelopment/refa/blob/1b17bba07e57f0fa1d85469079833348039c81ab/src/dfa.ts#L7)).

### Expected Behavior

`no-circular` doesn't error because circular dependencies are arguably a runtime problem.

### Current Behavior

`no-circular` errors because it checks compile-time dependencies and doesn't account for the possibility that they might be removed during compilation (only applicable to languages with a compile step).

Output:
```
  error no-circular: src/nfa.ts → 
      src/dfa.ts →
      src/nfa.ts
  error no-circular: src/dfa.ts →
      src/nfa.ts →
      src/dfa.ts
```

Alternatively, I could also set `tsPreCompilationDeps: false`, but then all TS files that only contain type definition get reported by `no-orphans`.

### Possible Solution

Set `preCompilationOnly: false` for `no-circular`, so only runtime dependencies are used.

<details>

```js
module.exports = {
  name: "no-circular",
  comment:
    "This dependency is part of a circular relationship. You might want to revise " +
    "your solution (i.e. use dependency inversion, make sure the modules have a " +
    "single responsibility) ",
  severity: "error",
  from: {},
  to: {
    circular: true,
    preCompilationOnly: false
  },
};
```

</details>

(I tested this and it works just as I wanted to.)

### Considered alternatives

Make a new rule `no-circular-runtime` with exactly this behavior.

**Comment by sverweij** [comment]
Hi @RunDevelopment - thanks for raising this issue and your elaborate and clear explanation. 

The `no-circular` rule as shipped by default with dependency-cruiser indeed by default detects circular dependencies that exist before pre-compilation as well as those that exist after the typescript compiler had its way. A circular relationship is an indication of a potential flaw in the design of an application, regardless whether the relationship only exists before compilation or also after. In the few shops I've made the setup for this was also the rationale to have the no-circular rule as it is. This is also the reason I'll keep the default no-circular behaviour as-is.

That said, I made dependency-cruiser configurable by design because it's impossible to foresee everything. And you made excellent use of that by redefining the rule to make it suitable for your context 😃 .

A remark about the configuration:  you probably want to set the `tsPrecompilationDeps` to the value `"specify"` in order for dependency-cruiser to do its job correctly (and keep doing it correctly - see below). Only then it will know whether the dependencies exists only before or before as well as after compilation.

> I was a little puzzled why your setup seems to give you the correct results. Here's why I was puzzled: dependency-cruiser _only_ sets the `preCompilationOnly` attribute when `tsPrecompilationDeps` has the value `"specify"` ([in `get-dependencies`](https://github.com/sverweij/dependency-cruiser/blob/develop/src/extract/get-dependencies.js#L67)). Your dependency-cruiser config has it on `true` though, which means it should not work. The reason it does seem to work is because the validation step has a small bug and always returns _no match_ in case the preCompilationOnly attribute is not defined (regardless whether your rule's preCompilationOnly attribute equals _true_ or _false_ 😬 ) => I'll correct that in the next release.

**Comment by RunDevelopment** [comment]
Thank you for the detailed response. I will close the issue as the behaviour is intentional.

> you probably want to set the tsPrecompilationDeps to the value "specify" in order for dependency-cruiser to do its job correctly 

Could you please specify which values are valid for `preCompilationOnly`? The [doc](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/rules-reference.md#precompilationonly) doesn't say anything about this.

The default configuration generated by the excellent command-line tool had it set to `true` (with a comment explaining that the default is `false`), so I assumed that it's a simple boolean and that the documentation somehow hasn't been updated yet.

**Comment by sverweij** [comment]
> Could you please specify which values are valid for preCompilationOnly? The doc doesn't say anything about this.

Indeed, thanks for noticing!  I'll correct that a.s.a.p. In the mean time: 
- the `preCompilationOnly` attribute is a boolean - it accepts `true` and `false` (so [in refa](https://github.com/RunDevelopment/refa/blob/master/.dependency-cruiser.js#L38) you set that to `false` correctly!).

- It's the [`tsPrecompilationDeps`](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/rules-reference.md#tsprecompilationdeps) option that has a slightly awkward tri-state boolean-or-a-string (`true`/ `false`/ `"specify"`) type.  It's that one ([here in refa](https://github.com/RunDevelopment/refa/blob/master/.dependency-cruiser.js#L191)) you want to  set to `"specify"` for your use case.

And indeed the the `--init` script doesn't include a question to emit the  `"specify"` value for tsPrecompilationDeps yet. It'll need an additional question ("do you want to be able to distinguish pre-compilation only from post-compilation dependencies within your rules (N/y)?"). I'll keep it in mind for a future version.

**Comment by RunDevelopment** [comment]
Thanks for the clarification!

(Forgot to close)
