### ISSUE TITLE
Config init script creates a not excluded orphan

### ISSUE THREAD

**Issue by hoschi** [sverweij/dependency-cruiser#310]
### Expected Behavior

Validation after init on a empty repo should give no errors.

### Current Behavior

Validation after init on a empty repo marks `.dependency-cruiser.js` as orphan.

### Possible Solution

Created configuration should exclude itself from "no-orphans" rule.

### Steps to Reproduce (for bugs)

1. run `depcruise --init`
2. run `depcruise .dependency-cruiser.js src --validate`

Output:
```
boilerplate > depcruise --init
? Where do your source files live? src
? Do your test files live in a separate folder? No
? Looks like you're using Babel. Use a babel config? No

  Successfully created '.dependency-cruiser.js'

boilerplate > 10206
boilerplate > depcruise .dependency-cruiser.js src --validate

  info no-orphans: .dependency-cruiser.js

✖ 1 dependency violations (0 errors, 0 warnings). 14 modules, 18 dependencies cruised.


```

### Your Environment

- Version used: 9.4.0
- Node version: 12.17.0
- Operating System and version: Linux
- Link to your project: -

**Comment by hoschi** [comment]
It actually was a Create React App project with not the root (where the config file lies) but only `src/` was scanned, but good to know you fixed that in a stable way. I tested your snippet and it works fine, thanks :smiley:

**Comment by sverweij** [comment]
@hoschi yesterday's regular release now contains the fix, so no need for the workaround anymore. 

Thanks again for raising this issue!
