### ISSUE TITLE
Feature request: Support arrays of regexes for path and pathNot

### ISSUE THREAD

**Issue by Undistraction** [sverweij/dependency-cruiser#316]
Currently both `path` and `pathNot` only support a single regex as their value. This is fine in many cases, but in instances where you want to exclude / include a a large number of paths, the regexes can get pretty convoluted. 

### Desired Behavior

Would be great if you could specify an array of regexes.

### Current Behavior

Only a single regex is supported.

**Comment by sverweij** [comment]
Hi @Undistraction that's an excellent point! It's currently already sort-of possible to do so (see [no-orphans.js](https://github.com/sverweij/dependency-cruiser/blob/develop/configs/rules/no-orphans.js) for example), but your suggestion gives more readable configs - and it's easier to use to boot.

You can try it as of now with `dependency-cruiser@9.6.0-beta-1` (published a few minutes ago on npm)

=> Let me know what you think; when it works well for you I'll merge the linked PR and release it as a regular 9.6.0 version.

In the mean time I'll bring the documentation up to snuff and see whether I can expand this idea to everything else accepting regular expressions in the config.

**Comment by Undistraction** [comment]
@sverweij That appears to work like a dream. Much more readable. 

Thanks for the quick response and for a great project. Finally got the chance to get it set up today and it's already been very helpful.

**Comment by sverweij** [comment]
@Undistraction thanks for validating! I'll publish it later on.

... and nice to hear dc is helpful. You don't have to answer this, but I can't resist asking: how did it help you?

**Comment by Undistraction** [comment]
So far, it's helped me find a couple of interdependencies that needed to be eliminated. I'm using it with a Gatsby site, which can pretty much be split into a set of build-time and built dependencies, the former being involved in configuration and page generation, the later standard runtime dependencies for pages/components. It's also helped me catch some orphaned files. I was hoping to use it to track down why I have a particular dependency (`lodash`) in one of my chunks, despite it only being a dependency of Dec dependencies, but I've getting an out-of-memory crash when trying to visualise with `node_modules` included. I probably need to do some more reading of the docs and play with the depth.

Hoping to integrate it into our CI and precommit hooks tomorrow.

**Comment by sverweij** [comment]
@Undistraction thanks! Insights like these are helpful.

Were you able to solve the _who uses lodash_ problem? 

If not, here's some things you can try:
- if you suspect the code in your own repo:
  - you could add a new rule that forbids  use of lodash
  - the `not-to-dev-dep` rule in the default config might need a little more tweaking to your repo's setup.
  - more barebones: put the output of your cruise through the `text` reporter and `grep` for _lodash_ (`depcruise bin src -c -T text | grep lodash`)
- if you suspect another node module from using lodash below the surface
  - if you're a yarn user: `yarn why lodash`

HTH ...

In other news: `dependency-cruiser@9.6.0` has just been published - it contains the functionality you tested yesterday + the rest of the functionality described in #317. I'll expand your idea to the options section in the config in a separate PR.
