### ISSUE TITLE
Feature request: option to report circular folder dependency

### ISSUE THREAD

**Issue by kevinrutherford** [sverweij/dependency-cruiser#324]
I love dependency-cruiser -- thanks so much for creating an maintaining it.

I would like the option to be able to flag circular dependencies between folders as an error.

### Context

We have a gnarly typescript project with types defined in all sorts of weird places, and then referenced from everywhere. This has led to circular dependencies between folders. I'm trying to sort out the architecture to be cleaner, and so I would like to trigger an error message for folders that depend on each other.

### Expected Behavior

Allow the creation of a validation rule that would report an error in the following situation:

src/a/a1.ts -> src/b/b1.ts
src/b/b2.ts -> src/a/a2.ts

### Current Behavior

There doesn't appear to be a way to write such a rule

### Possible Solution

No idea, sorry!

### Considered alternatives

Currently I have to manually detect these, and then persuade my colleagues that it is bad...

**Comment by sverweij** [comment]
hi @kevinrutherford - thanks for this insight in how you're using dependency-cruiser! 

Not too long ago I bumped into a similar situation - and made a mental note to cook something for it. However, at the time (and in that code base) we could manage with some rules that were geared towards the architecture. E.g. when looking at the high level ("archi") graph we saw modules in a _search_ component depend on modules in _utils_ (OK), but also code in _utils_ calling modules in _search_ (weird; not OK). That was a cycle between folders alright, but we fixed that by applying a rule that forbade _utils_ depending on functional components. Similarly we already had a rule in place to ban dependencies directly between components, which as a side effect prevents cycles there as well.

Is this an approach that could work in your situation as well? Or is the issue you're trying to solve more 'discovery' oriented?

> In the mean time: I didn't think it'd be hard to implement this. To prove that I've made a crude 
> hack. It consolidates modules to folders just below _packages/_ before running any rules 
> against them. See below for how that looks in the archi and err-html reporters when unleashed 
> against [react](https://github.com/facebook/react). 
>
> If this is going to be a feature the most complex thing will be integrating the configuration 
> in a way that is easy to use & understand...
> 
> <img width="1027" alt="image" src="https://user-images.githubusercontent.com/4822597/85058431-683f0400-b1a2-11ea-99e4-e588948b42a9.png">
>
> The html report looked slightly more actionable ...
> <img width="711" alt="image" src="https://user-images.githubusercontent.com/4822597/85058560-93295800-b1a2-11ea-9e11-b0802a224ebd.png">

**Comment by kevinrutherford** [comment]
Thanks for the detailed response @sverweij. In my case the folders that depend on each other are all within the same architectural sub-domain, so I can't really add exclusion rules for individual folders.

The report you cooked up here looks perfect -- exactly what I need.
