### ISSUE TITLE
Add option to resolve symlinks of dependencies

### ISSUE THREAD

**Issue by ajafff** [sverweij/dependency-cruiser#33]
### Expected Behavior
I use yarn workspaces to link the packages in my monorepo to each other. This bascially does `yarn link` (or `npm link`) behind the scenes.
The setup is as follows:

```
packages
  |-- a
  \-- b
node_modules
  |-- a -> ../packages/a
  \-- b -> ../packages/b
```

`a` requires `b`, so I would expect the path to be `packages/b/index.js` but instead it is `node_modules/b/index.js`.

Node resolves symlinks during require. That's why I expected this tool to do that too.

### Current Behavior
Symlinks are not resolved, see above.

### Possible Solution
Add an option whether `fs.realpath` should be used after resolving imports.
This should not be enabled by default, because it would probably break other users.

### Your Environment

* Version used: 2.13.1
* Node version: 9.5.0
* Operating System and version: macOS High Sierra 10.13.3
* Link to your project: https://github.com/fimbullinter/wotan (.dependecy-cruiser.json is not updated as of writing this)

**Comment by sverweij** [comment]
Ouch! I was expecting that to work as well. Thanks for reporting. You're also right that fixing it right on will be breaking, so I'll put it behind an option (both in the cli and in .dependency-cruiser.json).

(Wotan looks cool b.t.w.! I'll definitely give it a closer look after this).

**Comment by ajafff** [comment]
I thought this would be as easy as adding the `preserveSymlinks: false` option to `resolve.sync`, but it seems that resolving symlinks was never implemented in that module: https://github.com/browserify/resolve/issues/122

I'll probably try to fix this upstream.

**Comment by ajafff** [comment]
I totally missed that. So it seems that's not a bug in `resolve`. They just don't use realpath on the result at all. Instead they resolve the input `basedir` if explicitly requested.

That means this package just needs a call to `fs.realpathSync` after using `resolve.sync`.

**Comment by sverweij** [comment]
We still need the fix in dependency-cruiser, but even when yesterday I concurred with the view it isn't a bug in `resolve`, today I've had a closer look and I'd say it still needs a fix upstream as well - given that `resolve`'s intent is to implement the `require.resolve` algorithm:

Let's say we have a link and an index.js in a folder:
```
only-the-link@ -> the-real-dir
the-real-dir/
the-real-dir/index.js
```

Now I'd expect `resolve.sync` and node's `require.resolve` to have the same result. But they don't:
```javascript
> require.resolve('./only-the-link');
'/dir/the-real-dir/index.js'

> resolve=require('resolve');
(...)

> resolve.sync('./only-the-link', {preserveSymlinks: false})
'/dir/only-the-link/index.js' // expected: '/dir/the-real-dir/index.js'

> resolve.sync('./only-the-link', {preserveSymlinks: true})
'/dir/only-the-link/index.js'
```
