### ISSUE TITLE
Issue: npm audit vulnerability because of lodash

### ISSUE THREAD

**Issue by fabb** [sverweij/dependency-cruiser#333]
Please update lodash to the latest version, the currently used version has a vulnerability: https://www.npmjs.com/advisories/1523

**Comment by sverweij** [comment]
Thanks for the notification! I'll publish a new version tonight.

I saw the update yesterday but didn't know that version was marked as the
fix for the vulnerability (that should already have happened in 4.17.18 (or
actually .16).

The audit vulnerability is b.t.w. a false positive:
- dependency-cruiser uses lodash 4.17.18. That version already contains the
fix the vulnerability (see https://github.com/lodash/lodash/commits/4.17.19
).
- dependency-cruiser *nor any of its *dependencies uses zipObjectDeep. (I'd
love to seek snyk/ npm making their audit vulnerabilities a little more
fine grained ...)

**Comment by sverweij** [comment]
(FTR: published as version 9.9.2)
