### ISSUE TITLE
Option to treat warnings as errors

### ISSUE THREAD

**Issue by ajafff** [sverweij/dependency-cruiser#34]
Because my package dependencies are a bit special (same package in `peerDependencies` and `devDependencies`), I cannot use `forbidden` rules to express what kinds of npm dependencies are allowed. Therefore I use `allowed` rules: https://github.com/fimbullinter/wotan/blob/7866ba356e39b66aa0ea4817bd8ae2afa17d5baf/packages/wotan/.dependency-cruiser.json

Unfortunately violating `allowed` only results in warnings. It would be great if there was an option to treat warnings as errors and exit with a non-zero exit code.

**Comment by sverweij** [comment]
When I wrote the first version of dependency-cruiser I considered making the _severity_ level of the allowed rule configurable, but decided to wait until there was demand for it.

That time has come, it seems :-)

**Comment by sverweij** [comment]
hi @ajafff I've published a version 3.0.0-beta-4 that has this in. Let me know what you think...
