### ISSUE TITLE
Recognizing barrel file (index.ts)

### ISSUE THREAD

**Issue by linuschinsay** [sverweij/dependency-cruiser#340]
### Summary

It seems that import statements pointing to folder (using barrel files: index.ts or index.js) are not recognized by dependency-cruiser? The GraphViz output is not showing the arrows to the other files in the "barrel" folder.

### Context

As our codebase is huge, we make use of barrel files to export functionalities of a particular folder.

### Environment

- Version used: 9.9.4
- Node version: v10.16.3
- Operating System and version: windows 10
- Link to your project: NA

**Comment by sverweij** [comment]
@linuschinsay thanks for raising this. dependency-cruiser doesn't (shouldn't) treat barrel files differently from other files. I've run it against several environments with barrel files and had no issues with them. Which means there might be something specific in your environment and/ or setup.

Could you provide a minimal reproduction example showcasing your problem (including the .dependency-cruiser.js and the command line parameters you've used)?
