### ISSUE TITLE
Feature request: changelog file to make it easy to see what is new from one version to another

### ISSUE THREAD

**Issue by abierbaum** [sverweij/dependency-cruiser#349]
### Context

I am coming back to dependency-cruiser after not having update in a while.  I am trying to learn what has changed, what may have broken, and what new awesome features I want to use.  But I can't find a way to see this easily.

### Expected Behavior

I think it would be great to have a CHANGELOG.md file that described the big changes from one version to another.

**Comment by sverweij** [comment]
Hi again @abierbaum! Good suggestion, thanks for asking, I  your point :-)

At this moment dependency-cruiser's changelog uses github's  [releases section](https://github.com/sverweij/dependency-cruiser/releases). Did you find that already? If not: is that usable for you? If you already did: is there something you'd like to see in a CHANGELOG.md that isn't in the releases section?

- I'll still consider a CHANGELOG.md (maybe to start with a link to the releases section) as that'll likely improve the discoverability of changes
- Dependency-cruiser follows semver, so breaking changes are in major releases and  new features in minors.
