### ISSUE TITLE
depcruiser doesn't parse .js imports when the source file is actually .ts

### ISSUE THREAD

**Issue by jackfranklin** [sverweij/dependency-cruiser#364]
### Expected Behavior

Puppeteer is written in TypeScript but we ship using ES Modules that include a `.js` extension.

e.g., a file `Foo.ts` that imports `Bar.ts` will have the following import:

```
import Bar from './Bar.js';
```

Here, `Bar.js` doesn't exist, but `Bar.ts` does. TypeScript understands this but it seems dependency-cruiser does not and fails to parse the import.

### Current Behavior

(I'm guessing) but I think that dep-cruiser sees the import to `Bar.js` but doesn't find that file, so it gives up.

### Possible Solution

If the source file is TypeScript (e.g., you're parsing `Foo.ts`), and you find an import that's suffixed with `.js`, look for the `.ts` file if the `.js` one cannot be found.

### Steps to Reproduce (for bugs)

1. Checkout [Puppeteer from GitHub](https://github.com/puppeteer/puppeteer)
2. Run `npm install`
3. Run `npm run generate-dependency-graph`

You'll see a dependency-chart.png generated, however it's absolutely tiny and doesn't parse all files. If you update the import in `src/index.ts` to remove the `.js` suffix on the `initializePuppeteer` import, you'll see that it begins to parse that file.

I'm happy to attempt a fix if no one else has time, so please let me know! Thanks.

### Your Environment

- Version used: 9.13.1
- Node version: 12
- Operating System and version: Latest OS X

**Comment by sverweij** [comment]
Hi @jackfranklin thanks for raising this issue. 

Your guess in _current behavior_ is correct. dependency-cruiser (or actually _enhanced_resolve_ who's doing the file resolution heavy lifting) can't find a `Bar.js` on disk - sees it already has an extension, and flags the module as _could not resolve_. 

I was surprised to see the typescript compiler accept this - but 🤷 if tsc accepts it, dependency-cruiser should follow. I've made a fix that works (see graphs below), but it needs a little polishing - I'll try to have a PR (and a beta version) ready by tomorrow night.

> The fix is to retry _without_ extension when we can't find the file on disk and the import has an extension. That way enhanced_resolve can do its thing with know extensions and other parts of the module resolution Gödel set ...

### Sample output
Incantation to get the files below:

```sh
depcruise src/index.ts --config --output-type dot --include-only "^src" |\
   dot -T png > puppeteer-without-pre-compilation-deps.png
```

#### Puppeteer internal dependencies without pre-compilation dependencies

> config with `tsPreCompilationDependencies: false`

![puppeteer-without-pre-compilation-deps](https://user-images.githubusercontent.com/4822597/92641185-b0bc1880-f2de-11ea-9f08-ecdc3bde0a81.png)


#### Puppeteer dependencies with pre-compilation dependencies

> config with `tsPreCompilationDependencies: "specify"` so you also get dependencies on e.g. modules that only have typings in them.

![puppeteer-with-pre-compilation-deps](https://user-images.githubusercontent.com/4822597/92641257-c29dbb80-f2de-11ea-837b-570baf0634bf.png)

**Comment by sverweij** [comment]
@jackfranklin I've published a working and polished version as `dependency-cruiser@9.13.2-beta-1`. 

B.t.w. with a few little tweaks puppeteer's generated dependency-graph can look a bit nicer (i.e. with straight lines, collapsed vendor/ node_modules - or even left out... ) LMK if you want me to help out.

**Comment by jackfranklin** [comment]
@sverweij this is amazing, thank you so much for a quick response! Super speedy :)

I'll give the beta a go and have a look - thank you!

**Comment by sverweij** [comment]
hi @jackfranklin - I've just merged & released the fix for this issue as part of dependency-cruiser@9.14.0
