### ISSUE TITLE
doc: update the react real world example

### ISSUE THREAD

**Issue by sverweij** [sverweij/dependency-cruiser#370]
### Context
One of the [real world samples](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/real-world-samples.md#react) is the high level overview of the [react](https://github.com/facebook/react) mono repo. The graph hasn't
been updated for a while, though.

### Desired situation
The high level graph in the real world samples section is updated to react's latest master branch. Instructions + configuration are in the howto in the [react](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/real-world-samples.md#react) section.

**Comment by Guzzler** [comment]
https://github.com/sverweij/dependency-cruiser/pull/374 have created this PR in relation that should solve this with the latest clone of the facebook/react repository. please let me know if any other changes are to be made.
