### ISSUE TITLE
doc: update the yarn 2 ("berry") real world example

### ISSUE THREAD

**Issue by sverweij** [sverweij/dependency-cruiser#371]
### Context
One of the [real world samples](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/real-world-samples.md#yarn-2-berry) is the high level overview of the [yarn(2)](https://github.com/yarnpkg/berry) mono repo. The graph hasn't been updated for a while, though.

### Desired situation
The high level graph in the real world samples section is updated to yarn berry's latest master branch. Instructions + configuration are in the howto in the [yarn 2 ("berry")](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/real-world-samples.md#yarn-2-berry) section.

**Comment by Guzzler** [comment]
#374 have created this PR in relation that should solve this with the latest clone of the berry repository. please let me know if any other changes are to be made. Could not update the html file as it was not generated and on an attempt of generation failed.
