### ISSUE TITLE
init: expand the list of deprecated core dependencies

### ISSUE THREAD

**Issue by sverweij** [sverweij/dependency-cruiser#373]
### context

`configs/rules/no-deprecated-core.js` lists modules that have een deprecated and/ or have been removed from node. The list is up to date to node version 8. Since, more internal depencencies have been deprecated (v10) and subsequently removed (v12) - [as documented in node api documentation](https://nodejs.org/dist/latest-v12.x/docs/api/deprecations.html#deprecations_dep0084_requiring_bundled_internal_dependencies). Same for [node 14](https://nodejs.org/dist/latest-v14.x/docs/api/deprecations.html)

### desired situation

The code that generates the initial .dependency-cruiser template also lists the node core modules the links above list as either deprecated or removed. Some hints
-  the template for dependency-cruiser configs generated by --init is in `src/cli/init-config/config.js.template.hbs` 
- compile by either running `make` or by running the handlebars command manually (e.g. `npx handlebars --commonjs handlebars/runtime -f src/cli/init-config/config.js.template.js src/cli/init-config/config.js.template.hbs`)

**Comment by Winner95** [comment]
Hello @sverweij ,

I was wondering if I can help with this issue?

If it is fine, I was wondering if it is fine to discuss the possible implementation:

1) Do you think, it is good to check for user's node.js in `package.json` and based on it & used version, show deprecation warning for certain versions?

2) Data from `https://nodejs.org/dist/latest-v8.x/docs/api/deprecations.json` and other versions can be used (probably saved locally with pointing at the origin of list of deprecation) there as well?

**Comment by sverweij** [comment]
Hello @Winner95 automating this would be interesting, but I'm afraid it'll remain a manual task for now.

1. The current implementation goes with a static list. The reasoning at the time: when a core module is deprecated in e.g. node 14, it'll be of interest to projects still on node 10 as well, as eventually those projects will have to upgrade to node 14 as well. 

2. I didn't know that json URL - thanks for that! It'd been super interesting if we could use that to update in batch e.g. each new node release. So I've downloaded it and taken a closer look. It seems deprecations to modules haven't been recorded consistently enough to reliably automate, though (see below) ...

> ```
> > !wget https://nodejs.org/dist/latest-v8.x/docs/api/deprecations.json
> > d = require('./deprecations')
> > d.modules[0].modules[1].modules.map(pMod => pMod.displayName)
> [
>   'DEP0001: http.OutgoingMessage.prototype.flush',
>   "DEP0002: require('\\_linklist')",                        => linklist got deprecated
>   'DEP0004: CryptoStream.prototype.readyState',
>   'DEP0005: Buffer() constructor',
>   "DEP0008: require('constants')",                          => constants got deprecated
>   'DEP0009: crypto.pbkdf2 without digest',
>   'DEP0013: fs asynchronous function without callback',
>   'DEP0014: fs.read legacy String interface',
>   'DEP0015: fs.readSync legacy String interface',
>   'DEP0016: GLOBAL/root',
>   'DEP0018: Unhandled promise rejections',
>   "DEP0019: require('.') resolved outside directory",
>   'DEP0024: REPLServer.prototype.convertToContext()',
>   "DEP0025: require('sys')",                               => sys got deprecated
>   'DEP0030: SlowBuffer',
>   'DEP0032: domain module',                                => domain got deprecated
>   'DEP0040: punycode module',                              => punycode got deprecated
> etc ...
> ]
> 
> ```

> The similar json for v12 mentions _DEP0084: requiring bundled internal dependencies_, but the precise modules are recorded in unstructured html (in the `desc`) field,
... but I don't see the v8/tools/... and node-inspect/lib/... modules mentioned in [https://nodejs.org/dist/latest-v12.x/docs/api/deprecations.html#deprecations_dep0084_requiring_bundled_internal_dependencies

**Comment by Winner95** [comment]
Hello @sverweij , 

thank you for feedback!

So the best strategy will be to compare current version vs 10, 12 and 14 to prepare manual list for it. 

I can do it that then?

**Comment by sverweij** [comment]
yes @Winner95 you're very welcome to!

(sorry for my slow response rate b.t.w. - in the past weeks my spare time has been a bit more busy than I'm used to)

**Comment by Winner95** [comment]
Thank you @sverweij !)
