### ISSUE TITLE
doesn't work on windows

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [sverweij/dependency-cruiser#379]
wanted to try out this package, but sadly I can't get any graph from it

```

depcruise --include-only "^src" --output-type dot src | dot -T svg > dependencygraph.svg
'dot' is not recognized as an internal or external command,
operable program or batch file.

```

```

dependency-cruise -x "^src" src svg > dependencygraph.svg

  ERROR: Can't open 'svg' for reading. Does it exist?

```

**Comment by sverweij** [comment]
hi @hp8wvvvgnj6asjm7 - in the first command you pipe dependency-cruiser's output to GraphViz dot. The error message  indicates GraphViz dot isn't installed on your windows machine. You might want to do that first. 
[GraphViz download page is here](https://graphviz.gitlab.io/download/) - likely the [stable x64 build for windows](https://www2.graphviz.org/Packages/stable/windows/10/cmake/Release/x64/) is the one you want to grab.

Note that dependency-cruiser doesn't produce svg of itself. It can generate graph descriptions in the _dot_ language (`--output-type dot`), but you do need GraphViz dot to turn these into pictures.

In the second command you post you instruct dependency-cruiser to look in the 'src' and 'svg' folders (but with `-x` to hard-exclude everything file in the src folder), using the default _--output-type_ (=report any dependency-violations). The svg folder doesn't exist though, apparently, so dependency-cruiser complains about that and quits.


> windows is a supported operating system, despite its peculiarities. Each change to dependency-cruiser gets automatically tested on a windows machine [here's for instance the latest results for the build of release 9.15.0](https://github.com/sverweij/dependency-cruiser/runs/1205674963?check_suite_focus=true)
