### ISSUE TITLE
Questions : How to start analyzing child dependencies from a files without any parent dependencies ?

### ISSUE THREAD

**Issue by speedfire514** [sverweij/dependency-cruiser#382]
This tool is really useful to run rules and analyze a project. I run into some issues try to analyze some part of code dependencies.
I would like to analyze a file child dependencies to a good level of detail (-S 6 for instance) but I am not interested to view the parent dependencies. Basically, it is to display only downward dependencies (child). I am having a hard time to do that and wonder if there is something I'm missing.
-Focus : highlight the file to analyze but is not going too deep in level (-S 6)
-Exclude : not an easy option. We have to generate every time and exclude some path. It won't even work if by any chance, the path to exclude because it was a parent dependencies is finally used by a child dependent

I tried to find different approach but I could not manage to do that easily. At the end of the day, to address an analysis like the one I want to perform, maybe a  --downward-dependencies option is the only viable solution.

Do you have any idea how I could do that ? Is it something I'm missing ? Can we start discussing potential solutions ?

**Comment by sverweij** [comment]
Hi @speedfire514 
- it's  possible to start the cruise at the file you want to analyse - it'll automatically only analyse the files the module and the modules it depends upon. 
- If you want to limit the number of (grand^n)-children would [--max-depth](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/cli.md#--max-depth) (see [here](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/options-reference.md#maxdepth) for examples) be of help?
