### ISSUE TITLE
documentation: init vs report config file

### ISSUE THREAD

**Issue by wiese** [sverweij/dependency-cruiser#383]
### Summary

The [documentation](https://github.com/sverweij/dependency-cruiser/tree/4c24cfca0e4595d69f949d7256ad18dccdc553ce#validate-things) does a good job of getting users started (thanks for that). This includes how generate the config (via the `depcruise --init` command), as well as how to run reports. The reporting step is documented to rely on a config file passed (`.dependency-cruiser.json`). The init step however creates a file with a different extension (`.dependency-cruiser.js`) and is also documented like this. I.e. running the reporting step as documented results in an error.

> ERROR: Can't open '.dependency-cruiser.json' for reading. Does it exist? (You can create a dependency-cruiser configuration file with depcruise --init .)

If I use the JS file generated in the init step to feed the validate command then everything works fine.

### Context

I just found this project and it looks very helpful indeed. Not sure if it's a bug or I'm just not understanding yet. Just tripped over this upon my first trying it out. 

### Environment

- Version used: 4c24cfca0e4595d69f949d7256ad18dccdc553ce

**Comment by sverweij** [comment]
Thanks @wiese you indeed spotted a documentation bug - I'll fix it in a minute!

> The configuration format started out as json, and to this is still supported. dependency-cruiser's _--init_ doesn't generate them anymore, though because the .js format is more readable and more flexible to use
