### ISSUE TITLE
zsh: command not found: depcruise-fmt

### ISSUE THREAD

**Issue by techbirds** [sverweij/dependency-cruiser#385]
just execute depcruise command:

```
npx depcruise --validate --output-type anon src | depcruise-fmt --output-type dot - | dot -T svg > anonymized_graph.svg
```

error:

```
zsh: command not found: depcruise-fmt
zsh: command not found: dot
```

**Comment by hantatsang** [comment]
@techbirds Can you share how did you resolve this error?

**Comment by sverweij** [comment]
Hi @hantatsang - can't speak for @techbirds, but in both cases the shell complains it can't find the executable

- in case of depcruise-fmt: when you've installed it locally, planting `npx` in front of it will make it run
  (npx is a command that ships with npm that executes scripts in your local node_modules - see [this article](https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b) for an intro) 
- in case of dot: that's an executable from the GraphViz package, which translates graph descriptions into nice pictures. They have instructions in their [download](https://graphviz.gitlab.io/download/) page on how to install it on your OS.

```sh
npx depcruise --validate --output-type anon src | npx depcruise-fmt --output-type dot - | dot -T svg > anonymized_graph.svg
```

**Comment by hantatsang** [comment]
Thanks @sverweij 

Just a note for MacOS (Big Sur) user installing `graphviz`:

`brew install graphviz` didn't resolve the `command not found: dot` error for me.
I installed [MaxPorts](https://www.macports.org/install.php) and ran `sudo ports install graphviz` instead.
