### ISSUE TITLE
Not a bug or a feature: Permission to use sample images

### ISSUE THREAD

**Issue by hasanbalci** [sverweij/dependency-cruiser#391]
Hi, I'm writing an academic journal paper about graph visualization and in my paper I want to use one the images (probably the chalk example) in doc/real-world-samples folder of this repository. I ask for your permission to be able to use this image in my paper. If you give permission, I will cite the url of the image unless you want me to cite another resource. 

Thanks in advance!

**Comment by sverweij** [comment]
Hi @hasanbalci - feel free to use the image, and use the url of the image for citation (for context: the graphs are all generated by passing dot output from dependency-cruiser through  GraphViz dot).

And I'd of course like to read your paper - (better) graph visualisation has my warm interest :-)

**Comment by hasanbalci** [comment]
Thanks again! Of course, I will share my paper when it is published.
