### ISSUE TITLE
moreThanOneDependencyType: false doesn’t work as documented

### ISSUE THREAD

**Issue by lo1tuma** [sverweij/dependency-cruiser#399]
I’ve installed dependency-cruiser and created my initial config with the `--init` flag.

The generated `not-to-dev-dep` rule seems quite useful and I want to use this rule, but I n eed to adjust it a little bit. In my case I have a scenario where I want to allow using a devDependency but only when the same dependency is also defined as a peerDependency. So I had the idea to use `moreThanOneDependencyType: false` for that:

```
        {
            name: 'not-to-dev-dep',
            severity: 'error',
            from: {
                path: 'src/',
                pathNot: ['\\.test\\.(js|ts|jsx|tsx)$']
            },
            to: {
                dependencyTypes: ['npm-dev'],
                moreThanOneDependencyType: false
            }
        }
```

As I understand the documentation this should only match when a devDependency is required and when only exactly 0 ore 1 dependency types exist. But I still get an error reported.

**Comment by sverweij** [comment]
@lo1tuma thanks for this issue - your expectation based on the documentation is entirely correct! The implementation is currently not matching it, though (a.k.a. you found a bug :-) ). Looks like an easy fix, so as soon I have some bandwidth (likely in the weekend at the earliest) I'll make a PR for it.

**Comment by sverweij** [comment]
hi @lo1tuma - couldn't sleep and the fix indeed seemed to be straightforward so now there's a PR (☝️) that should fix the issue - I've released it with a beta tag on npm as `dependency-cruiser@9.17.1-beta-2`.  Could you give it a spin and let me know whether it works for your use case?

**Comment by lo1tuma** [comment]
Hi @sverweij, I hope this bug report was not the reason you couldn’t sleep. I’ve just tested the beta version and it works like as expected. Thank you!

**Comment by sverweij** [comment]
@lo1tuma the insomnia was not related to this bug report :-) . Thanks for the validation, I'll merge it so it'll be part of the next upcoming regular release.
