### ISSUE TITLE
Only the first violation per import is reported

### ISSUE THREAD

**Issue by ajafff** [sverweij/dependency-cruiser#40]
### Expected Behavior
Consider the following config:

```json
{
  "forbidden": [
    {
      "name": "no-core",
      "severity": "info",
      "from": {
        "path": "^src/"
      },
      "to": {
        "dependencyTypes": [
          "core"
        ]
      }
    },
    {
      "name": "no-fs",
      "severity": "error",
      "from": {},
      "to": {
        "dependencyTypes": [
          "core"
        ],
        "path": "^fs$"
      }
    }
  ],
  "allowed": [
    {
      "from": {
        "path": "^src/foo.js$"
      },
      "to": {
        "path": "^src/bar.js$"
      }
    }
  ]
}
```

and a file named `src/foo.js` with the following content:

```js
require('fs');
```

I expect the following output:

```
warn not-in-allowed: src/foo.js → fs
info no-core: src/foo.js → fs
error no-fs: src/foo.js → fs
```

and a non-zero exit code.

### Current Behavior
```
warn not-in-allowed: src/foo.js → fs
```
and exit code 0
### Possible Solution
In `validateAgainstRules` use `filter` instead of `find`. Also don't return early if none of the allowed rules matched.

Or sort by severity and report the first violation with the highest severity.

### Steps to Reproduce (for bugs)
See above

### Context
I noticed this when updating to 3.0.0-beta-1. Once the `not-in-allowed` warnings were gone, I had a few errors which previously didn't show up.
I remembered to report it as I saw what causes is while reviewing #39

Also note if you remove the `allowed` section, you will only see the message with severity info which doesn't end the process with an non-zero exit code.

### Your Environment

* Version used:
* Node version:
* Operating System and version:
* Link to your project:

**Comment by sverweij** [comment]
True. The code assumes we can only violate one rule per module. That was a good place to start a.o. with performance in mind, but also a bit optimistic - and not adequate in many cases. I'll change it.

The changes you suggest in `validateAgainstRules` are simple, but also ripple through to the reporter interface - and will technically be breaking. Ah well - there's a major bump coming up anyway :-)

**Comment by sverweij** [comment]
dependency-cruiser@3.0.0-beta-5 has the simple solution (return the highest severity violated rule) - as the first step towards the correct change. The correct change itself will follow along in the same PR (but not tonight... 🛌 )
