### ISSUE TITLE
Issue: Typescript files not followed more than 1 level deep

### ISSUE THREAD

**Issue by uni0ue** [sverweij/dependency-cruiser#406]
I'm trying to generate a dependency tree with depenendcy-cruiser and GraphViz for a specific typescript file. However, it only shows 1 level deep (regardless of max-depth). It works as expected with javascript files.

Assuming there are 3 typescript files.
```
│── level1.ts
│   ├── level2.ts
│     ├── level3.ts
```
level1.ts imports level2.ts which imports level3.ts

By running `$  depcruise -T dot "level1.ts" | dot -T svg > dependencygraph.svg` 

### Expected Behavior
It generates folllowing graph
![image](https://user-images.githubusercontent.com/4518682/102633357-9cdf4880-4150-11eb-96c3-c2e31722518b.png)

### Current Behavior
It generates folllowing graph (level 3 is missing)
![image](https://user-images.githubusercontent.com/4518682/102627605-b7152880-4148-11eb-8121-839d1c88a058.png)

### Steps to Reproduce (for bugs)

1. Create level1.ts, level2.ts, level3.ts
2. level1.ts imports level2.ts
3. level2.ts imports level3.ts
4. run `$  depcruise -T dot "level1.ts" | dot -T svg > dependencygraph.svg` 

### Context
I'm trying to analyze several pages in a Next.js project separately (e.g. pages/home.tsx). I'd like to visualize all the layers from a page to the most nested tsx component. Maybe I'm missing something? I also tried with specifying the typescript config as a command line option.

### Your Environment

- Version used: 9.19.1
- Node version: v12.16.1
- Operating System and version: Win 10

**Comment by sverweij** [comment]
@uni0ue likely cause is dependency-cruiser can't find the typescript compiler. It needs to be installed in the same spot as dependency-cruiser itself is (see the [FAQ entry on this](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/faq.md#q-typescript-coffeescript-livescript-or-vue-single-file-component-sfc-dependencies-dont-show-up-how-can-i-fix-that) for more info).

**Comment by uni0ue** [comment]
That makes sense and works now, thanks @sverweij. Sorry I missed that part in the FAQ since it was kinda working already.

**Comment by danielo515** [comment]
Wait a second. How does this work if I want to use dep-cruiser as a global dependency but run it inside a typescript folder?

**Comment by sverweij** [comment]
It would use the typescript compiler that is installed globally - if any. 

B.t.w. running dependency-cruiser as a local install has the benefit it will  use the compilers and tools your local project also uses. This will ensure the results it gets have a better guarantee to match what is actually going on in your project.

**Comment by danielo515** [comment]
> B.t.w. running dependency-cruiser as a local install has the benefit it will use the compilers and tools your local project also uses. This will ensure the results it gets have a better guarantee to match what is actually going on in your project.

After installing it locally indeed it started working as I expected. I think the importance of installing it locally is not highlighted enough.
