### ISSUE TITLE
Improvement: filter more early in initial file gathering

### ISSUE THREAD

**Issue by sverweij** [sverweij/dependency-cruiser#409]
@curledUpSheep wrote in #386:

> I'm facing a similar performance issue (dependency-cruiser 9.21.0, Windows 10, SSD):
> 
> ```
> 169905ms     148Mb     114Mb reading files
> ...
> × 2 dependency violations (0 errors, 2 warnings). 1153 modules, 3799 dependencies cruised.
> 
>       3ms     149Mb     124Mb really done (171364ms)
> ```
>
> I'm running depcruise on a Lerna monorepo with quite some symlinks to internal packages in the monorepo, sometimes nested.
>
> In my case, it seems the issue is the `gatherScannableFilesFromDirectory` function in `gather-initial-sources.js`. This recursively builds a huge list of files, only performing filtering when it gets down to the level of actual files. This means that, if I set a `doNotFollow` for `node_modules`, it will still go into the node_modules folder and list all files as deep as it can.
>
> For our particular repo, this leads to `gatherScannableFilesFromDirectory` being called a huge number of times with paths like `api\node_modules\@company\internal-symlinked-package-A\node_modules\@company\internal-symlinked-package-B\node_modules\@company\internal-symlinked-package-C\node_modules\@babel\helper-member-expression-to-functions\node_modules\lodash\fp` (even though all of these files will be excluded from the result because we have a `doNotFollow` for `node_modules`).
>
> As a test, I added the following code at the start of `gatherScannableFilesFromDirectory`'s `.reduce()` callback:
>
> ```
> if (!keepNonExcluded(pathToPosix(path.join(pDirectoryName, pFileName)), pOptions)) {
>   return pSum;
> }
> ```
>
> This results in a >10x performance improvement on our repo (from >2.5 minutes to 15 seconds):
>
> ```
> 14782ms     146Mb     117Mb reading files
> ...
> × 2 dependency violations (0 errors, 2 warnings). 1153 modules, 3799 dependencies cruised.
> 
>       6ms     147Mb     128Mb really done (15853ms)
> ```
>
> For our use case, this doesn't seem to affect any of the rule checking (it looks like `gatherScannableFilesFromDirectory` would filter out these files anyway). However, I can imagine that this breaks behavior for people using `doNotFollow`, `includeOnly` or `exclude` with expressions that are intended to be checked only against the full file path.
>
> Still, I think it's a very common use case to have a `doNotFollow` with a `path` array only containing simple strings like `node_modules`, `coverage`, `test-reports` etc. where it's safe to exclude matching directories without going any deeper. If we could detect those cases and apply the filtering as early as possible, it could result in quite a big performance gain.
>
> @sverweij do you think it would make sense to set up something like this? If you don't have the bandwidth to implement it, I might be able to free up some time to create a PR.
>
> _Edit: base before and after on exactly the same files with exactly the same settings_

_Originally posted by @curledUpSheep in https://github.com/sverweij/dependency-cruiser/issues/386#issuecomment-750308623_

**Comment by sverweij** [comment]
Hi @curledUpSheep thanks for your research and for reaching out. I've been able to reproduce the issue (and improvement) on macOS.

Your guess that it's a breaking change is correct - some `includeOnly` unit/ integration tests broke, but as far as I can reason (and tests seem to prove) there's no regression for `exclude` and `doNotFollow`. So I've refactored the gatherScannableFilesFromDirectory to early filter those.

=> The version in the PR now is published to npm as `dependency-cruiser@9.21.1-beta-1` - could you let me know if this fixes the issue for you as well?

> P.S. I've created a new issue for it, so it's easier to track.

**Comment by curledUpSheep** [comment]
@sverweij thanks for diving into this so quickly!

I just tested with `dependency-cruiser@9.21.1-beta-1`, this indeed fixes the performance issue for me (same running time as my earlier hacky solution).
