### ISSUE TITLE
Issue: depcruise --init CLI errors out on mac

### ISSUE THREAD

**Issue by bx-ali** [sverweij/dependency-cruiser#416]
On initializing the cruiser, I get the error 
  ```ERROR: The "path" argument must be of type string or an instance of Buffer or URL. Received an instance of Object```

This happens when I use the default options or try to select no for test files. 

the CLI to allow me to not indicate test files

```
 alirezatajadod$ depcruise --init
? Where do your source files live? src
? Do your test files live in a separate folder? (Y/n) n
``` 
on input above
```
? Where do your source files live? src
? Do your test files live in a separate folder? No

  ERROR: The "path" argument must be of type string or an instance of Buffer or URL. Received an instance of Object
```
### Steps to Reproduce (for bugs)

1.  run depcruise --init
2. select default for src files
3. type n for where do your tests live

### Context

cant initialize and use the software

### Your Environment

I am using a MAC OS and bash running Fedora. 

- Version used: 9.21.3
- Node version:v12.18.3
- Operating System and version: MAC OS, Big Sur 11.1
- Link to your project: private

**Comment by sverweij** [comment]
hi @bx-ali thanks for raising this! I've reproduced the issue and there will be a fix tonight (GMT+1). 

In the mean time you can run `depcruise --init` with `yes` as an extra parameter: `depcruise --init yes`. This will create a `.dependency-cruiser.js` config with defaults that will work in your environment.

**Comment by sverweij** [comment]
Hey @bx-ali `dependency-cruiser@9.21.4` has just been published on npm - this includes the freshly merged fix.
