### ISSUE TITLE
Not a bug or a feature: What's the best way to publish rules?

### ISSUE THREAD

**Issue by jLouzado** [sverweij/dependency-cruiser#418]
### Summary

Similar to the lint eco-system, it'd be nice if people could make and publish cruiser-rules.

The problem with just publishing a gist and having people copy-paste it into their projects is that there's no sense of versioning; if an update is pushed a dependant project needs to manually update the rule.

Is there already a way to accomplish this? would appreciate any help, thank you.

**Comment by sverweij** [comment]
Thanks for this question @jLouzado

There's two ways to do this - using node's `require` (recommended) or through dependency-cruiser's own `extends` mechanism.

HTH

## Using require

The configuration file that contain the rules (typically `.dependency-cruiser.js`) is plain javascript and you can use `require` to import rules, entire sets of rules, and options to compose them. That way you can reference them locally, or publish them to a central registry (like npm - or your companies' one) and reference them like you would any node_module.

Example for a locally defined rule:

```javascript
// file: ./configs/not-to-unresolvable.js
module.exports = {
  name: "not-to-unresolvable",
  comment:
    "This module depends on a module that cannot be found ('resolved to disk'). " +
    "If it's an npm module: add it to your package.json. In all other cases you " +
    "likely already know what to do.",
  severity: "error",
  from: {},
  to: {
    couldNotResolve: true,
  },
};
```

```javascript
// .dependency-cruiser.js
const notToUnresolvableRule = require('./configs/not-to-unresolvable');

module.exports = {
  forbidden: [
    notToUresolvable
    // more rules here either referenced or not.
  ],
  options: {
    // your options here
  }
}
```

Dependency-cruiser uses this mechanism for its 'recommended' preset - see [configs source code](https://github.com/sverweij/dependency-cruiser/tree/develop/configs) for an example.

## using dependency-cruiser's configuration `extends` mechanism

It's also possible to use dependency-cruiser's [`extends`](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/rules-reference.md#extends) mechanism which came to fruit when it the preferred way to specify a configuration was still json. I still works to this day, even with configurations in javascript. The advantage is that it automatically takes care of merging multiple rule sets, which can be pain in bespoke setups. Disadvantage: takes a bit to get used to the semantics (see linked documentation).

That said, today I'd go for the straightforwardness of the _Using require_ approach.

**Comment by jLouzado** [comment]
thank you very much 🙌🏽
