### ISSUE TITLE
Feature request: handle dynamic alias packages such as module-alias

### ISSUE THREAD

**Issue by ulfakerlind** [sverweij/dependency-cruiser#435]
My guess is that this is out of scope 
### Context

Due to the dynamic routing of module-alias, depcruiser cant find the modules that have recieved an arbitrary mapping like src/common -> @common

### Expected Behavior

a generic de-mapping for specific strings in imports would be nice

### Current Behavior

mappings are ignored and imports fail

### Possible Solution

adding demapping rules -> @common -> src/common

**Comment by sverweij** [comment]
Hi @ulfakerlind - thanks for this question. What do you currently use to get these aliases resolved?

dependency-cruiser currently supports aliases (/ path redefinitions/ folder mapping/ ...) as defined in either TypeScript's `tsconfig.json`, webpack's configs or one of the myriad of babel plugins that support this. When you tell dependency-cruiser (either in a config file or as command line switches) where these live, it should nicely resolve the aliased module name (`@common`) to the real module name on disk (`src/common`). If it doesn't you might've bumped into a bug. 

Usually `depcruise --init` will detect the configs for you and save them correctly in .dependency-cruiser.js, but it might be your environment uses alternate names and/ or locations, and you might need to set them manually. Here's some references

- TypeScript: 
  - [configuring tsconfig in .dependency-cruiser.js](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/options-reference.md#tsconfig-use-a-typescript-configuration-file-project)
  - [specifying a tsconfig on the cli](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/cli.md#--ts-config-use-a-typescript-configuration-file-project)
- WebPack: 
  - [configuring webpack configs in .dependency-cruiser.js](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/options-reference.md#webpackconfig-use-the-resolution-options-of-a-webpack-configuration)
  -  [using webpack configs in the dependency-cruiser cli](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/cli.md#--webpack-config-use-the-resolution-options-of-a-webpack-configuration)
- Babel: 
  - [specifying a babel config in .dependency-cruiser.js](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/options-reference.md#babelconfig-use-a-babel-configuration-file)
  - (not available in the cli yet)

Then again if your environment uses something different than these three - consider me interested!

**Comment by ulfakerlind** [comment]
Oh ok! Well then maybe its just not implemented. The npm package is called "module-alias" :)

**Comment by sverweij** [comment]
Hi @ulfakerlind - so apparently [`module-alias`](https://github.com/ilearnio/module-alias) is yet another way to define aliases. I learned something today :-) . When I understand its documentation correctly there's two ways to use it:

1. declaratively - by defining a bunch of aliases in package.json. In their readme the [usage with webpack](https://github.com/ilearnio/module-alias#usage-with-webpack) section suggests the format to be compatible with webpack. If this is indeed the case dependency-cruiser supports it (indirectly - see below).
2. programmatically - by adding aliases while the program _at runtime_. I can't think of a sane use case for this over the declarative approach, but a scan of some >100 star repo's on GitHub that use it learns it is used in the field nonetheless. So maybe there _is_ some 🤷 . As dependency-cruiser is trying to focus on doing static analysis well, programmatic aliases are  out of scope for now.

Many repo's seem to use `module-alias` it so they can reference themselves easily. As this is now a native, out of the box feature of node (on node ^12.19/ >=14.7), and it already worked earlier on if you were on yarn or (IIRC) pnpm, I expect the use of module-alias will become less over time. Moreover it seems `module-alias` hasn't been published for over a year.

#### Using the declarative way with dependency-cruiser

- create a webpack.config.js as described in [module-alias's README](https://github.com/ilearnio/module-alias#usage-with-webpack)
- tell dependency-cruiser about it, either via the [command line](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/cli.md#--webpack-config-use-the-resolution-options-of-a-webpack-configuration) or in the [.dependency-cruiser.js](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/options-reference.md#webpackconfig-use-the-resolution-options-of-a-webpack-configuration)
- you're set

(It's possible to make dependency-cruiser do that automatically - let me know if that'd help, then I'll put it on the backlog)
