### ISSUE TITLE
Issue: Dependency graph doesn't seem to detect any dependencies beyond the first level

### ISSUE THREAD

**Issue by dominictwlee** [sverweij/dependency-cruiser#436]
I tried replicating some of the real world examples from the README, but they don't seem to generate a correct dependency graph. What I did was clone the tslint repo, and executed the cli command shown in the docs.

`dependency-cruise -T dot -x node_modules -- src/index.ts  | dot -T png > tslint-without-node_modules.png` 

What I ended up getting as a result was this:
![image](https://user-images.githubusercontent.com/34794189/106389681-8299bb00-63dc-11eb-823e-52c7c958660c.png)

It seems to only detect the immediate dependencies of index.ts, then stops there and ignores all the dependencies of its children.

### Expected Behavior
I expected a detailed representation of all dependencies as shown in real world examples for tslint
https://github.com/sverweij/dependency-cruiser/blob/develop/doc/real-world-samples/tslint-without-node_modules.png

### Current Behavior
I've tried this across various repos, and they all similarly detected  the immediate dependencies for index.ts/js, and ignored all the subsequent nodes in the graph, as shown in the first picture.

### Possible Solution
No idea, I initially thought it was user error, but given that I followed the exact example shown in the README for TSlint, this could potentially be a bug?

### Steps to Reproduce (for bugs)

1. Clone tslint repo
2. Execute the command shown above (I copied it from the README, minus the validation)
3. Expect a full dependency graph
4.Only get a small graph that shows the immediate dependencies of index.ts

### Context
Was hoping to use this to help me learn codebases, but didn't manage to get it going. I hope it's just some sort of user error, but doesn't seem to be the case since I used the provided examples.

### Your Environment

- Version used: latest
- Node version: 14.15.4
- Operating System and version: Pop!_OS 20.10

**Comment by sverweij** [comment]
Hi @dominictwlee thanks for reaching out on this. 

It looks like dependency-cruiser can't find the typescript compiler. When dependency-cruiser runs, it looks for compilers in the spot where it's installed. If it's installed globally, it'll look for the globally installed typescript compiler. When dependency-cruiser is installed in

Would this [this FAQ entry](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/faq.md#q-typescript-coffeescript-livescript-or-vue-single-file-component-sfc-dependencies-dont-show-up-how-can-i-fix-that) be of help?

As you're not the first to bump into this (and likely not the last either) I'll see if it's possible to automatically detect
this and propose alternatives (e.g. when during --init it sees a .ts, but it doesn't see a typescript compiler => point to FAQ).

HTH 

> Just to make sure there isn't anything wonky going on with tslint I've just tried to replay it, both with 
> dependency-cruiser installed in the same folder and (see below the picture) with a globally installed 
> one, and both seem to work AOK...

```sh
git clone git@github.com:palantir/tslint.git
cd tslint
yarn add -D dependency-cruiser

# create a dependency-cruiser config (and automatically answer 'yes' to all questions the --init command asks
# so it automatically uses the tsconfig.json,  guesses the root paths etc. etc.):
yarn depcruise --init yes
```

> Now you can start to make graphs and check for rules. For the former e.g.:

```sh
# --include-only: 
# --config looks for the .dependency-cruiser.js - no need to specify the file name unless the thing has a different name
# --collapse: summarise up to two levels deep. Increase to see more detail (& larger graphs)
yarn -s depcruise bin src --include-only "^(bin|src)" --config --collapse 2 --output-type dot | \
  # the -Gsplines=ortho is to get graphviz to render straight lines (which makes a world of 
  # difference for graphs with < ~100 nodes). When the graph is bigger graphviz might not
  # be able to cope, so then leave it out
  dot -Gsplines=ortho -T svg | \
  # depcruise-wrap-stream-in-html adds some interactivity to the graphviz dot output
  yarn -s depcruise-wrap-stream-in-html > high-level-dependency-graph.html
```
> which yields something like this:

<img width="806" alt="image" src="https://user-images.githubusercontent.com/4822597/106392603-e4fdb600-63f2-11eb-92cb-6539fa1b9834.png">

> After this I repeated the process with a global installed version of dependency-cruiser, which yielded the same result:

```sh
# install dependency-cruiser _and_ the typescript compiler globally
npm i --global dependency-cruiser typescript

git clone git@github.com:palantir/tslint.git
cd tslint

# Typically no need to prefix depcruise or depcruise-wrap-stream-in-html with yarn -s (or npx) when installed globally:
depcruise bin src --progress --include-only "^(bin|src)" --config --collapse 2 --output-type dot | \
  dot -Gsplines=ortho -T svg | \
  depcruise-wrap-stream-in-html > high-level-dependency-graph.html
```

**Comment by dominictwlee** [comment]
@sverweij  Ah damn, sorry about that, completely missed the FAQ when trying to debug this issue.

Yep all clear now, thanks for pointing me in the right direction!
