### ISSUE TITLE
Capturing groups not working given reachable property

### ISSUE THREAD

**Issue by ben-eb** [sverweij/dependency-cruiser#442]
Hello! 👋 

Thanks for your work on this library, it's really useful! 👍 

I'm trying to validate that each service that I have is self-contained and has a single entry point with no dead code. I thought I could use capturing groups to achieve this, like so:

```json
{
  "forbidden": [
    {
      "name": "no-unreachable-from-entrypoint",
      "severity": "error",
      "from": { "path": "^services/([^/]+)/index\\.js$" },
      "to": { "path": "^services/$1", "reachable": false }
    }
  ]
}
```

### Expected Behavior

The capturing groups should work with the `reachable` property set.

### Current Behavior

The tool is not detecting the unreachable code inside the directory. What I can do as a workaround is to duplicate the rule:

```json
{
  "forbidden": [
    {
      "name": "no-unreachable-from-entrypoint-one",
      "severity": "error",
      "from": { "path": "^services/one/index\\.js$" },
      "to": { "path": "^services/one", "reachable": false }
    },
    {
      "name": "no-unreachable-from-entrypoint-two",
      "severity": "error",
      "from": { "path": "^services/two/index\\.js$" },
      "to": { "path": "^services/two", "reachable": false }
    }
  ]
}
```

I would prefer not to have to do this, but it's a possibility. 🙂 

### Steps to Reproduce (for bugs)

Given the following:

```
services
├── one
│   ├── index.js
│   └── unreachable.js
```

Using the config above, we should get a warning for `unreachable.js`. Trying with capturing groups instead does not produce an error.

### Your Environment

- Version used: 9.23.0
- Node version: v12.16.1
- Operating System and version: OS X Mojave
- Link to your project: _private_

**Comment by sverweij** [comment]
Hi @ben-eb thanks for reporting this omission! It's indeed not implemented and it's somewhat non-trivial to add - a.k.a. a nice challenge => I'm working on it. Expect a heads-up in the coming days.

**Comment by ben-eb** [comment]
@sverweij You're welcome! That sounds good, I like a challenge too! Thanks for keeping me posted. 🙂

**Comment by sverweij** [comment]
@ben-eb got first a working version up. I suspect it could be made a little faster by giving the algorithm some attention, but it's working well otherwise.

Anyway - if you want to try it out it's on npm as `dependency-cruiser@9.23.1-beta-1`. All feedback is welcome!

**Comment by ben-eb** [comment]
@sverweij That was quick, thank you! 👍 

I've had a quick play with the beta release and it looks to be doing everything I expected. My full config is below:

```json
{
  "forbidden": [
    {
      "name": "no-linked-services",
      "severity": "error",
      "from": { "path": "^services/([^/]+)/.+" },
      "to": {
        "path": "^services/([^/]+)/.+",
        "pathNot": "^services/$1/.+"
      }
    },
    {
      "name": "no-unreachable-from-entrypoint",
      "severity": "error",
      "from": { "path": "^services/([^/]+)/index\\.js$" },
      "to": {
        "path": "^services/$1",
        "pathNot": "test\\.js$",
        "reachable": false
      }
    }
  ]
}
```

This is now working properly! 🎉
