### ISSUE TITLE
Feature request: Have a way to know if a file is shared

### ISSUE THREAD

**Issue by davidparkagoda** [sverweij/dependency-cruiser#445]
### Context

Currently dependency cruiser is helping me to consolidate where files are being used multiple times and have more visibility. However there are times where files that are used multiple times are put into a shared folder, and after some refactoring, they are not used multiple times. I would like a way to know whether or not a file is shared.

### Possible Solution

Maybe something like this?
```
{
  "name": "must-share",
  "severity": "warn",
  "from": {
    "path": "^src/components", // files importing
  }
  "to": {
    "path": "^src/shared", // files exporting
    "shared": true, // or maybe numerical in some way?
  }
}
```
```
\---src
    +---components
    |       imports-1-2.ts
    |       imports-1.ts
    |       
    \---shared
            1.ts
            2.ts
```
dependency cruiser would complain about file `2.ts` with this rule

### Considered alternatives

I was wracking my head on how to do something like this with the current set of rules. In the end I do not think it is possible. It looks like I need a way to state how many times an import/export happens.

**Comment by sverweij** [comment]
Hi @davidparkagoda - this will be a useful addition to dependency-cruiser's capabilities, thanks for the suggestion! 

It doesn't seem too hard to implement - but I'll need to sleep a night on it to understand all angles.

I like your suggestion to have it 'maybe numerical in some way' - in that way it'll enable other rules as well (limit # of dependencies, flag if there's only 2 dependant (like in your example) or only 3 (e.g. when there's a rule there have to be _at least_ 3 occurrences before generic'ing it)). I.e.

```json
{
  "name": "must-share",
  "severity": "warn",
  "from": {
    "path": "^src/components", // files importing
  }
  "to": {
    "path": "^src/shared", // files exporting
    "minDependants": 2, // syntax t.b.d. 
    "maxDependencies": 10 // syntax t.b.d.
  }
}
```

=> Do I understand correctly b.t.w. that if a module in `src/shared` is used 10 times, but only 2 times from src/componts, this rule  should fire?

**Comment by davidparkagoda** [comment]
Yes. Ideally in my current real world scenario, I would have another rule to make sure that shared is only being used from `src/components`.

**Comment by sverweij** [comment]
Hey @davidparkagoda I've made a quick sketch (working, including unit tests - don't worry I didn't go full cowboy yet) to get a feel for this feature. It's published on npm as `dependency-cruiser@9.24.0-beta-1`

=> Could you let me know if this first sketch matches what you need it for? Is it performant enough? What do you still miss?

A rule like this should now flag all modules that have 0 or 1 dependents in the _src/components_ folder:

```javascript
{
  "name": "must-share",
  "severity": "warn",
  "from": {
    "path": "^src/components", 
  },
  "to": {
    "path": "^src/shared",
    "numberOfDependentsLessThan": 2 // can be any number from 0 to 100
  }
}
```

- it works with _path_ and _pathNot_ restrictions on both the _from_ and _to_ parts of the rule
- the semantics work, but I still have to sleep a night over how it fits in with other rules (this might mean interface changes to what you see above).
- there's a (temporary) rule in dependency-cruiser's own config I've used to play around with the rule - you can find it [here](https://github.com/sverweij/dependency-cruiser/blob/feature/adds-dependents-count-validation/.dependency-cruiser.json#L6)
- (if you're curious about the code - it's in the [feature/adds-dependents-count-validation](https://github.com/sverweij/dependency-cruiser/tree/feature/adds-dependents-count-validation) branch)

Some limitations in the sketch:
- [group matching](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/rules-reference.md#group-matching) doesn't work yet. (This might be useful when there's lot of _shared_ folders sprinkled through the code base you want to apply this rule to)
- it only works in _forbidden_ rules (_allowed_ and _required_ might follow later on)
- documentation is limited to this issue a.t.m.
- I just discovered the typescript type definition doesn't have the _numberOfDependentsLessThan_ attribute in it.
- there is a performance impact when there's at least one dependents rule: ~30ms on dependency-cruiser's own (small) code base, (~400 modules/ 970 dependencies) which typically takes ~2s to run - (2.6Ghz quad core intel i7 on macOS).

**Comment by davidparkagoda** [comment]
It looks great, already getting some interesting insights

I do not have any comments on performance as I am still experimenting with dependency-cruiser

**Comment by sverweij** [comment]
Hey @davidparkagoda as you might've seen I've opened a PR that addresses the points from my previous comment. I've made one change to the syntax so it's easier to expand the pattern, and to make clear the semantics of the restrictions is different from a regular from -> to rule ([required](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/rules-reference.md#required) rules use this as well for the same reason).

```javascript
{
  "name": "must-share",
  "severity": "warn",
  "from": {
    "path": "^src/components", 
  },
  "module": { // changed from "to" to "module"
    "path": "^src/shared",
    "numberOfDependentsLessThan": 2 // can be any number from 0 to 100
  }
}
```

E.g. if we wanted to have a rule that limits the number of dependencies on internal modules (but that doesn't care about external depencies) we could hypothetically do this:

```javascript
{
  "name": "limit-max-internal-dependencies",
  "severity": "warn",
  "module": {
    "path": "^src",
    "numberOfDependenciesLessThan": 8 
  },
  "to": {
    "path": "^src/" 
  }
}
```

**Comment by sverweij** [comment]
@davidparkagoda the dependents ('numberOfDependentsLesThan') feature is part of the regular release (as of dependency-cruiser@9.24.0) since an hour ago. Feedback is still welcome.
