### ISSUE TITLE
Feature request: Add ability to filter "via" when using reachable rule 

### ISSUE THREAD

**Issue by Obi-Dann** [sverweij/dependency-cruiser#452]
I am trying to write a rule to ensure no view/UI specific code is referenced from view models.
So far my reachable rule looks like that:
```js
{
    name: 'no-ui-assets-in-view-models',
    severity: 'error',
    from: {
        path: ['ViewModel\\.ts$'],
    },
    to: {
        path: ['(\\.s?css)', '(\\.tsx)'],
        pathNot: ['ViewModel\\.ts$'],
        reachable: true,
    },
},
```

It works well, but the problem is that I am getting a lot more errors than useful because some of the view models reference other view models, so the errors may look like that:
```
  error no-ui-assets-in-view-models: src/pages/CreateEvent/Sections/InterviewDetails/InterviewDetailsViewModel.ts → src/components/DateTimePicker/DateOfBirthPicker.scss
      src/pages/CreateEvent/Sections/InterviewDetails/InterviewDetailsViewModel.ts
      →
      src/pages/CreateEvent/Sections/EventLocation/EventLocationViewModel.ts →
      src/components/SiteSelector/SiteSelector.tsx →
      src/components/Forms/FormControls.tsx →
      src/components/DateTimePicker/DateOfBirthPicker.tsx →
      src/components/DateTimePicker/DateOfBirthPicker.scss
  error no-ui-assets-in-view-models: src/pages/CreateEvent/Sections/InterviewDetails/InterviewDetailsViewModel.ts → src/components/DateTimePicker/Calendar.tsx
      src/pages/CreateEvent/Sections/InterviewDetails/InterviewDetailsViewModel.ts
      →
      src/pages/CreateEvent/Sections/EventLocation/EventLocationViewModel.ts →
      src/components/SiteSelector/SiteSelector.tsx →
      src/components/Forms/FormControls.tsx →
      src/components/DateTimePicker/DateOfBirthPicker.tsx →
      src/components/DateTimePicker/DatePicker.tsx →
      src/components/DateTimePicker/Calendar.tsx
```

### Current Behavior
In this case, the issue is with `EventLocationViewModel.ts` that it references some UI components, but I get also errors on every other module that requires `EventLocationViewModel.ts`. It's still useful, but much harder to see the root case

### Expected Behavior
I think there should be a way to either aggregate this kind of issues or be able to filter `via`, eg. to forbid going from `ViewModel` to `scss` but only when it does not go via another `ViewModel`.

### Possible Solution
I've been thinking whether `reachable` can be extended to take a regex or `pathNot` for reachable rules should also be filtering `via`. I can give a crack creating a PR but would be keen to agree on the approach.

**Comment by sverweij** [comment]
hi @Obi-Dann thanks for this feature request! If I understand correctly the rule is trying to find the one perpretator violating the border between view-models and things in views (`EventLocationViewModel.ts` -> `SiteSelector` - check?)

![image](https://user-images.githubusercontent.com/4822597/114276769-6b082f80-9a28-11eb-977c-e270384e7be6.png)

Would a direct rule work for your use case (so without the `reachable` attribute? E.g. ...

```javascript
{
    name: 'no-ui-assets-in-view-models',
    severity: 'error',
    from: {
        path: ['ViewModel\\.ts$'],
    },
    to: {
        path: ['(\\.s?css)', '(\\.tsx)'],
        pathNot: ['ViewModel\\.ts$'],
    },
}
```

... would yield just the one error we're looking for:
```
error no-ui-assets-in-view-models (direct): src/pages/CreateEvent/Sections/EventLocation/EventLocationViewModel.ts → src/components/SiteSelector/SiteSelector.tsx
```

<img width="422" alt="image" src="https://user-images.githubusercontent.com/4822597/114276899-000b2880-9a29-11eb-89cc-e25fe4e51abf.png">
