### ISSUE TITLE
Generate dependencies among methods / interfaces?

### ISSUE THREAD

**Issue by tamethecomplex** [sverweij/dependency-cruiser#46]
Hi, cool project!

### Expected Behavior
Is it feasible with current tools to output a dependency graph not only among files, but among any symbol which can return output from "find references"?  A dependency graph among files is helpful, but being able to cruise dependencies among any symbol would take this to a whole other level to aid in fine-grained code examination.

### Context
I want to load this dependency graph into a graph database and supplement with javadoc descriptions in order to generate fine-grained code documentation searchable as a web, rather than existing doc tools which output a hierarchy without rich links based on references.

**Comment by sverweij** [comment]
That's a very cool suggestion. It's a bit beyond the scope of what dependency-cruiser was created for, though. (Also, I did have a look into it in the past. It's decidedly non-trivial to execute correctly).

I think that [ternjs](https://github.com/ternjs/tern) or the language services behind visual studio code will come closer to your goals.

Hope this helps...

**Comment by tamethecomplex** [comment]
Got it, thanks :-)  I'll see what else is out there.
