### ISSUE TITLE
Question: How to only visualize dependencies between specific paths while excluding leaf nodes?

### ISSUE THREAD

**Issue by fernandomrtnz** [sverweij/dependency-cruiser#462]
Given 

```
.
└── Paths/
    ├── Foo/
    │   ├── Foo1
    │   └── Foo2/
    │       └── Foo3
    └── Bar
```

where `Foo1` has a dependency on `Bar` and `Foo2` while `Foo2`/`Foo3` have no dependencies on `Bar`. I only want to visualize the dependencies between `Foo` and `Bar`.

How can I omit visualizing the `Foo1` -> `Foo2` -> `Foo3` branch since it never depends on anything in `Bar`?

**Comment by sverweij** [comment]
hi @fernandomrtnz thanks for reaching out on this. If you just want it in your visualisation you can use a [collapse pattern](https://github.com/sverweij/dependency-cruiser/blob/v10.0.0/doc/options-reference.md#summarising-collapsepattern-dot-and-archi-reporters) in the configuration of the dot reporter. You can use regular expressions to decide what to collapse. 

I've put up the sources for the example  in [dependenc-cruiser's reproduction repository](https://github.com/sverweij/dependency-cruiser-repro-repo/tree/main/462), so you can easily play around with options.

Hope this helps!

### example

Let's say the source tree looks like so (click arrow to expand):
<details>
  <summary>example tree</summary>

```
src
├── bar
│   ├── plugh
│   │   ├── titi.js
│   │   └── tutu.js
│   ├── thud
│   │   ├── ipsum.js
│   │   └── lorem.js
│   └── xyzzy.js
├── baz
│   ├── fred
│   │   └── quux.js
│   ├── tata.js
│   └── waldo
│       └── qux.js
├── foo
│   ├── corge
│   │   └── index.js
│   └── grault
│       └── quuz.js
└── toto.js
```

</details>

Let's say you want to only see dependencies between folders directly below `src`. 

### Alternative 1: --collapse on the command line

There's also a quick'n dirty command line parameter to do something similar: [--collapse](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/cli.md#--collapse-summarize-to-folder-depth-or-pattern). It either takes a regular expression (which works similar as those for reporters - see below) or a number that corresponds to a folder depth. To collapse to folders directly under src (= 2 levels deep; 1 for src, 1 for the level below it), you'd use:

```
npx depcruise src --config --output-type dot --collapse 2 |\
    dot -T svg |\
    npx depcruise-wrap-stream-in-html > collapsed-dependency-graph.html
```

### With reporter configuration

The dot based reporters ('dot', 'archi') have a configuration option to  
[summarise/ collapse](https://github.com/sverweij/dependency-cruiser/blob/v10.0.1/doc/options-reference.md#summarising-collapsepattern-dot-and-archi-reporters) based on a regular expression.

Assuming you have a `.dependency-cruiser.js` (if you don't create one with [`depcruise --init`](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/cli.md#--init)), make sure to have something like this in your options section:
```javascript
// ...
  options: {
    doNotFollow: {
      path: "node_modules",
    },
    prefix:
      "https://github.com/sverweij/dependency-cruiser-repro-repo/tree/main/462/src/",

    reporterOptions: {
      dot: {
        collapsePattern: "src/[^/]+",
      },
    },
  },
};
```

Now run depcruise again:

```
npx depcruise src --config --output-type dot |\
    dot -T svg |\
    npx depcruise-wrap-stream-in-html > collapsed-dependency-graph.html
```

### Result

With --collapse or a  `collapsePattern` in the .dependency-cruiser-config the output looks like this:


[<img width="369" alt="image" src="https://user-images.githubusercontent.com/4822597/118355151-e8b2e400-b56e-11eb-80f7-9dc27b043027.png">](https://sverweij.github.io/dependency-cruiser-repro-repo/462/high-level-dependency-graph.html)


And - for comparison - without it:

[<img width="642" alt="image" src="https://user-images.githubusercontent.com/4822597/118355276-637bff00-b56f-11eb-9c05-00fa80930658.png">](https://sverweij.github.io/dependency-cruiser-repro-repo/462/dependency-graph.html)
