### ISSUE TITLE
ERROR: Can't open 'src' for reading. Does it exist?

### ISSUE THREAD

**Issue by appdatasoft** [sverweij/dependency-cruiser#465]
I am on mac

when i run this 
npx depcruise --include-only "^src" --output-type dot src | dot -T svg > dependencygraph.svg    

I am getting 

ERROR: Can't open 'src' for reading. Does it exist?

npx depcruise --init
? This looks like a mono repo. Is that correct? Yes
? Mono repo it is! Where do your packages live? packages
? Do your packages use dependencies declared in the root of your repo? Yes
? Looks like you're using TypeScript. Use a 'tsconfig.json'? Yes
? Full path to your 'tsconfig.json': tsconfig.base.json
? Also regard TypeScript dependencies that exist only before compilation? Yes

  ✔ Successfully created '.dependency-cruiser.js'

**Comment by sverweij** [comment]
hi @appdatasoft it looks like you're trying to get dependency-cruiser to look at a directory that doesn't exist. Judging the interaction with `--init` this does make sense as the source code probably lives in `packages`. So instead this might work better:

```sh
npx depcruise --include-only "^packages" --output-type dot packages | dot -T svg > dependencygraph.svg
```

Usually mono-repos have a lot of modules in them and as a result the dependency graph will be equally large - to an extent it might not have any meaning. If you bump into that, try to limit what dependency-cruiser visualises with the [`--collapse`](https://github.com/sverweij/dependency-cruiser/blob/v10.0.1/doc/cli.md#--collapse-summarize-to-folder-depth-or-pattern) switch. To collapse to a depth of 3 you can use this:

```sh
npx depcruise --include-only "^packages" --output-type dot --collapse 3 packages | dot -T svg > dependencygraph.svg
```

increase the depth if you want to see more, decrease of you want a bit more abstraction.
