### ISSUE TITLE
Is it possible to detect orphaned modules/files...

### ISSUE THREAD

**Issue by adamclerk** [sverweij/dependency-cruiser#47]
...with this tool.

I've looked at the docs and at initial glance I don't think it is.

Just checking...

**Comment by sverweij** [comment]
Thanks for the suggestion! And indeed, it's not in. Yet. It seems totally doable, though (if with 'orphaned modules' you mean modules that have (1) _no dependencies_ and (2) _no modules that depend on it_ - check?).

What is the use case you have for it?

**Comment by sverweij** [comment]
@adamclerk - thanks. I assumed as much, but it's good to have the assumption confirmed.

As you can see in #48 I'm working on it. Detection is in place - I'm on configuring the rules definition & engine.

**Comment by sverweij** [comment]
@adamclerk Configuring the rules definition & engine proved a little harder nut to crack - but it's in there. If you want to try it out: I've published it as a beta on npm, so if you `npm i dependency-cruiser@beta` or `npm i dependency-cruiser@4.0.0-beta-0` you can try it out.

Two things to keep in mind:
- dependency-cruiser will only check for orphans when there's a rule set up for them (sample snippet in the [reference](https://github.com/sverweij/dependency-cruiser/blob/feature/detect-orphans/doc/rules-reference.md#orphans))
- make sure to pass folders (or globs) to the command line - an individual starter file (like `src/index.ts` will typically not get you any orphans.

For more details check the [reference for orphans](https://github.com/sverweij/dependency-cruiser/blob/feature/detect-orphans/doc/rules-reference.md#orphans).

I'll be polishing & performance tweaking (if necessary) a bit before releasing it as `latest` on npm.

**Comment by sverweij** [comment]
@adamclerk as a heads-up: I've published version 4 of dependency-cruiser to npm about 2 hours ago. It includes orphan-detection.

**Comment by adamclerk** [comment]
Thanks so much Sander. This is awesome.
