### ISSUE TITLE
Support globs

### ISSUE THREAD

**Issue by kyranjamie** [sverweij/dependency-cruiser#472]
### Context

The docs [describe why regular expressions are preferred over globs](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/rules-reference.md#path-specials). Glob-only pattern matching would certainly be a limitation compared to what can be expressed with regexes.

### Desired outcome

Nonetheless, globs are suitable in many uses cases and, for most, way easier to reliably comprehend and write than regular expressions.

I wonder if there's a world in which depcruiser could support both.

**Comment by sverweij** [comment]
Hi @kyranjamie thanks for this question! I do understand that using globs might look enticing.

Internally dependency-cruiser uses regular expressions. That means that to use globs, they'll have to be converted to regular expressions first. Libraries can do that for us e.g. I've found [picomatch](https://github.com/micromatch/picomatch#toregex) and [micromatch](https://github.com/micromatch/micromatch#makeRe). In theory you should be able to use that inside a .dependency-cruiser.js; just require it, and use the output of the conversion in the spot dependency-cruiser expects a regular-expression-as-a-string. E.g. using micromatch (note: _untested_):

```javascript
const { makeRe } = require("micromatch");

function toRe(pGlob) {
  const lMicromatchOptions = {
    contains: true,
    // ...
  }
  return makeRe(pGlob, lMicromatchOptions).toString();
}

/** @type {import('dependency-cruiser').IConfiguration} */
module.exports = {
  forbidden: [
    {
      name: "not-to-dev-dep",
      severity: "error",
      from: {
        // path: "^src",
        path: toRe("src/**/*"),
      },
      to: {
        dependencyTypes: ["npm-dev"],
      },
    },
  ],
  options: {
    doNotFollow: {
      path: "node_modules",
    },
    enhancedResolveOptions: {
      exportsFields: ["exports"],
      conditionNames: ["import", "require", "node", "default"],
    },
  },
};
```

HTH

**Comment by kyranjamie** [comment]
Thanks @sverweij—

I attempted a solution like yours using [globrex](https://github.com/terkelg/globrex) without much luck; it couldn't handle globs like `src/{one,two}/**`.  
The libraries you've suggested look more promising. Will try these out as well 👍🏼
