### ISSUE TITLE
dependency cruiser fails to run if tsconfig is extended from a package

### ISSUE THREAD

**Issue by utsavkapoor** [sverweij/dependency-cruiser#477]
If you extend your tsconfig.json with a package like `@companyName/packageName/src/baseConfig.json` dependency cruiser fails while typescript compilation passes. I also found out that if I use relative paths in my tsconfig, dependency cruiser works fine.

Attaching my tsconfig.json and dependency cruiser options:

tsconfig
`"extends": "@companyName/packageName/src/baseConfig.json",
    "compilerOptions": {
        "baseUrl": ".",
        "rootDir": "./",
        "outDir": "lib"
    },`

dependency-cruiser config
`{
        doNotFollow: {
            path: 'node_modules',
            dependencyTypes: [
                'npm',
                'npm-dev',
                'npm-optional',
                'npm-peer',
                'npm-bundled',
                'npm-no-pkg',
            ],
        },
        tsPreCompilationDeps: false,
        tsConfig: {
            fileName: './tsconfig.json',
        },
        reporterOptions: {
            dot: {
                collapsePattern: 'node_modules/[^/]+',
            },
            archi: {
                collapsePattern:
                    '^(node_modules|packages|src|lib|app|bin|test(s?)|spec(s?))/[^/]+',
            },
        },
    },`

### Expected Behavior

dependency cruiser should run with the above configurations.

### Current Behavior

dependency cruiser throws the following error
> depcruise --validate .dependency-cruiser.js src

ERROR: error TS6053: File '@companyName/packageName/src/baseConfig.json' not found.

- Version used: 9.17.0
- Node version: v14.17.1
- Operating System and version: OSX
- Link to your project:

**Comment by sverweij** [comment]
hi @utsavkapoor thanks for raising this issue. I've tried to reproduce it (see [dependency-cruiser-repro-repo/477](https://github.com/sverweij/dependency-cruiser-repro-repo/tree/main/477)), but wasn't able to - it seems to work as expected. 

Do you run the command (`depcruise --validate .dependency-cruiser.js src`) indeed directly from the command line? If that's the case it most likely runs a globally installed instance of dependency-cruiser. That instance will know about globally installed packages - including, but not limited to, typescript and `@companyName/packageName`. It will not know about locally installed packages, though.

Easiest way to fix that:
- ensure dependency-cruiser is installed in the same folder as you're running it from
- Use one of these ways to ensure that local instance is used:
  - from the command line use `npx depcruise --validate 
  - add a script in the `scripts` section of your  package.json (e.g. `"check-dependencies": "depcruise --validate .dependency-cruiser.js src"`) and run that with npm (e.g. `npm run check-dependencies`)

HTH!

> The reproduction repo uses version 9.17.0, as per the description in the issue. However,  use of the latest version (^10.0.6) is encouraged. The only breaking change in versions >=10 is dropping support for ancient node versions, and the version you use is decently modern & 100% compatible.

**Comment by utsavkapoor** [comment]
Hi @sverweij - We do not run the command directly from the command line. We have script in package.json which runs it. Sorry for not including that. We run the command like you have mentioned (script in package.json and use npm to run it). 
Let me try to reproduce this in your repo and come back
