### ISSUE TITLE
Investigate: potential regression with path resolution/ typescript config parsing on yarn 3

### ISSUE THREAD

**Issue by sverweij** [sverweij/dependency-cruiser#480]
### Summary

See https://twitter.com/julienfouilhe/status/1420051821155033091?s=20

Related issue on yarn/ berry: https://github.com/yarnpkg/berry/issues/3198

### Environment

yarn 3.0.0

- Version used: 10.0.7
- Node version: 16.1.0
- Operating System and version: POSIX compliant
- Link to your project: https://github.com/sverweij/dependency-cruiser-repro-repo/tree/main/480

**Comment by sverweij** [comment]
@julienfouilhe as discussed earlier on twitter:
- under yarn 3 relative paths seem to work differently (not sure if it's intended) from node and earlier versions of yarn
- for now fixed with the workaround in the linked PR
- Released on npm as `dependency-cruiser@10.0.8-beta-1` (which is now also the version the [repro repo uses](https://github.com/sverweij/dependency-cruiser-repro-repo/tree/main/480)
- This will later land in v10.1.0 - but I'll need a reliable way to automatically non-regression test with yarn 3 first.

The repro repo also contains a minimal script to prove relative paths work differently on yarn 3 (in there run `yarn fs`).

**Comment by julienfouilhe** [comment]
@sverweij Thanks a lot! I can confirm `dependency-cruiser@10.0.8-beta-1` fixes the problem in our codebase.

**Comment by sverweij** [comment]
(The fix for this issue is now also part of the regular dependency-cruiser release - as of version 10.1.0, which was just published to npmjs)
