### ISSUE TITLE
Issue: Inconsistency with 2 types of expressing directories on CLI args

### ISSUE THREAD

**Issue by binary64** [sverweij/dependency-cruiser#495]
```
User@DESKTOP-QRQIHPO MINGW64 /c/p/monorepo (dependency-cruiser)
$ yarn depcruise --config .dependency-cruiser.js "{libs,apps}" --ignore-known
yarn run v1.22.10
$ C:\p\monorepo\node_modules\.bin\depcruise --config .dependency-cruiser.js {libs,apps} --ignore-known

√ no dependency violations found (6553 modules, 13357 dependencies cruised)

Done in 121.40s.

User@DESKTOP-QRQIHPO MINGW64 /c/p/monorepo (dependency-cruiser)
$ yarn depcruise --config .dependency-cruiser.js libs apps --ignore-known
yarn run v1.22.10
$ C:\p\monorepo\node_modules\.bin\depcruise --config .dependency-cruiser.js libs apps --ignore-known

√ no dependency violations found (6143 modules, 13357 dependencies cruised)

Done in 117.00s.
```

### Expected Behavior

Both should show the same number of modules (`6143 modules`)

### Current Behavior

They are different

### Possible Solution

Provide examples of multiple directories on README. Or how about scan `.` by default - but ignoring the entries in .gitignore by default.

### Context

This is inside an Nx.dev repo

### Your Environment

- Version used: 10.3.0-beta-4
- Node version: 16
- Operating System and version: Windows

**Comment by sverweij** [comment]
hi @binary64 thanks for raising this. It's a bit puzzling indeed. Both arguments go through the same processing (with [glob](https://github.com/isaacs/node-glob)). I can't reproduce the in the repos I have access to - could you provide a minimal reproduction example?
