### ISSUE TITLE
Issue: Out of heap when using --do-not-follow

### ISSUE THREAD

**Issue by binary64** [sverweij/dependency-cruiser#496]
```
$ C:\p\monorepo\node_modules\.bin\depcruise --config .dependency-cruiser.js {libs,apps} --ignore-known --do-not-follow index.ts

<--- Last few GCs --->

[28428:000001C751909050]   394658 ms: Scavenge (reduce) 4064.7 (4142.8) -> 4064.1 (4143.1) MB, 3.9 / 0.0 ms  (average mu = 0.083, current mu = 0.002) allocation failure
[28428:000001C751909050]   399808 ms: Mark-sweep (reduce) 4064.9 (4143.1) -> 4063.8 (4143.1) MB, 5144.2 / 0.0 ms  (average mu = 0.097, current mu = 0.110) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF746A7B9CF v8::internal::CodeObjectRegistry::~CodeObjectRegistry+112159
 2: 00007FF746A0CA26 v8::internal::MicrotaskQueue::GetMicrotasksScopeDepth+65430
 3: 00007FF746A0D90D node::OnFatalError+301
 4: 00007FF7473A1BAE v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF7473883AD v8::SharedArrayBuffer::Externalize+781
 6: 00007FF747210D3C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1452
 7: 00007FF74721D5C4 v8::internal::Heap::PublishPendingAllocations+1092
 8: 00007FF74721A75D v8::internal::Heap::PageFlagsAreConsistent+2877
 9: 00007FF74720DAA5 v8::internal::Heap::CollectGarbage+1909
10: 00007FF74720BC25 v8::internal::Heap::AllocateExternalBackingStore+1653
11: 00007FF74722E701 v8::internal::Factory::NewFillerObject+209
12: 00007FF746F3E1BA v8::internal::DateCache::Weekday+1386
13: 00007FF747428B91 v8::internal::SetupIsolateDelegate::SetupHeap+460817
14: 000001C7545694AB
error Command failed with exit code 134.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Expected Behavior

When I remove the `--do-not-follow index.ts` it works perfectly.

### Current Behavior

Tried it a few times, heap crash every time.

### Possible Solution

Not sure why `v8::internal::DateCache::Weekday` is present in the nodejs stack trace every time.

### Context

I had some circular-dep warnings for my index.ts, which is a barrel file (contains only export * from's). I was trying to exclude it. Probably not what I want, but still we probably shouldn't use so much memory.

### Your Environment

- Version used: 10.3.0-beta-4
- Node version: 16
- Operating System and version: Windows

**Comment by sverweij** [comment]
hi @binary64 when you use  `--do-not-follow index.ts` it won't follow dependencies discovered through index.ts, but it will follow all other dependencies. Including all your node_modules. The --do-not-follow command line switch overrides the `doNotFollow` option in .dependency-cruiser.js, which likely has `node_modules` as a pattern to not follow. Doing this in a large monorepo with thousands of external npm packages will at some point exhaust resources.
