### ISSUE TITLE
Issue: Progress bar is not very pretty, or smooth

### ISSUE THREAD

**Issue by binary64** [sverweij/dependency-cruiser#497]
Hi, I wasn't sure this is a bug or feature. But with `--progress`, it looks like this:-

![image](https://user-images.githubusercontent.com/1680627/132977581-20a72b15-c67a-4d37-9a07-dc5475bc2a88.png)

Problem 1: It jumps straight to 63% from the start, then 120 seconds later it jumps to 100%.
Problem 2: It looks like 10 very short progress bars, not 1

### Expected Behavior

A silky smooth progress bar that dispenses coffee while you wait

### Current Behavior

It's like Windows 95 progress "99% done" on steroids.

### Possible Solution

https://github.com/sindresorhus/ora

### Context

I would prefer a `--no-progress` instead.

**Comment by sverweij** [comment]
Hi @binary64 --progress currently advances the progress bar at discrete steps in the process (see below - it's also the output of `--progress performance-feedback`); primarily to get a quick insight in where dependency-cruiser spends its time and secondarily to indicate it is doing something. And indeed - reading files takes the most time. 

If you don't like it you can always leave the --progress switch from the command line (by default progress is off ) or pass `--progress none` if you need to override the progress setting in the configuration file.

On operating systems like linux and macOS it looks a bit better than on what you show above: 

https://user-images.githubusercontent.com/4822597/132979841-47fb803a-c861-400d-a688-8a6ec3ee7e84.mp4

Are you on mswindows?

```
  elapsed heapTotal  heapUsed after step...
    695ms      59Mb      48Mb start of node process
      8ms      59Mb      49Mb parsing options
    180ms      79Mb      55Mb parsing rule set
      0ms      79Mb      55Mb making sense of files and directories
      0ms      79Mb      55Mb determining how to resolve
      0ms      79Mb      55Mb reading files
     23ms      79Mb      57Mb reading files: gathering initial sources
    786ms     105Mb      83Mb reading files: visiting dependencies
      0ms     105Mb      83Mb analyzing
     16ms     105Mb      87Mb analyzing: cycles
     19ms     108Mb      77Mb analyzing: dependents
      1ms     108Mb      77Mb analyzing: orphans
    223ms     110Mb      81Mb analyzing: reachables
      0ms     110Mb      81Mb analyzing: add focus (if any)
     63ms     110Mb      79Mb analyzing: validations
      4ms     110Mb      79Mb analyzing: comparing against known errors
      3ms     110Mb      80Mb reporting
      1ms     110Mb      80Mb really done (2024ms)
```
