### ISSUE TITLE
Not a bug or a feature: how do I specify modules that dependent only on specific package?

### ISSUE THREAD

**Issue by plainview1** [sverweij/dependency-cruiser#501]
I'm using depcruise to to find all modules, that depend on specific package - Is there a cli option for this? I tried all filtering cli commands (--include-only and --focus) with no effect.

Ideally I need all (*.ts) imports path's that require some instance from specific package and the dependencies of that instance as well - is it possible to do it?

### Environment

- Version used: latest
- Node version: 12.0.0
- Operating System and version: osx
- Link to your project:

**Comment by yuanyazhen** [comment]
Hi, is this what you want? the blow command will return all modules in `src` depend on `src/wired-lib`.

```depcruise src --include-only "^src" --focus "^src/wired-lib"  -T text```

here's the output 
<img src="https://user-images.githubusercontent.com/13688619/134444729-86cb9db9-556c-49ac-bc2e-583982f5ec5a.png" width="360" />
