### ISSUE TITLE
Not a bug or a feature: Is it possible to ignore circular dependency on "intermediate" files ?

### ISSUE THREAD

**Issue by epaillous** [sverweij/dependency-cruiser#505]
### Summary

I am using circular dependencies rule to remove circular dependencies in my project. My actual rule is : 
```
{
  name: 'no-circular',
  comment:
    `This dependency is part of a circular relationship. 
    You might want to revise your solution (i.e. use dependency inversion,
     make sure the modules have a single responsibility) `,
  severity: 'error',
  from: {},
  to: {
    circular: true,
  },
}
```

In some folders of my project (such as `ui`, `hooks`, or `tables`), I have some "intermediate `index.ts` files" that reexport components (to be able to import the component directly from the folder, such as `import {XXX} from 'ui'`). That cause a lot of circular dependencies because dependency-cruiser will trigger this kind of cycle : 
```
error no-circular: app/javascript/ui/Switch.tsx → 
      app/javascript/hooks/index.tsx →
      app/javascript/hooks/useSidePanelFooter.ts →
      app/javascript/tables/index.tsx →
      app/javascript/tables/Table.tsx →
      app/javascript/tables/Loader.tsx →
      app/javascript/ui/index.tsx →
      app/javascript/ui/Switch.tsx
```
I would like to have a way to "ignore" these circles once dependency cruiser meets either `hooks/index.tsx`, `ui/index.tsx` or `tables/index.tsx `
I tried to modify my rule such as : 
```
const KNOWN_CIRCULAR_PATH = [
  '^(app/javascript/tables/index.ts)',
  '^(app/javascript/ui/index.tsx)',
  '^(app/javascript/hooks/index.tsx)',
]

...


{
  name: 'no-circular',
  comment:
    `This dependency is part of a circular relationship. 
    You might want to revise your solution (i.e. use dependency inversion,
     make sure the modules have a single responsibility) `,
  severity: 'error',
  from: { pathNot: KNOWN_CIRCULAR_PATH},
  to: {
    circular: true,
  },
}
```
But that is not working, since `pathNot` will only prevent files to be check for a potential circular dependency, but will not prevent dependency cruiser to ignore circular dependency if it meets files matching `pathNot`.

Is their a way to achieve this ?

I also tried to set `tsPreCompilationDeps` to `false` and that is my workaround for now but I could miss some typescript files contains an actual strong circular dependency that I do not want.

**Comment by sverweij** [comment]
Hi  @epaillous this is not (yet) possible. It'll probably not be hard to implement, though and it looks useful (not only for this use case) - so I'll put it on the backlog. When it's implemented rules could look like this (check:  would this work for you?).

```javascript
// log an error for all circular dependencies except when they are via one of the barrels
{
  name: 'no-circular',
  severity:  'error',
  from: {
  },
  to: {
    circular: true,
    viaNot: [
      '^(app/javascript/tables/index.ts)',
      '^(app/javascript/ui/index.tsx)',
    ]
  }
},

// for circular dependencies that pass through one of the barrels generate a warning
{
  name: 'no-circular (exception for known barrels)',
  severity: 'warn',
  from: {
  },
  to: {
    circular: true,
    via: [
      '^(app/javascript/tables/index.ts)',
      '^(app/javascript/ui/index.tsx)',
    ]
  }
}
```

In the mean time - could the `--ignore-known` command line option be a (temporary) workaround? With this it's possible to ignore individual violations of existing rules:
1. save all existing violations to a file with [`depcruise-baseline`](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/cli.md#depcruise-baseline)
2. edit that file so it only contains the violations you want to ignore
3. run dependency-cruiser with [`--ignore-known`](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/cli.md#--ignore-known-ignore-known-violations)

**Comment by sverweij** [comment]
hi @epaillous - you can try this feature now in `dependency-cruiser@10.4.0-beta-3` which adds `via` and `viaNot` attributes which you can use in the `to` part of rules that check for cyclic dependencies. 

Feedback welcome!
