### ISSUE TITLE
Issue: add `ignoreKnown` option to optionsUsed in the output model

### ISSUE THREAD

**Issue by sverweij** [sverweij/dependency-cruiser#508]
### Expected Behavior

When running dependency-cruiser with the --ignore-known command line option (or passing known violations with the ignoreKnown option in the API), the output model should include an `ignoreKnown` key in the `optionsUsed` section 

### Current Behavior

It doesn't - even though it's already part of the json schema (see [options-used.mjs](https://github.com/sverweij/dependency-cruiser/blob/develop/tools/schema/options-used.mjs#L19) and the type it references in in [options.mjs](https://github.com/sverweij/dependency-cruiser/blob/develop/tools/schema/options.mjs#L54)).

### How to reproduce

You can test this even with a small setup without any source files:
- create a file called `.dependency-cruiser-known-violations.json` with oneviolation in it e.g.
```json
[
  {
    "from": "foo/bar/baz.js",
    "to": "aap/noot/mies.js",
    "rule": {
      "severity": "error",
      "name": "no-yadda"
    }   
  }
]
```
- create an empty folder (e.g. `src`)
- run dependency-cruiser against it with the `--ignore-known` option and json as output type:
```
depcruise src --output-type json --ignore-known 
```

### Possible Solution

- Add `ignoreKnown` to the SHAREABLE_OPTIONS array in [src/enrich/summarize/summarize-options.js](https://github.com/sverweij/dependency-cruiser/blob/develop/src/enrich/summarize/summarize-options.js#L4)
- Add a unit test to [test/enrich/summarize.spec.mjs](https://github.com/sverweij/dependency-cruiser/blob/develop/test/enrich/summarize.spec.mjs) that proves it works. E.g so that ...

```javascript
const KNOWN_VIOLATIONS = [
  {
    from: "foo/bar/baz.js",
    to: "aap/noot/mies.js",
    rule: {
      severity: "error",
      name: "no-yadda"
    }   
  },  
];

summarize([], { knownViolations: KNOWN_VIOLATIONS } }, []);
```

... would yield something like this:

```javascript
    {
      error: 0,
      info: 0,
      ignore: 0,
      optionsUsed: {
        args: "",
        knownViolations: [ // _not_ ignoreKnown, as was stated in a previous version of this issue
          {
            from: "foo/bar/baz.js",
            to: "aap/noot/mies.js",
            rule: {
              severity: "error",
              name: "no-yadda"
            }   
          },  
        ],
      },
      totalCruised: 0,
      totalDependenciesCruised: 0,
      violations: [],
      warn: 0,
    }
```

### Context

The idea of dependency-cruiser's output model is that it contains all information to reproduce the output - both because they're potentially useful to reporters and because it is valuable when hunting down bugs. Ignore-known is an important piece of information in that puzzle.

**Comment by radiantly** [comment]
This is quite the detailed issue! It looks interesting, could I take a go at it?

**Comment by radiantly** [comment]
Hi, quick question! Do I output the following json:

```
ignoreKnown: true,
knownViolations: [ .. array of violations .. ]
```
(This is what the `pOptions` structure that's received by `summarize-options.js` looks like)

or 
```
ignoreKnown: [ .. array of violations .. ]
```

The former seems more portable if we were to include the list of known violations in the future, but not ignore them. (I suppose there's no use case for that though?)
