### ISSUE TITLE
Can I dependency-cruiser type

### ISSUE THREAD

**Issue by hasban121138** [sverweij/dependency-cruiser#512]
`dependency-cruiser: 10.1.0`

It like this
```tsx
import { myType } from 'myType'
class MyClass {
 func ():myType {}
}
```
If I want to get it   . What should I do ?
Thanks!

**Comment by sverweij** [comment]
Hi @hasban121138 if you want to see dependencies between modules and modules that are only types, you'll have to instruct dependency-cruiser to not ignore dependencies that only exist before compilation to javascript. You can do this with the command line switch `--ts-pre-compilation-deps`(https://github.com/sverweij/dependency-cruiser/blob/develop/doc/cli.md#--ts-pre-compilation-deps-typescript-only)/ the option [tsPreCompilationDeps](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/options-reference.md#tsprecompilationdeps).

Be sure to check out the [FAQ](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/faq.md#q-some-typescript-dependencies-id-expect-dont-show-up-what-gives) entry on this as well.
