### ISSUE TITLE
Not a bug or a feature: Build dependants graph

### ISSUE THREAD

**Issue by ikhalikov** [sverweij/dependency-cruiser#514]
### Summary

This tool works great for building dependencies graph for a whole project. But I was curious if I can use it to get (deep) graph of all dependants. Let's say, I have module `A` which is being used in modules `B`, `C` and `D` - is there a way to build a graph containing only them? I tried to use `--focus` option, but it seems to show only direct dependants, w/o transient links with other modules.

The only option I see at this moment is to use `--focus` option in a loop/recursive to get the complete tree of `A` dependants

**Comment by sverweij** [comment]
hi @ikhalikov dependency-cruiser does have an algorithm on board to get all transitive dependants of a module. It's what is behind the [`reachable`](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/rules-reference.md#reachable---detecting-dead-wood-and-transient-dependencies) restriction, so you can use it to set up rules (see below for an example). With this you can mimic the desired behaviour.

If you want to use dependency-cruiser to explore a code base from the command line or you want to _only_ show/ cruise modules that can reach a certain module, this might not be the most usable approach, though.

Would you only be interested in the (transitive) dependents (e.g. with a `--reaches` cli option) or also of the (transitive) dependencies of the module in question (so more like a `--focus-deep` cli option)?


### example

E.g. to find/ flag all modules that reach ('are transitive dependents of') `src/report/index.js` a rule like this will show them

```javascript
{
  "forbidden": [
    {
      "name": "reaches-report-index",
      "severity": "info",
      "from": {},
      "to": {
        "path": "src/report/index\\.js",
        "reachable": true
      }
    }
  ],
  // ... bunch of options
}
```

With the standard reporter (`err`) they will show up like this ...

```
  info reaches-report-index: src/main/rule-set/validate.js → src/report/index.js
      src/main/rule-set/validate.js →
      src/main/options/validate.js →
      src/report/index.js
  info reaches-report-index: src/main/report-wrap.js → src/report/index.js
      src/main/report-wrap.js →
      src/report/index.js
  info reaches-report-index: src/main/options/validate.js → src/report/index.js
      src/main/options/validate.js →
      src/report/index.js
  info reaches-report-index: src/main/index.js → src/report/index.js
      src/main/index.js →
      src/main/options/validate.js →
      src/report/index.js
  info reaches-report-index: src/cli/index.js → src/report/index.js
      src/cli/index.js →
      src/main/index.js →
      src/main/options/validate.js →
      src/report/index.js
  info reaches-report-index: src/cli/format.js → src/report/index.js
      src/cli/format.js →
      src/main/index.js →
      src/main/options/validate.js →
      src/report/index.js
  info reaches-report-index: src/cli/format-meta-info.js → src/report/index.js
      src/cli/format-meta-info.js →
      src/main/index.js →
      src/main/options/validate.js →
      src/report/index.js
```

... and you can make them show up in the dot graph as well, like so (the fuchsia coloured nodes):

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/4822597/137601840-fda68ca5-bc90-48df-80d5-2a08208dd1c0.png">
