### ISSUE TITLE
Feature request: Exclude dependencyTypes option

### ISSUE THREAD

**Issue by rklos** [sverweij/dependency-cruiser#516]
There was such a issue some time ago (https://github.com/sverweij/dependency-cruiser/issues/490), but at that moment there was no option for identify `type-only` import types. Now, we can make some rules for types that are `type-only`. But it will be nice (relating that issue above) to add option for excluding dependency types.

### Context
A few days ago, new dependency type was added to dependency cruiser - `type-only`. I find very usefull to setup some import restriction except type imports.

For example:
I have a TypeScript module, which is injected to class from outside. I want to prevent developer from reimporting this module, but I want to allow import of type definitions from it.

### Expected Behavior

Something like this:
```
forbidden: [
    {
      name: 'not-to-modules',
      severity: 'error',
      from: {},
      to: {
        path: [
          '^modules',
        ],
        dependencyTypesNot: [ 'type-only' ],
      },
    },
  ]
```

In this case:
```
import Foo from '~/modules/foo'; // forbidden
import type Foo from '~/modules/foo'; // allowed
```

**Comment by sverweij** [comment]
hi @rklos it makes sense to have this - if only from a consistency perspective. I think it would also be possible to use [`allowed`](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/rules-reference.md#allowed) rules to get what you want, but I've found there's a slight learning curve to them.

**Comment by rklos** [comment]
I tried to use `allowed`, but (maybe I did something wrong) it doesn't work. None of `allowed` rules overrides `forbidden` rules. Perhaps it is worth adding an example to the documentation on how to get this effect in different ways

**Comment by sverweij** [comment]
hi @rklos dependency-cruiser@10.5.0 (published this evening) has the dependencyTypesNot attribute. Feedback welcome!
