### ISSUE TITLE
Feature request: Rules in TypeScript

### ISSUE THREAD

**Issue by TranquilMarmot** [sverweij/dependency-cruiser#522]
### Context

This project has some really nice types in https://github.com/sverweij/dependency-cruiser/tree/develop/types but... you can only write your config file in JavaScript right now!

### Expected Behavior

If you pass in i.e. `--config .dependency-cruiser.ts` then `dependency-cruiser` should transpile it to `.js` and then use that as the config.

i.e.

```ts
import { IConfiguration } from 'dependency-cruiser';

const configuration: IConfiguration = {
    // ...
}

export default configuration;
```

### Current Behavior

`dependency-cruiser` will fail with:

```
ERROR: JSON5: invalid character 'i' at 1:1
```

### Possible Solution

Other projects, like [`webpack`](https://webpack.js.org/configuration/configuration-languages/) and [`jest`](https://jestjs.io/docs/configuration), allow adding configuration in TypeScript.

`webpack` relies on using [`ts-node`](https://www.npmjs.com/package/ts-node) to transpile the config file. It would probably be possible to do something similar here.

### Considered alternatives

As laid out in [the faq](https://github.com/sverweij/dependency-cruiser/blob/ed52c71df45adc3b85067b53452cc4a4a2a03315/doc/faq.md#q-can-i-get-code-completion-for-dependency-cruiserjs) you can add the following to the top of the config file:

```js
/** @type {import('dependency-cruiser').IConfiguration} */
```

this "works" but not as well as an actual TypeScript file would.

**Comment by sverweij** [comment]
hi @TranquilMarmot thanks for the suggestion. 

What would be the advantage(s?) of having a config in typescript over javascript-with-typescript-anotations? The latter gives code completion - and if you want/ need to the typescript compiler can validate it for you. Are there additional advantages?

I looked into different additional config formats in the past (apart from typescript: yml, coffeescript). At the time I weighed the effort required to write it, to keep the involved code  secure, performant &  understandable against its practical use and decided against it. What didn't help is that adoption rates for typescript as a config language didn't seem great for webpack or jest. I just re-ran the queries against GitHub (the only large data source I know for this) and it hasn't changed much:

- [webpack.conf.js](https://github.com/search?q=filename%3A%22webpack.conf.js%22&type=Code&ref=advsearch&l=&l=): 267258 (99.97%)
- [webpack.conf.ts](https://github.com/search?q=filename%3A%22webpack.conf.ts%22&type=Code&ref=advsearch&l=&l=): 84 (0.03%)
- [wepback.conf.coffee](https://github.com/search?q=filename%3A%22webpack.conf.coffee%22&type=Code&ref=advsearch&l=&l=): 4 (0.00%)

For jest the adoption rate seems a little better: 
- [jest.config.js](https://github.com/search?q=filename%3A%22jest.config.js%22&type=Code): 518122 (94.70%)
- [jest.config.ts](https://github.com/search?q=filename%3A%22jest.config.ts%22&type=Code): 15229 (2.78%)
- [jest.config.json](https://github.com/search?q=filename%3A%22jest.config.json%22&type=Code): 13734 (2.51%)


That said if there's a convincing reason to support typescript as a config language beyond code completion/ validation I'm willing to consider it.
