### ISSUE TITLE
Feature request: Dependency Graph Changes for Pull Requests

### ISSUE THREAD

**Issue by alyshahudson** [sverweij/dependency-cruiser#528]
I would really like to use this tool on pull requests to compare the changes made to the dependency graph. Is there a way to do that with this tool as is?

**Comment by sverweij** [comment]
@alyshahudson that should be possible, but it depends a bit on the purpose and/ or your ambition levels in what timeframe. 

=> What'd be your main use of the comparison?

Two possibilities off-the-cuff 

### use the version management system

This is possible with dependency-cruiser as is. In its most simplistic form there's something in place that saves a diagram on each commit (e.g. with husky, lint-staged or even directly in git hooks). You could then pull up the diagram from the branch you integrate into (e.g. `main` or `develop`) and put the one from the PR branch next to it. It depends on the tool you make the pull requests in how to automate this exactly.


Two caveats with this approach: 
- graphviz auto-layouts the graphical output. Sometimes this means only one additional module or dependency will change up the position of a lot of elements. Having two diagrams side-by side might then be less than helpful. 
- Another caveat might be that detailed dependency diagrams can become quite big and visually comparing two big diagrams might not be ideal either.

#### example: side by side of a high level overview graph

I currently make a snapshots of the dependency graphs just before I create a new version ([with the `version` life-cycle trigger in package.json](https://github.com/sverweij/dependency-cruiser/blob/v10.7.0/package.json#L131)). That'd be a little taste of how this could look in a PR:

Side by side:
[![dependency-cruiser high-level overview graph - v8.0.0](https://raw.githubusercontent.com/sverweij/dependency-cruiser/v8.0.0/doc/real-world-samples/dependency-cruiser-archi-graph.svg)][![dependency-cruiser high-level overview graph - v10.4.0](https://raw.githubusercontent.com/sverweij/dependency-cruiser/v10.4.0/doc/real-world-samples/dependency-cruiser-archi-graph.svg)](https://github.com/sverweij/dependency-cruiser/blob/v10.4.0/doc/real-world-samples/dependency-cruiser-archi-graph.svg)

- [source of v8.0.0 here](https://github.com/sverweij/dependency-cruiser/blob/v8.0.0/doc/real-world-samples/dependency-cruiser-archi-graph.svg) in the repo.
- [source of v10.4.0 here](https://github.com/sverweij/dependency-cruiser/blob/v10.4.0/doc/real-world-samples/dependency-cruiser-archi-graph.svg) in the repo

If the goal is to have just an overview of changes, a similar approach with the [text reporter](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/cli.md#text) might get you set; it'll likely be easier to compare (as it can be sorted reliably) - and you can also apply a diff (/`git diff`) on them.


### 'integrated diff'

Where changes are highlighted in the graph itself. This is currently not in dependency-cruiser, but it would make a nice future feature. I don't have a clue how hard it'd be to implement that, though.
