### ISSUE TITLE
Specific nodes location on graph

### ISSUE THREAD

**Issue by Kindest13** [sverweij/dependency-cruiser#533]
Do your library have ability to configure priority of nodes(packages) on graph? So that we can simulate tree representation - big packages can be on top, small(utils) packages could be located lower.

**Comment by sverweij** [comment]
Dependency-cruiser itself does not do graph layout.  It does have _dot_ reporter, though, which produces a graph description that can be layed out with [graphviz](https://graphviz.org/) - typically by feeding it to GraphViz’ _dot_ command line tool. By default the automatic layout algorithm is a tree on its side - root on the left, leaves on the right.

There are some tweaks to influence that, both from the dependency-cruiser configuration and from the _dot_ command line tool. For the latter it’s probably best to reference the GraphViz online documentation (via the link above). For the former - the documentation section on [theming dot output](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/options-reference.md#theme-dot-ddot-and-archi-reporters) should get you started; one of the [examples](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/options-reference.md#theming-examples) makes the default layout go top-down (root on top, leaves at the bottom). 

Likely this will get you close to your need already. There are further possibilities to tweak the layout of dot graphs, but they’re typically a trade-off in how much you want to invest in tweaking. An example of this is the [config](https://github.com/sverweij/dependency-cruiser/blob/develop/tools/schema/.dependency-cruiser.json) used to document dependency-cruiser’s [json schema](https://sverweij.github.io/dependency-cruiser/schema-overview.html).
