### ISSUE TITLE
type issue: `format` function's signature in dependency-cruiser.d.ts is not correct

### ISSUE THREAD

**Issue by hikerpig** [sverweij/dependency-cruiser#551]
### Current Behavior

```ts
export function format(
  pResult: ICruiseResult,
  pOutputType: OutputType // not correctly typed here, should be an object, but typed as a string
): IReporterOutput;
```

The code below acctually works, but it will raise a type error due to the incorrect type file.

![image](https://user-images.githubusercontent.com/2259688/147634571-0fb4862d-94d7-4b7a-a4ef-da93556c8bd5.png)

### Possible Solution

Fix the typing.

### Your Environment

- Version used: 11.2.0

**Comment by sverweij** [comment]
Hi @hikerpig thanks for raising this - that should totally be a composite type of some sort. I'll try to fix it this wee.

**Comment by sverweij** [comment]
@hikerpig dependency-cruiser@11.2.1 (published a few minutes ago) contains the correct signature for the `format` function. Let me know if there's still something missing.

> The OutputType still doesn't give as good code-completion as I'd like (no suggestions for which strings to use).
> This is because it allows 'string' to enable passing reporter plugins - everything staring with the string `"plugin:"` 
> is also valid (`"plugin:my-awesome-reporter"`). I haven't been able to tie that down to a proper/ more strict type
> yet.
