### ISSUE TITLE
Not a bug or a feature: Unable to get depcruise to return Error when there are violations

### ISSUE THREAD

**Issue by jLouzado** [sverweij/dependency-cruiser#553]
### Summary

* I'd like to include dependency-cruiser as a check in my CI so that the build fails if there are violations
* currently the script returns as running successfully even if there are violations, so the CI overall-state is 🟢 

### Context

* Here's a custom rule I added to forbid imports from a JS file to a TS file: [no-unsafe-import](https://github.com/jLouzado/theseus-ts-example/blob/main/.dependency-cruiser.js#L125)
* Here's the script in package.json: [lint:deps](https://github.com/jLouzado/theseus-ts-example/blob/main/package.json#L11)
* Here's the [CI run result](https://github.com/jLouzado/theseus-ts-example/runs/4672174345?check_suite_focus=true) that's returning 🟢 
  * output shown below

```
> yarn depcruise --config .dependency-cruiser.js .

yarn run v1.22.17
$ /home/runner/work/theseus-ts-example/theseus-ts-example/node_modules/.bin/depcruise --config .dependency-cruiser.js .

  warn no-unsafe-import: utils-typescript.ts → utils-javascript.js

✖ 1 dependency violations (0 errors, 1 warnings). 5 modules, 4 dependencies cruised.

Done in 0.82s.
```

### Environment

- Version used:
- Node version: 14.x
- Operating System and version:
- Link to your project: https://github.com/jLouzado/theseus-ts-example

**Comment by sverweij** [comment]
hi @jLouzado dependency-cruiser only considers violations of severity `error` for non-zero exit codes - just like e.g. eslint does. When a rule doesn't contain an explicit severity dependency-cruiser assumes it to be of severity `warning`. You can set the severity of the rule to `error` by adding `severity: "error"` to the custom rule.

**Comment by jLouzado** [comment]
Oh got it thank you so much, feeling a bit dumb now thank you for clarifying. Happy New Year. 😊

**Comment by jLouzado** [comment]
Oh got it thank you so much. Happy New Year. 😊
