### ISSUE TITLE
Can you change the way (shape) modules are shown on graph? 

### ISSUE THREAD

**Issue by mazury** [sverweij/dependency-cruiser#555]
I would like to generate graph for a big codebase. There are lots of files and final ratio of graph's height and width generated with ddot is 1:20, which makes it a bit difficult to read. It would be better if everything was fit inside, let's say a square or some box with bigger dimension ratio. 

Here are the images:
![image](https://user-images.githubusercontent.com/24698150/147947945-2c7e1e44-2398-45cb-a8a8-d9f576acdcaa.png)
![image](https://user-images.githubusercontent.com/24698150/147948039-22c14b27-7cf7-45c4-a26a-92955e28a713.png)

So the question is can we change that? Or it's generated automatically and there you can't affect this behaviour?

**Comment by sverweij** [comment]
Hi @mazury TL;DR - yes, using the possibilities of GraphViz dot, which does the actual rendering.

The graph is indeed generated automatically (by GraphViz dot), but there's quite some tweaking parameters in the `dot` language. E.g. there's [`nodesep`](https://graphviz.org/docs/attrs/nodesep/) and [`ranksep`](https://graphviz.org/docs/attrs/ranksep/) that influence the distance between nodes horizontally and vertically (assuming your graph is rendered top-down.


You pass them as command line parameters to the `dot` program (useful for quick testing) or you can put these values in `.dependency-cruiser.js` in `.options.reporterOptions.ddot.theme.graph`. 

Sample of the first one

```sh
npx depcruise src --output-type ddot --config .dependency-cruiser.js | \
  dot -Tsvg -Gnodesep=0.1 -Granksep=1 > graph.svg
```


There's (a lot, I'm afraid) parameters in GraphViz that are tweak able; I usually start with the [Attributes](https://graphviz.org/doc/info/attrs.html) section in their documentation. Nowadays they also link to an [online editor](http://magjac.com/graphviz-visual-editor/) that enables you to play around with short feedback cycles.

> B.t.w. sorry for taking so long to answer your question!
