### ISSUE TITLE
Feature request: Add windows support

### ISSUE THREAD

**Issue by andvolodko** [sverweij/dependency-cruiser#558]

**Comment by sverweij** [comment]
Hi @andvolodko dependency-cruiser should already work on windows (there's even a [separate CI job](https://github.com/sverweij/dependency-cruiser/actions/workflows/test-workflow-windows-only.yml) ensuring compatibility with the OS's many idiosyncrasies doesn't break). Something particular you're missing? Is there something that doesn't seem to work at the moment?

**Comment by andvolodko** [comment]
I cannot run "dot" command from command line on windows.
On mac it was not easy, but I done it by using 2 commands: 1 for generating .dot file, second from converting dot to svg.
This command:
depcruise --include-only "^src" --output-type dot src | dot -T svg > dependencygraph.svg
from your main page unfortunately not worked for me

**Comment by sverweij** [comment]
hi @andvolodko dependency-cruiser doesn't render graphs by itself. It generates a file in the GraphViz _dot_ format. `dot` is a program from the [GraphViz](https://graphviz.org) suite that takes a file in the _dot_ format and makes it into a nice picture. If the windows machine can't run `dot`, the most likely cause is that GraphViz isn't installed. You can grab it from the GraphViz website [GraphViz download page is here](https://graphviz.gitlab.io/download/) - likely the [stable x64 build for windows](https://www2.graphviz.org/Packages/stable/windows/10/cmake/Release/x64/).

Related/ similar issue: #379

**Comment by andvolodko** [comment]
Thank you @sverweij
