### ISSUE TITLE
Feature request: filtering out exceptions from forbidden rules

### ISSUE THREAD

**Issue by mlewando** [sverweij/dependency-cruiser#559]
### Context

I have some rule in `forbidden` rules, let's say that it's to disallow dependency to dev dependencies (this is simplified version):

```
{
      name: 'not-to-dev-dep',
      severity: 'error',
      from: { path: '^(src)' },
      to: { dependencyTypes: ['npm-dev'] },
}
```
I have some file `a.js` that depends on some dev-dependency `b` that for some reason I need to keep for a while. I need to filter out this violations of my rule.

### Expected Behavior

I'd like to allow only dependency from `a.js` to `b`. No other module can require `b` neither `a.js` can require other dev dependencies.

### Current Behavior

Currently I cen either allow `a.js` to import any dev dependencies (with `pathNot` in `from`) or allot to import `b` in any module (with `pathNot` in `to`). I see no option to allow only dependency `a.js` -> `b`

### Possible Solution

Maybe some additional option like `exceptions` in the rule object?

**Comment by sverweij** [comment]
Hi @mlewando if I understand correctly you're in a situation where you want to temporarily 'quarantine' rule violations, so you can at least prevent new violations. There's two options I currently see for this:

- One way you already explored; use  `pathNot` in both the `from` and `to` parts of rules - and maybe adding a separate rule for the exception, and a complimentary one for all the new violations. As you discovered it can become not only laborious and hard to get water-tight.

- Another way is to use a file with known violations and pass that with and pass [`--ignore-known`](https://github.com/sverweij/dependency-cruiser/blob/v11.2.1/doc/cli.md#--ignore-known-ignore-known-violations) to the dependency-cruiser cli when you want to ignore them. dependency-cruiser uses this feature on its self scan as well:
  - ignored violations in [.dependency-cruiser-known-violations.json](https://github.com/sverweij/dependency-cruiser/blob/v11.2.1/.dependency-cruiser-known-violations.json)
  - default depcruise command with --ignore-known in [package.json#L75](https://github.com/sverweij/dependency-cruiser/blob/v11.2.1/package.json#L75)

I'd recommend to at least generate the first iteration of this known violations file with the  like the one generated with [depcruise-baseline](https://github.com/sverweij/dependency-cruiser/blob/v11.2.1/doc/cli.md#depcruise-baseline)  command, which will write _all_ current violations to a .dependency-cruiser-known-violations.json. You can either edit that file to only include what you actually want to ignore - or use it as is and when violations get fixed re-generate the file with the same command.

The feature is reasonably new. It's decently tested, but the documentation might feel a bit terse. Improvement suggestions on both that (and the feature itself) are welcome.

Related: #493
