### ISSUE TITLE
Feature request: Customizable HTML

### ISSUE THREAD

**Issue by ghmcadams** [sverweij/dependency-cruiser#562]
I am really enjoying this tool.  Not only does it provide the boundary enforcement I have been looking for, but I love that it creates the visual diagram to go with it.  The dynamic line and node colors and customizable node shapes makes it really easy to see issues at a glance.  2 Things I have struggled with in the html output of dot diagrams are:
- Large diagrams are tough to navigate (no zoom/pan)
- No options for custom functionality (custom highlight color, click to source/destination, etc.)

### Context

We will be using the visual diagram as a tool to identify and visualize problems.  The more we can customize the interactions for our use case, the faster we can resolve issues.

### Expected Behavior

I would like to have more control over the html and css output.

### Current Behavior

A single HTML template is used and cannot be modified.

### Possible Solution

I think to start with, allowing a specified base html file would suffice.  Perhaps down the road, a config driven html could work as well.

**Comment by sverweij** [comment]
Hi @ghmcadams thanks for this suggestion.

At this moment the (graphical) html output is not directly tweakable. However, the approach to come from the svg GraphViz dot generates to the html is embarassingly simple; the depcruise-wrap-stream-in-html script  concatenates a [header snippet](https://github.com/sverweij/dependency-cruiser/blob/v11.3.0/src/cli/tools/svg-in-html-snippets/header.snippet.html), the svg, a [script snippet][snippet](https://github.com/sverweij/dependency-cruiser/blob/develop/src/cli/tools/svg-in-html-snippets/script.snippet.js) and a [footer](https://github.com/sverweij/dependency-cruiser/blob/v11.3.0/src/cli/tools/svg-in-html-snippets/footer.snippet.html) together.

Before the introduction of this command I piped the dot output through a shell invocation (`... dot -T svg | cat header.snippet -  script.snippet footer.snippet > result.html`), which works, but is a bit much when all you want is some neat html without much hassle. It's very flexible, though and might help in a pinch if you need to iterate quickly, or if you need some customisation that isn't there out of the box (your use case if I see correctly).


- It would be possible to expand the depcruise-wrap-stream-in-html script with parameters to indicate custom locations of header, script & footer snippets. I'm not quite sure that'd be a widely used feature yet, though (especially when the default script/ css get better so they include e.g. better navigability).
- Additional functionality in the html that wraps around the svg dot generates is welcome, so if you have contributions towards expanding the current script (while keeping it standalone) consider me interested - I'm sure others would love to see something towards that as well (especially pan and zoom and smarter navigation options (i.e. a short cut to navigate to the other end of a dependency - if I understand that suggestion correctly).

**Comment by ghmcadams** [comment]
Thanks for the reply.  The work-around you mentioned solves my immediate problem.  Depending on time I have available, I may be able to contribute something when I make the html adjustments.
