### ISSUE TITLE
Not getting the full svelte imports

### ISSUE THREAD

**Issue by j2l** [sverweij/dependency-cruiser#563]
I `depcruise -T dot src | dot -T svg > dependencygraph.svg` any svelte project on github, for instance https://github.com/fouita/tailwind-editor and got a limited graph:
![dependencygraph](https://user-images.githubusercontent.com/65325/152124525-04992f2d-bfc4-4e3e-92e0-ab65e7686531.svg)
In this case, missing Editor/ContentEditor.svelte, Toolbar/ svelte files and Icons/, but they are imported:
```
grep -R TriangleDown
src/ToolBar/Spacing.svelte:    import TriangleDown from "../Icons/TriangleDown.svelte";
src/ToolBar/Spacing.svelte:        <TriangleDown />
src/ToolBar/TextAlign.svelte:    import TriangleDown from "../Icons/TriangleDown.svelte";
src/ToolBar/TextAlign.svelte:        <TriangleDown />
```
I red the doc and didn't find how to extend.
So I guess it's a doc bug, a depcruise bug or a user bug :)

### Expected Behavior
Full graph

### Current Behavior
Partial graph

### Steps to Reproduce (for bugs)
1. download a svelte project, ex: https://github.com/fouita/tailwind-editor zip
2. open terminal, depcruise -T dot src | dot -T svg > dependencygraph.svg
3. open svg

### Your Environment
- Version used: 11.3.0
- Node version: v14.18.3
- Operating System and version: Ubuntu 21.10

Thanks for your help!

**Comment by sverweij** [comment]
Hi @j2l I've tried to reproduce the issue with these steps:

- clone the repo
- install dependency-cruiser as a development dependency (`npm i -D dependency-cruiser`)
- initialise dependency-cruiser (`npx depcruise --init` & answer some questions that asks)
- added a few convenience scripts to package.json

> You can also use the cheat code `depcruise --init experimental-scripts` to combine the last two steps and leaving answering questions over to dependency-cruisers's guesstimates on the environment it runs in.

When I then run dependency-cruiser, either separately (`npx depcruise --config --output-type dot | dot -T svg > dependencygraph.svg`) or with one of the convenience scripts (npm run depcruise:graph) it finds & follows .svelte modules as expected:

<img width="815" alt="image" src="https://user-images.githubusercontent.com/4822597/152399723-f47a89f9-89e9-4182-852d-5dbdd4504351.png">

#### What's the difference with the situation in the issue description?

The most likely difference is that when you got the issue you were using a dependency-cruiser instance that didn't have access to the _svelte_ compiler. A hypothesis as to what might have cause that: you used a globally installed version of dependency-cruiser. Typically the svelte compiler isn't installed in that location. A remedy could be to install the svelte compiler globally as well. However, you probably want to install dependency-cruiser locally. There it'll have all the tools you use to build your environment available. They'll be guaranteed to be the right version as well.

Also see
- [The first entry in the FAQ](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/faq.md#q-typescript-coffeescript-livescript-or-vue-single-file-component-sfc-dependencies-dont-show-up-how-can-i-fix-that)
- [--init](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/cli.md#--init)
- the [validate things](https://github.com/sverweij/dependency-cruiser#declare-some-rules) section in the README that might help as a starting point.

Hope this helps!

**Comment by j2l** [comment]
Thank you @sverweij 
I still might do something wrong because I get an error at the end:
![image](https://user-images.githubusercontent.com/65325/152404701-1efdf791-8568-49f4-82f5-c3fa25ef2f6a.png)

**Comment by sverweij** [comment]
hi @j2l oh crap - I made a typo in my example command line and forgot the mandatory argument (the folders to scan; in this case `src`). This should work:

```
npx depcruise src --config --output-type dot | dot -T svg > dependencygraph.svg
```

> the error message you get is from GraphViz dot. Dependency-cruiser just dumped its command line help text, and dot is a hard time parsing that as _dot_ source code

I'll also dump the .dependency-cruiser.js and package.json (with the convenience scripts) on here.

**Comment by j2l** [comment]
I'm tired too :smile: it's late in Europe.
![image](https://user-images.githubusercontent.com/65325/152406964-685e0fea-4b74-4640-b3fa-79ddd8e41350.png)

yeah!

How to remove the no-to-dev-dep links and get kind of the same as yours?

**Comment by sverweij** [comment]
🎉  

- Regarding the lines to node_modules: I added in the  `--include-only "^src"` [cli option](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/cli.md#--include-only-only-include-modules-satisfying-a-pattern) to the convenience script (see package.json snippet in the previous comment. It's also possible to do that in the .dependency-cruiser.js either [just for graphs](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/options-reference.md#filtering-dot-ddot-and-archi-reporters) or [overall](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/options-reference.md#includeonly-only-include-modules-satisfying-a-pattern)
- The straight lines (possibly your next question 😄  ) are a feature in graphviz dot. Either pass -Tsplines=ortho to the `dot` command or configure it in .dependency-cruiser.js like so (the .dependency-cruiser.js you generated already has a section like this:


<details>
<summary>snippet from .dependency-cruiser.js</summary>

```javascript
// ...
      dot: {
        collapsePattern: "node_modules/[^/]+",
        theme: {
          graph: {
            /* use splines: "ortho" for straight lines. Be aware though
              graphviz might take a long time calculating ortho(gonal)
              routings.
           */
            splines: "ortho",
          },
        },
      },
// ...
```


</details>

**Comment by j2l** [comment]
Cool! Thank you @sverweij 
Everything is fine for me, closing.

**Comment by j2l** [comment]
> pass -Tsplines=ortho to the dot command

is not working for me and I didn't find this in graphviz CLI manual
