### ISSUE TITLE
When paths have commas in them they are reported as not-to-unresolvable

### ISSUE THREAD

**Issue by lukesmurray** [sverweij/dependency-cruiser#567]
### Expected Behavior

The path should be reported as resolvable.

### Current Behavior

The path is reported as unresolvabe.

### Possible Solution

Probably a regex issue. Maybe this is unnecessary to fix. It is pretty weird.

### Steps to Reproduce (for bugs)

You can replicate this with a simple import.

`import foo from "./path/to/foo, comma.json`

This is really strange I admit, the actual filename is `foo, comma.json`

Rather than resolving this it will report `not-to-unresolvable` `-> comma.json`.

It seems to think the `comma.json` is a standalone import because it comes after the comma.

### Context

You can honestly close this if it is hard to solve and a total edge case I just wanted to report it in case it is indicative of a larger issue.

### Your Environment

- Version used:
- Node version:
- Operating System and version:
- Link to your project:

**Comment by sverweij** [comment]
Hi @lukesmurray thanks for reporting this! I've been able to reproduce it and found where to fix it ([the regex to unravel esm urls](https://github.com/sverweij/dependency-cruiser/blob/06ec5c8f1e3e4386a9a71e0c8418c3b3909393c7/src/extract/utl/extract-module-attributes.js#L21) is not specific enough)

**Comment by sverweij** [comment]
☝️ fixed (& added an additional unit test) - will be part of the next release.
