### ISSUE TITLE
Add the ability to add a `comment` field in `.dependency-cruiser-known-violations.json`

### ISSUE THREAD

**Issue by btiernay** [sverweij/dependency-cruiser#571]
Often one wants to document why a known violation exists so that the context may be relayed between writer and reader. This is common in other systems such as Dependency Check's [`notes` element](https://jeremylong.github.io/DependencyCheck/general/suppression.html).

### Expected Behavior

Add the ability to add a comment:
```json
  {
    "type": "dependency",
    "from": "from.js",
    "to": "to.js",
    "notes": "Currently there is a bug in `from.js` that we are working to fix. Excluding for now."
    "rule": {
      "severity": "error",
      "name": "not-to-unresolvable"
    }
  },
```

### Current Behavior

There is no field and you cannot comment in JSON 😢 

### Possible Solution

Add a `notes` field to the JSON Schema.

### Considered alternatives

Allow JS files?

**Comment by sverweij** [comment]
hi @btiernay good idea! Shouldn't be too hard to add it to the json schema. 

> B.t.w. the known violations are parsed with [json5](https://json5.org) which is a bit more liberate than json - so it will still work just fine when you add comments.

**Comment by sverweij** [comment]
The PR addressing this issue has been merged and the resulting code will be part of the next release (expected somewhere this weekend).

**Comment by btiernay** [comment]
Awesome, thank you! ❤️
