### ISSUE TITLE
Remove `'^(assert)$'` from `config.js.template.hb`

### ISSUE THREAD

**Issue by btiernay** [sverweij/dependency-cruiser#572]
### Context

After running `depcruise --init` the generated file includes the following stanza:
```js
{
      name: 'no-deprecated-core',
      comment:
        'A module depends on a node core module that has been deprecated. Find an alternative - these are ' +
        "bound to exist - node doesn't deprecate lightly.",
      severity: 'warn',
      from: {},
      to: {
        dependencyTypes: [
          'core'
        ],
        path: [
          '^(v8\/tools\/codemap)$',
          '^(v8\/tools\/consarray)$',
          '^(v8\/tools\/csvparser)$',
          '^(v8\/tools\/logreader)$',
          '^(v8\/tools\/profile_view)$',
          '^(v8\/tools\/profile)$',
          '^(v8\/tools\/SourceMap)$',
          '^(v8\/tools\/splaytree)$',
          '^(v8\/tools\/tickprocessor-driver)$',
          '^(v8\/tools\/tickprocessor)$',
          '^(node-inspect\/lib\/_inspect)$',
          '^(node-inspect\/lib\/internal\/inspect_client)$',
          '^(node-inspect\/lib\/internal\/inspect_repl)$',
          '^(async_hooks)$',
          '^(assert)$',  // <- This
          '^(punycode)$',
          '^(domain)$',
          '^(constants)$',
          '^(sys)$',
          '^(_linklist)$',
          '^(_stream_wrap)$'
        ]
    }
}
```

This results in warnings such as the following:
```
  warn no-deprecated-core: index.js → assert
    A module depends on a node core module that has been deprecated. Find an
    alternative - these are bound to exist - node doesn't deprecate lightly.
```

However, [DEP0089](https://nodejs.org/api/deprecations.html#DEP0089) indicates that since `v12.8.0`, the deprecation of `require('assert')` has been revoked.

### Expected Behavior

No warning should be generated for usage of `assert`

### Current Behavior

See above

### Possible Solution

Remove `'^(assert)$'` from here:
https://github.com/sverweij/dependency-cruiser/blob/a3c187b0187ff09fab19c6b7df4c2bd53d48cf02/src/cli/init-config/config.js.template.hbs#L89

### Considered alternatives

N/A

**Comment by sverweij** [comment]
Hi @btiernay thanks for bringing this up! Fix is validating on the ci (☝️), and will be part of the next release (likely somewhere this weekend).

> on a related note - this now is a manual check, it'd be better if it could be sourced from a central
> spot similar to `module.builtinModules` but then e.g.`module.deprecatedModules` so it's just
> a build away.
>  I've looked for that for a bit on GitHub & npm  but couldn't something suitable, so that'll have 
> to remain a future feature for now...
