### ISSUE TITLE
Question: Need for a server based interactive solution providing different views on the same data

### ISSUE THREAD

**Issue by stemey** [sverweij/dependency-cruiser#576]
### Summary

Our code base is quite large. We need an interactive solution to start from a base view and then drill into different modules/packages to explore the dependencies in our software. Is there already such a solution? If not are you interested in a PR?

### Proposal

A simple express server rendering the svg graphs. The cli arguments are passed as request parameters. An SPA like frontend that can be used to select links and edges to navigate to new diagrams. In this way the user can drill into certain module(s) (setting include--only) or focus on a certain module (setting focus).

**Comment by sverweij** [comment]
hi @stemey an interactive way to go through a code base and only show portions at at time would indeed be useful to a lot of people. Especially when the number of modules rises above a certain threshold any graph representation becomes useless and to make sense of the thing there's additional tools necessary - being able to do this dynamically (it's already possible to generate these things statically) would be very nice indeed.

The client/ server solution makes sense. Not sure this repo is the correct spot for that, but as a separate solution it'd definitely be welcomed.
