### ISSUE TITLE
Question: create-react-app absolute imports stop dependency tree

### ISSUE THREAD

**Issue by ronalson** [sverweij/dependency-cruiser#601]
### Summary

Dependencies scan stops at first level due to create-react-app custom configuration for absolute imports ([cra docs](https://create-react-app.dev/docs/importing-a-component/#absolute-imports)).

### Context

I'm trying to make sense of a large scale react project but I had not luck runnig dependecy-cruiser properly due to a custom configuration of the project.

The project uses **absolute imports** to import [sic] a good chunk of its dependecy. This config is set at: `jsconfig.jsom` and it allows for a "cleaner" import path of components and such.

```javascript
{
  "compilerOptions": {
    "baseUrl": "src"
  },
  "include": ["src"]
}
```

*Problem*

The output I'm getting is very similar to this issue referended in the FAQ [TypeScript parser dependency](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/faq.md#q-it-looks-like-dependency-cruiser-only-detects-the-first-of-level-dependencies---what-is-going-on-typescript) but I'm not sure how to deal with it since CRA has some hidden config files that I cannot tap into.

I've created a demo CRA project that simulates the issue:

https://github.com/ronalson/cra-dep-cruiser-demo

Notice bellow that if I import `Button.js` at `./src/components/OddParent` with an absolute import my output is very different:

- No absolute imports

![regular import](https://raw.githubusercontent.com/ronalson/cra-dep-cruiser-demo/main/depcruise/no-absolute-import.svg)

- With absolute imports

![absolute import](https://raw.githubusercontent.com/ronalson/cra-dep-cruiser-demo/main/depcruise/with-absolute-import.svg)

*running depcurise*

I'm running depcruise like so:

```sh
depcruise -x '^node_modules' --output-type dot ./src | dot -T svg > ./depcruise/with-absolute-import.svg
```

I've also tried to run the `init` cli command but had no luck.

*Request*

Can someone point me to what configuration change should I look into? Does anyone has experience in running depcruise with CRA projects?

### Environment

- Version used: 11.7.1
- Node version: v16.15.0
- Operating System and version: Macos 12.3.1
- Link to your project: https://github.com/ronalson/cra-dep-cruiser-demo

**Comment by sverweij** [comment]
Hi @ronalson the 'absolute imports' work by virtue of the bundler used by CRA taking into account the `jsconfig.json` (or `tsconfig.json` for typescript projects). In the depcruise command above dependency-cruiser isn't told to use the `jsconfig.json` - so it doesn't. You can do that with the [`--ts-config`](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/cli.md#--ts-config-use-a-typescript-configuration-file-project) command line option and the [`tsConfig`](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/options-reference.md#tsconfig-use-a-typescript-configuration-file-project) option in the .dependency-cruiser.js configuration file.

- The easiest is to run `depcruise --init yes`. This will detect the existence of the `jsconfig.json` and put it in `.dependency-cruise.js` for you in the right spot. When running the depcruise command, pass `--config` (or `--config .dependency-cruiser.js` if you want to be explicit) and Bob's your uncle:
```
depcruise src --config .dependency-cruiser.js --output-type dot | dot -T svg > ./depcruise/with-absolute-import.svg
```
- This works in the interactive version of `--init` as well. I can see how the questions might be confusing as you're not using typescript, so I'll see if I can adjust the wording and/ or make something specific for jsconfig.json only setups. You're probably not the only one using CRA this way :-) 
```
? Where do your source files live? src
? Do your test files live in a separate folder? No
? Looks like you're using TypeScript. Use a 'tsconfig.json'? Yes
? Full path to your 'tsconfig.json': jsconfig.json
? Also regard TypeScript dependencies that exist only before compilation? No
```
- I do recommend to use a .dependency-cruiser.js and put options in there, but it's also possible to specify the `jsconfig.json` on the command line 
```
depcruise src --include-only "^src" --ts-config jsconfig.json --output-type dot | dot -T svg -o ./depcruise/with-absolute-import.svg
```
I'll see if I can update the text in the --help command to clarify the --ts-config option can also be used with jsconfig.json (as it's exactly the same file format in the first place).


Result in either case:

<img width="762" alt="image" src="https://user-images.githubusercontent.com/4822597/169642777-7dc3d883-fa7e-4c9c-b49a-ddbb5f5d2f44.png">
