### ISSUE TITLE
Question: Is there a way to set 'constraint' of subgraph?

### ISSUE THREAD

**Issue by czlowiek488** [sverweij/dependency-cruiser#611]
Set constraints for subgraph.
https://stackoverflow.com/questions/7777722/top-down-subgraphs-left-right-inside-subgraphs

But it does work recursively on all subgraphs. I would like to have only 1 layer of subgraph with this attribute.
```
options.reporterOptions.dot.theme.edge.constraint = false
```
![image](https://user-images.githubusercontent.com/34620109/172072235-2945a006-4a62-4e01-b187-6ef8486c2299.png)

Default behaviour works well for smaller apps.
My all apps has structure with 2 main directories with a lot subdirectories, amount of subdirectories grows through development time.
My apps may be 3 times bigger and still has only 2 subdirectories.
As you can see in image below it would unnest arrow tails and make image more compact.
![image](https://user-images.githubusercontent.com/34620109/172070600-8a659320-3467-4be2-9836-d68cc674efc5.png)
I would like to achieve result like this.
![image](https://user-images.githubusercontent.com/34620109/172070636-3bdef534-3fcd-4061-a340-69a66ba48b15.png)

Is there a way to achieve what I would like?

Thanks for any help

**Comment by czlowiek488** [comment]
Now when I think about this if using `constraints` would set to true by default to every odd level of graph it would be trully usuable. 
I belive this approach could be implemented without many changes.

**Comment by sverweij** [comment]
Hi @czlowiek488 thanks for your question. Short answer: yes it's possible - see below for the details. 

=> What is the use case you have in mind for this feature?

It _is_ possible to set the _constraint_ attribute in the `dot` dependency-cruiser generates both overall (`edges` attribute in the `theme` option you can set) and on dependencies matching various criteria. With the proposal from your previous comment to alter by every odd level of the graph something like this will work (verified to work against dependency-cruiser's own code base - see the diagram below (in the first 'details' block) for the result:


```javascript
/** @type {import('dependency-cruiser').IConfiguration} */
module.exports = {
  options: {
    // not essential to the question - edit these to match your target situation
    doNotFollow: "node_modules",
    // how the reporters and derivaters are composed won't add to the bigger
    // picture, so we collapse them
    collapse:
      "node_modules/[^/]+/|^src/report/[^/]+/|^src/enrich/derive/[^/]+/",
    // ensure node native, node_modules etc don't show up in the diagram
    // so it remains legible
    includeOnly: "^(bin|src)",

    // here's the relevant part of the configuration
    reporterOptions: {
      dot: {
        theme: {
          graph: {
            // possible values true (splines), false (direct lines) and
            // "ortho" (orthogonal routing) - which typically looks the best
            // but is limited to being effective in smaller (< 200 node)
            // graphs only
            splines: "ortho",
          },
          edge: {
            // constraint: false makes it so none of the dependencies get constrained.
            // When left in place on its own this will plot all modules in a vertical line
            // on top of each other. In most cases this will hamper readability/
            // usability of the graph. The constraint 'overrides' on alternating
            // levels will alleviate that drawback a bit.
            constraint: false,
          },
          dependencies: [
            // the order of these formatting directives matters. For this use case:
            // most specific to least specific
            {
              // DO have constraint attributes for all dependencies
              // ending on modules 3 levels deep
              criteria: { resolved: "^[^/]+/[^/]+/[^/]+/" },
              attributes: { constraint: true },
            },
            {
              // DON'T have constraint attributes for all dependencies
              // ending on modules 2 levels deep
              criteria: { resolved: "^[^/]+/[^/]+/" },
              attributes: { constraint: false },
            },
            {
              // DO have constraint attributes for all dependencies
              // ending on modules 1 level deep
              criteria: { resolved: "^[^/]+/" },
              attributes: { constraint: true },
            },
          ],
        },
      },
    },
  },
};
```


<details>

![tmp-paste-this-on-github](https://user-images.githubusercontent.com/4822597/173233622-76074285-0eeb-40e7-a021-9cbf8cf26d12.png)

</details>

In comparison - this is how the same graph looks without tweaking the 'constraints':

<details>

![tmp-paste-this-on-github-no-constraints-fs8](https://user-images.githubusercontent.com/4822597/173233737-62b2b885-1a37-4516-944d-c729844b5294.png)


</details>


Hope this helps.
