### ISSUE TITLE
Feature request: (mermaid reporter) add `minify` option

### ISSUE THREAD

**Issue by MH4GF** [sverweij/dependency-cruiser#621]
Propose option to compress output mermaid text.

### Context

The default value for mermaid.js and the limit on GitHub and Notion is that the amount of text rendered by mermaid.js is limited to 50000 characters. 
When outputting with the dependency-cruiser output-type set to mermaid, a slightly larger project could easily break through the limit and mermaid.js would fail to render.

#### Current strategy of mermaid-reporter-plugin 

The current mermaid-reporter-plugin adds indentation appropriately for human readability.
Another problem is that trying to use a file path as a mermaid node may result in an error as a mermaid syntax, even if it is correct as a file name. For this reason, some symbols are replaced or otherwise hashed. 
This should still cover some ground at this point, but it is not perfect yet.

The advantage of readability is that a human can make additions and corrections, but if you only need rendered diagrams and are not interested in the text, is there any possibility that readability is not necessary?

#### Proposed Solution

Propose option to compress text like a [Teaser](https://github.com/terser/terser), For example, add `minify: true` to .dependency-cruiser.js .
Readability is sacrificed, but by compressing to the point where each node retains its unique state, more dependencies can be displayed within mermaid's character limit. As a side effect, file paths no longer need to be hashed.

The following is a description of the expected output. First, here is the current output:

```mermaid
flowchart LR

subgraph test["test"]
  subgraph test_runDepcruise["runDepcruise"]
    subgraph test_runDepcruise_sample["sample"]
      subgraph test_runDepcruise_sample___mocks__["__mocks__"]
        subgraph test_runDepcruise_sample___mocks___test["test"]
          subgraph test_runDepcruise_sample___mocks___test_fixtures["fixtures"]
            subgraph test_runDepcruise_sample___mocks___test_fixtures_cjs["cjs"]
              test_runDepcruise_sample___mocks___test_fixtures_cjs_one_only_one_js["one_only_one.js"]
              test_runDepcruise_sample___mocks___test_fixtures_cjs_one_only_two_js["one_only_two.js"]
              test_runDepcruise_sample___mocks___test_fixtures_cjs_root_one_js["root_one.js"]
              test_runDepcruise_sample___mocks___test_fixtures_cjs_shared_js["shared.js"]
              subgraph test_runDepcruise_sample___mocks___test_fixtures_cjs_sub["sub"]
                test_runDepcruise_sample___mocks___test_fixtures_cjs_sub_dir_js["dir.js"]
                test_runDepcruise_sample___mocks___test_fixtures_cjs_sub_depindir_js["depindir.js"]
              end
              test_runDepcruise_sample___mocks___test_fixtures_cjs_root_two_js["root_two.js"]
              test_runDepcruise_sample___mocks___test_fixtures_cjs_somedata_json["somedata.json"]
              test_runDepcruise_sample___mocks___test_fixtures_cjs_two_only_one_js["two_only_one.js"]
            end
          end
        end
      end
    end
  end
end
test_runDepcruise_sample___mocks___test_fixtures_cjs_root_one_js --> test_runDepcruise_sample___mocks___test_fixtures_cjs_one_only_two_js
test_runDepcruise_sample___mocks___test_fixtures_cjs_root_one_js --> test_runDepcruise_sample___mocks___test_fixtures_cjs_shared_js
test_runDepcruise_sample___mocks___test_fixtures_cjs_root_one_js --> test_runDepcruise_sample___mocks___test_fixtures_cjs_sub_dir_js
test_runDepcruise_sample___mocks___test_fixtures_cjs_sub_dir_js --> test_runDepcruise_sample___mocks___test_fixtures_cjs_sub_depindir_js
test_runDepcruise_sample___mocks___test_fixtures_cjs_root_two_js --> test_runDepcruise_sample___mocks___test_fixtures_cjs_shared_js
test_runDepcruise_sample___mocks___test_fixtures_cjs_root_two_js --> test_runDepcruise_sample___mocks___test_fixtures_cjs_somedata_json
test_runDepcruise_sample___mocks___test_fixtures_cjs_root_two_js --> test_runDepcruise_sample___mocks___test_fixtures_cjs_two_only_one_js
test_runDepcruise_sample___mocks___test_fixtures_cjs_two_only_one_js --> test_runDepcruise_sample___mocks___test_fixtures_cjs_sub_dir_js
```

Next, here is the result of compressing the filenames and removing indentation and whitespace:

```mermaid
flowchart LR
subgraph a["test"]
subgraph b["runDepcruise"]
subgraph c["sample"]
subgraph d["__mocks__"]
subgraph e["test"]
subgraph f["fixtures"]
subgraph g["cjs"]
h["one_only_one.js"]
i["one_only_two.js"]
j["root_one.js"]
k["shared.js"]
subgraph l["sub"]
m["dir.js"]
n["depindir.js"]
end
o["root_two.js"]
p["somedata.json"]
q["two_only_one.js"]
end
end
end
end
end
end
end
j --> i
j --> k
j --> m
m --> n
o --> k
o --> p
o --> q
q --> m
```

(The syntax of mermaid seems to require a newline code)
You can see that the number of characters in the text is also overwhelmingly reduced, while the same rendering content.

**Comment by sverweij** [comment]
Hi @MH4GF - this suggestion makes sense. The easiest way to make this an option is to convert the mermaid plugin to a regular reporter (was planning to propose that anyway see PR #) and pair it with one or two [reporterOptions](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/options-reference.md#reporteroptions) of its own. 

"Compression"-wise I see two differences in your example:
- losing non-significant whitespace
- using (on average) shorter 'hashes' for the filenames

What'd you think to have `minify: true` the default? I guess most folks wouldn't 'read' the mermaid anyway + the performance impact should be negligible. If people need to see more readable mermaid (e.g. for debugging) they can always override it.

> It seems in mermaid syntax you can end a line with either a newline or a semi-colon. Byte-saving wise that won't do much, though :-)

**Comment by MH4GF** [comment]
Hi @sverweij !! I see you're busy, Thanks for all the quick replies!

> The easiest way to make this an option is to convert the mermaid plugin to a regular reporter (was planning to propose that anyway see PR https://github.com/sverweij/dependency-cruiser/pull/622) and pair it with one or two [reporterOptions](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/options-reference.md#reporteroptions) of its own.

Oh, that's great news for me too! 😄 

> What'd you think to have minify: true the default? I guess most folks wouldn't 'read' the mermaid anyway 

I completely agree with you, I think minified text would be more useful for many use cases.

> It seems in mermaid syntax you can end a line with either a newline or a semi-colon. 

Oh, I didn't know that! 👀

**Comment by MH4GF** [comment]
@sverweij  If this proposal looks good to you, I'll implement it on my end and send out a PR.

**Comment by sverweij** [comment]
@MH4GF yes, looking good - please go ahead :-)
