### ISSUE TITLE
Question: How to forbid any dependency between feature-folders with one specific exception

### ISSUE THREAD

**Issue by rabbl** [sverweij/dependency-cruiser#629]
### Summary

Thanks for creating this stunning tool for the community.  

We are searching for a ruleset where at one hand the 'features-not-to-features' rule applies (which should prevent interaction between feature-folders) but these features (modules) can interact over one specific connection that should be allowed.

### Context

We are implementing a modular hexagonal architecture where the 'modules' are forbidden to depend on each other.  
For this we can apply the well documented rule: ['features-not-to-features'](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/rules-tutorial.md#isolating-peer-folders-from-each-other).

But as they can connect over the ports/adapters they can have dependencies in between specific folders but only this and in ine direction. For example we have two 'modules' Authentication and User in:  
 
* src/app/modules/authentication
* src/app/modules/user

Each 'module' has an 'incoming' and an 'outgoing'-folder and the user-'module' can depend on the authentication-'module'  this way and vice versa:

* src/app/modules/user/incoming -> src/app/modules/authentication/outgoing
* src/app/modules/authentication/incoming -> src/app/modules/user/outgoing

I have tried this rule:

```
{
      name: 'no-cross-module-import',
      comment: "Cross module references are prohibited",
      severity: 'error',
      from: {
        path: '^src/app/modules/(authentication|user)/([^/]+)/.+',
        pathNot: '^src/app/modules/(authentication|user)/outgoing/.+',
      },
      to: {
        path: '^src/app/modules/(authentication|user)/.+',
        pathNot:  '^src/app/modules/$1/.+'
      }
    },
```

Is it possible somehow to define a ruleset that can acomplish that?
Forbid every dependency except this specific dependency?

Saludos

**Comment by sverweij** [comment]
hi @rabbl thanks for this interesting question - and sorry it so long to answer it. 

If I understand correctly there's a structure setup that looks (extremely simplified) like this:

![before-dependency-graph](https://user-images.githubusercontent.com/4822597/180596028-97bec7fd-c859-4be7-a6d5-36086982b0dc.svg)

And there's two rules:

- Inter module dependencies are forbidden
- There's an exception for modules inside a folder called `incoming` that _are_ allowed to depend on other modules, but only from the `outgoing` folder of that module.

To illustrate in the terms of the picture above (I've given the two rules different severities, so they're easier to distinguish):

![after-dependency-graph](https://user-images.githubusercontent.com/4822597/180596139-3c91bcac-eee0-4943-8bb8-bdc623deaf5f.svg)

One way to accomplish this:

```javascript
//...
  forbidden: [
    {
      name: "no-cross-module-import",
      severity: "error",
      from: {
        path: ["^src/modules/([^/]+)/.+"],
        // except 'incoming' modules from this rule - we have a
        // separate one for that below
        pathNot: ["^src/modules/.+/incoming"],
      },
      to: {
        path: "^src/modules/",
        pathNot: ["^src/modules/$1/"],
      },
    },
    {
      name: "incoming-only-to-external-outgoing",
      severity: "info",
      from: {
        path: ["^src/modules/([^/]+)/incoming"],
      },
      to: {
        // 'incoming' folders can't depend on other modules either;
        path: ["^src/modules/"],
        // except for their own module, and 'outgoing' folders in 
        // other modules.
        pathNot: ["^src/modules/$1/", "^src/modules/.+/outgoing"],
      },
    },
  ],
//...
```

I've put the sample modules, working .dependency-cruiser.js etc in [dependency-cruiser-repro-repo/629](https://github.com/sverweij/dependency-cruiser-repro-repo/tree/main/629)

Does this look like what you need?

**Comment by rabbl** [comment]
First of all, sorry for being delayed responding to this issue. 
I had now time to test it and it worked as expected.
Thank you very much that you took the time to build an example for this and giving me the final hint to solve it. 
I'ts a great work what you're doing for the community and I'd love to use and spread the word about your tool.
