### ISSUE TITLE
Feature request: Allow `import type`, and not `import` statements

### ISSUE THREAD

**Issue by kyranjamie** [sverweij/dependency-cruiser#630]
### Context

In my particular use case, a browser extension, I'm using a polyfill which gets set as a global. As such, I want to prohibit the library itself being imported (the global should be used). However, there are cases where we want to access the types with a `import type` statement (which doesn't bloat the final bundle).

### Possible Solution

A rule config modifier, along the lines of `allowTypeImports: true` that won't throw an error when the matching rule uses `import type`.

**Comment by sverweij** [comment]
Hi again @kyranjamie - it might be the [dependencyTypes and/ or dependencyTypesNot] (https://github.com/sverweij/dependency-cruiser/blob/develop/doc/rules-reference.md#dependencytypes-and-dependencytypesnot) restriction deliver what you're looking for - the _dependencyType_ `type-only` is used exclusively for import clauses that are type only (`import type`). Do these fit your use case?

**Comment by kyranjamie** [comment]
Ah, great. Completely missed this. Thanks @sverweij 👉🏼  https://github.com/hirosystems/stacks-wallet-web/pull/2524/commits/af277735d1b3ed049d8344f679fb80032a89985c
