### ISSUE TITLE
Unable to follow dependency with absolute path using typescript

### ISSUE THREAD

**Issue by juliensnz** [sverweij/dependency-cruiser#631]
I have a project using typescript with the following rules:

```
    "baseUrl": ".",
    "paths": {
      "~/*": ["src/*"]
    }
```

And all my imports look like this:

```
import {JobExecutionId} from '~/ProductExport/domain/model/JobExecution';
```

Dependency cruiser doesn't seems to follow those imports and I cannot find a way to make it work.

### Expected Behavior

It should follow all paths aliases

### Current Behavior

It does not follow path aliases

### Steps to Reproduce (for bugs)

Here is a code sandbox to reproduce the bug https://codesandbox.io/s/dependency-cruiser-absolute-imports-bug-forked-y5mgvt?file=/package.json

### Your Environment

- Version used: latest (11.11.0)
- Node version: 16.15.1
- Operating System and version: Mac os 12.4
- Link to your project: https://codesandbox.io/s/dependency-cruiser-absolute-imports-bug-forked-y5mgvt?file=/package.json

Thanks a lot for all your hard work on this awesome library. Don't hesitate to tell me if some informations are missing :)

**Comment by sverweij** [comment]
Hi @juliensnz thanks for the code sandbox, that makes reproducing your issue a lot easier. 

It looks like it's not an issue in dependency-cruiser though:

- It seems the depcruise command in the package.json doesn't tell dependency-cruiser to use a configuration file (it needs to be explicitly set for backwards compatibility reasons). That way it'll also know to find the tsconfig.json that contains the path alias. If you use a file with one of the standard names dependency-cruiser will sort out where it lives:

```
  ...
  "depcruise": "depcruise --config --include-only \"^(src)\" --output-type dot src | dot -T svg > dependencygraph.svg"
  ...
```

Or if you like to be explicit

```
  ...
  "depcruise": "depcruise --config .dependency-cruiser.js --include-only \"^(src)\" --output-type dot src | dot -T svg > dependencygraph.svg"
  ...
```


- When you do this you'll bump into the next thing; in the code sandbox the configuration file is called .dependency-cruiser.json - but its contents are javascript. That'll confuse the hell out of the parser (which will yell something like `ERROR: JSON5: invalid character 'm' at 2:1`). Fix: rename the .dependency-cruiser.json to .dependency-cruiser.js

- When that's fixed - it looks like the tsconfig.json provided isn't valid json; typescript's json parser really wants to see a comma at the end of line 30. Fix: add that

- Next the typescript compiler complains the 'lib' version (["ES2021"]) isn't valid. Luckily it helpfully throws an error message with a bunch of valid options. Fix: pick one of them (I picked ["es2020"])

Now `yarn depcruise` yields something expected:

<img width="232" alt="image" src="https://user-images.githubusercontent.com/4822597/177411452-5c632738-ad36-47c3-a959-e0c60cad7ecf.png">


> code sandbox is nigh unusable on my machine so I copied the code over to the
> dependency-cruiser-repro-repo and applied the fixes there - feel free to peruse/ 
> copy from there: [dependency-cruiser-repro-repo/tree/main/631](https://github.com/sverweij/dependency-cruiser-repro-repo/tree/main/631)
