### ISSUE TITLE
Feature request: graph showing only the dependent modules

### ISSUE THREAD

**Issue by El-Chiang** [sverweij/dependency-cruiser#632]
This tool is a great idea! Inspired by it, I added a job to the ci pipeline to analyze the impact (dependants) of each PR. However, our team works on a giant web application, if I show all the dependencies, this graph will be very large and not conducive to checking. So, is there a way only to show the dependants? 

### Context

Let me give you an example to describe the problem I am facing:

- There is an A->B->E and C->D->E dependency
- In this PR, I have modified the E
- Now, I want to find all the modules that depend on D, i.e. A ~ D.

Currently, I configure `reachable` rule and output to `err-report` to solve my need, but I also want to show their dpendency path through the graph, not only html report.

### Possible Solution

Is it possible to provide a `reaches` CLI option to filter out all dependants (like `reachable` rule)

**Comment by sverweij** [comment]
Hi @El-Chiang there's currently no _reaches_ or _reachable_ filter option in the CLI or the API. Besides being a good idea for pull request context I think it'll fulfil a more general need as well - in #469 there was a request for something similar.

What CI do you use?

### related work
For PR's I currently use the [--focus](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/cli.md#--focus-show-modules-and-their-direct-neighbours) option to highlight changed files and all modules they depend on and that depend on them.

**Comment by El-Chiang** [comment]
In the CI, it gets all the diff files at every PR and executes the depcruise command to analyze all the modules that depend on these diff files, and finally generates a report.

I thought about using the `--focus` command before, but in my case, I actually only focus on all modules that depend on them. And if I have multiple files that need to be focused, I have to execute this command in a loop.

**Comment by sverweij** [comment]
Hi @El-Chiang - I've made a stab at a `--reaches` filter (works both in the `depcruise` and `depcruise-fmt` command line and in the API) - see the linked PR above. 

The beta `dependency-cruiser@11.12.0-beta-2` on npm (just published) contains this feature. The feature will probably land in the next regular release (expected this Monday). 

In any case I'm curious whether it helps in your use-case. If you have any feedback it'll be very welcome!

**Comment by sverweij** [comment]
@El-Chiang FYI - the regular release (`dependency-cruiser@11.12.0`) with the reaches filter has just landed on npm. As said earlier: feedback is very welcome.

**Comment by El-Chiang** [comment]
Thanks @sverweij!  This works great for me 🎉
