### ISSUE TITLE
Allow .tsx files and path alias from tsconfig.json

### ISSUE THREAD

**Issue by jimsheen** [sverweij/dependency-cruiser#633]
Currently, this package does not support .tsx (TypeScript JSX files)

### Context

It would be really nice if this supported tsx files. Running the cli or in package.json script like this `    "depcruise": "depcruise --config .dependency-cruiser.js --include-only \"^(src)\" --output-type dot src | dot -T svg > dependencygraph.svg"` results in an empty graph output. This is because my whole src dir is .tsx or .ts files which seems like they are not found when running depcruise

I added ` extraExtensionsToScan: ['.tsx']` in dependency-cruiser.js config and a graph does get generated but there is no relationship. 

Interestingly, the .tsx files are found and output is correct when using this package as an API like this:
```
const cruiseResult: IReporterOutput = cruise(
      ARRAY_OF_FILES_AND_DIRS_TO_CRUISE,
      {
        exclude: ['node_modules'],
      }
    );
```

However, the paths alias from tsconfig.json are not being transformed in the output. E.g. `@components/Button` remains where it should have been converted to `src/components/Button` as per tsconfig.json:

```
 "compilerOptions": {
    "baseUrl": "./",
    "paths": {
      "@components/*": ["./src/components/*"],
```

Output:
```
{
          "module": "@components/Badge",
          "moduleSystem": "es6",
          "dynamic": false,
          "exoticallyRequired": false,
          "resolved": "@components/Badge",
          "coreModule": false,
          "followable": false,
          "couldNotResolve": true,
          "dependencyTypes": ["unknown"],
          "matchesDoNotFollow": false,
          "circular": false,
          "valid": true
        }
```

**Comment by sverweij** [comment]
hi @jimsheen both `.tsx` files and ts path aliases are supported out of the box provided ...

- dependency-cruiser is installed at the same spot as your typescript compiler (which is typically in your project/ repo). An easy check is to run `npx dependency-cruiser --info`, which will return what compilers it has at its disposal and what extensions it will peruse.
- it's configured to find the correct (and valid) tsconfig.json

The [`extraExtensionsToScan`](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/options-reference.md#extraextensionstoscan) option only exists to accommodate unparseable files that nonetheless need to be included in a dependency scan. As documented behind the link: dependency-cruiser will not parse any file matching the extra extension.

So it's better to remove the option if you don't need it (and not to include any extension of files you actually want analysed.

Samples of extensions that might go into the 'extra extensions' are .jpg or .png 

> without a reproduction example (including a .dependency-cruiser.js, tsconfig.json and some sample files) it's not easy for me to see what is going awry in your specific situation. If the above suggestions don't help don't hesitate to drop a reproduction sample (e.g. link to a repo or even a verbatim paste of both in a comment).
