### ISSUE TITLE
Typescript definition changes in 11.14.0 fails type checks

### ISSUE THREAD

**Issue by hoonoh** [sverweij/dependency-cruiser#644]
Hello, 

https://github.com/sverweij/dependency-cruiser/pull/643 changed `cruise` and other exported functions in `dependency-cruiser.d.ts` as types which breaks previous (currently documented) usage with typescript.

```ts
import { cruise } from 'dependency-cruiser';

cruise([]); // will throw TS error `'cruise' only refers to a type, but is being used as a value here. ts(2693)`
```

### Expected Behavior

`cruise` should be kept as function, or there should be another way to import the function.

### Current Behavior

Will throw `TS2693` error.

### Possible Solution

Revert changes in https://github.com/sverweij/dependency-cruiser/pull/643  or introduce a different way to import `cruise` function when using the API.

### Your Environment

- Version used: v11.14.0
- Node version: v16.15.1
- Operating System and version: Ubuntu 20.04.4
- Link to your project: NA

**Comment by sverweij** [comment]
dependency-cruiser@11.14.1 which should have the older, correct type definitions on board has just been published.
