### ISSUE TITLE
Question: How to create config for modules with index.ts that does not break circular dependency rule?

### ISSUE THREAD

**Issue by wjureczka** [sverweij/dependency-cruiser#652]
Hi, thanks for your great tooling!

### Summary
So my problem is connected with index files of modules. When I import code directly from the files, the circular dependency is not detected. It is proper behavior.
When I create an `index.ts` file with re-exports of the code from the directory, importing them from another module breaks the rule.

The picture below shows a structure that breaks the rules. I would like to make the dependency-cruiser accept such patterns.

The `x.ts` and the `z.ts` import the `y.ts`. The `y.ts` imports nothing.

![image](https://user-images.githubusercontent.com/24592871/186648433-1197f00b-119d-482b-a331-c75aa9165ade.png)

### Environment

- Version used: 11.14.1
- Node version: 16.16.0
- Operating System and version: macOS

**Comment by sverweij** [comment]
Hi @wjureczka thanks for this question!

You can add an exception to circular rules based on what cycles pass through, with the [`viaNot`](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/rules-reference.md#via-and-vianot-viaonly-and-viasomenot---restricting-what-cycles-to-match) attribute.


```javascript
// log an error for all circular dependencies except when they are via one of the barrels
{
  name: 'no-circular',
  severity:  'error',
  from: {
  },
  to: {
    circular: true,
    viaNot: [
      'index.ts$'
    ]
  }
},
```


It's still a circular dependency you might want to get rid of eventually, though - with the `via` attribute - have them as a rule with a lower severity e.g.:

```javascript
// for circular dependencies that pass through one of the barrels generate a warning
{
  name: 'no-circular (exception for known barrels)',
  severity: 'warn',
  from: {
  },
  to: {
    circular: true,
    via: [
      'index.ts$'
    ]
  }
}
```

You can read more about this in
- [rules reference: via and viaNot, viaOnly and viaSomeNot - restricting what cycles to match](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/rules-reference.md#via-and-vianot-viaonly-and-viasomenot---restricting-what-cycles-to-match)
- [issue 505](https://github.com/sverweij/dependency-cruiser/issues/505) which is the issue that led to the addition of these attributes.

Hope this helps!

**Comment by wjureczka** [comment]
@sverweij really appreciate the answer, thanks for the help!
