### ISSUE TITLE
Improve ICruiseOptions type

### ISSUE THREAD

**Issue by t-yng** [sverweij/dependency-cruiser#653]
### Summary

ICruiseOptions does not receive `ruseSet.optioins.tsConfig.fileName` property in TypeScript code.

I can't set option for the cruise function to read tsconfig.json because of type error.
I must write `@ts-ignore` to read tsconfig.json by the cruise function in TypeScript code.

```typescript
const cruiseOptions: ICruiseOptions = {
  // NOTE: dependency-cruiser does not read tsConfig if options.tsConfig is not set
  // @see: https://github.com/sverweij/dependency-cruiser/blob/d2ab3deed0d0bd2bcdb7b9a9f2198f2ecaca8c34/src/main/resolve-options/normalize.js#L89
  ruleSet: {    
	// Error: Type '{ options: { tsConfig: { fileName: string; } | undefined; }; }' is not assignable to type 'IFlattenedRuleSet'.
    options: {
      tsConfig:
        tsConfigFileName && tsConfig
          ? { fileName: tsConfigFileName }
          : undefined,
    },
  },
};
const tsConfig = extractTsConfig('tsconfig.json');

const result = cruise(['src'], cruiseOptions, undefined, tsConfig);
```

### Expected Behavior

ICruiseOptions receives `ruseSet.optioins.tsConfig.fileName` property in TypeScript code.

### Current Behavior

TypeScript compiler raise type error `Type '{ options: { tsConfig: { fileName: string; } | undefined; }; }' is not assignable to type 'IFlattenedRuleSet'`.
But I can avoid this error by `@ts-ignore`, so this is not critical.

### Bug Reason

Now dependency-cruiser check `ruseSet.options.tsConfig.fileName` is set to read tsconfig.json in bellow code.
So I must set `ruleSet.options.tsConfig.fileName` property to options of the cruise function, but ICruiseOptions doesn't receive the property. So I can't write type safe code to read tsConfig.

https://github.com/sverweij/dependency-cruiser/blob/d2ab3deed0d0bd2bcdb7b9a9f2198f2ecaca8c34/src/main/resolve-options/normalize.js#L89

### Possible Solution

add property `options.tsConfig.fileName` to ICruiseOptions type.

```typescript
// New
interface IRuseSetOptions {
  tsConfig: {
    fileName: string;
  }
}

export interface IFlattenedRuleSet {
  ....

  // New
  options: RuseSetOptions;
}
```

**Comment by sverweij** [comment]
Thanks @t-yng for spotting the bug and raising it as an issue. Sorry it took me so long to respond - I'll try and massage the typescript definition for this into shape over the weekend (and in parallel try to find a better way to sync it with the json-schema which is the definitive source for model validation and which _does_ have the correct attributes) and release it.
