### ISSUE TITLE
Question: Graph out dependencies of dependencies

### ISSUE THREAD

**Issue by vorehoci** [sverweij/dependency-cruiser#656]
I want to write out all Dependencies of my Homepage.vue
That means that I also want to see the tree of any dependencies of dependencies of Homepage.vue

folder structure

```
src / pages / ...
src / components / ...
src / utils / ...
```

Example of the command that I run.

`"depcruise -x \"node_modules\" \"src/pages/Homepage.vue\" --output-type dot | dot -T svg > dependencygraph.svg"`

It will generate svg with things like `header.vue` and `footer.vue` and any utils used in the Homepage.vue.
But it wont generate any dependancies that header or footer use such as `Button.vue`. Is there a command or option that would also generate that?

**Comment by sverweij** [comment]
> I'm also using webpack ( with aliases ), and have dependency-cruiser.js set up.
>
> Is it required to reference dependency-cruiser.js when running the npm script?

Yes, if you want that taken into account it is :-). Just pass `--config` (if you're using the default configuration name (`.dependency-cruiser.js`)) or `--config yourdependencruiser.js` if you use a custom configuration file name.
