### ISSUE TITLE
Bug: GraphViz assertion error - relatively small .dot file

### ISSUE THREAD

**Issue by magland** [sverweij/dependency-cruiser#659]
(First of all, thanks for this amazing tool - I hope I will be able to use it!)

### Expected Behavior

graphviz dot command should not fail on the .dot file output by dependency-cruiser when the graph is not too large

### Current Behavior

I get the following assertion error in graphviz
```
$ dot test.dot
dot: mincross.c:1561: flat_reorder: Assertion `constraining_flat_edge(g,v,e) == FALSE' failed.
Aborted (core dumped)
```

I have attached the `test.dot` file which is only 160 lines.
[test.dot.txt](https://github.com/sverweij/dependency-cruiser/files/9527335/test.dot.txt)

I noticed the same error in #15, but the conclusion there was that the graph was too large for graphviz to handle. I don't think that's the case here since the file is relatively small.

I also note that the top google hit for that assertion error is #15, which leads me to think this may be a dependency-cruiser-specific issue.

### Possible Solution

I suppose one could manually remove edges from the test.dot file until it works in order to get an idea of what the offending edge or node might [be.](url)

### Steps to Reproduce (for bugs)

1. git clone https://github.com/magland/spikesortingview
2. git checkout c0610d22930ec3ded2d0288d609f3a8a56c5ba65
3. yarn install
4. yarn run dependency-dot-debug
5. This produces a test.dot file. Try running dot on it. 

### Context

I am trying to generate a dependency graph for my project. I am using this for development purposes. This was working beautifully until I added the last module. This is a great tool, and I'm disappointed that I may not be able to use it.

### Your Environment

dot - graphviz version 2.43.0 (0)

"dependency-cruiser": "^11.15.0"

npm 8.6.0

node v16.14.2

Ubuntu 20.04

https://github.com/magland/spikesortingview

**Comment by magland** [comment]
Follow up. If I remove a single line from the .dot file, it works. The line is 156:

```
"src/libraries/view-units-table/" -> "src/libraries/component-sortable-table/"
```

Strangely, if I remove other lines, the problem persists. Didn't investigate too much further yet.

**Comment by magland** [comment]
Another possible clue. If I use `reporterOptions.dot.theme.replace: true`, I don't see the problem. So it seems to have something to do with the theme/styling.

Also, this works on a much larger graph if I increase `--collapse 3` to `4`

**Comment by magland** [comment]
FWIW I grew my graph larger and now it doesn't crash. So this is probably a weird error in GraphViz.

Feel free to close. But I think it may be useful to keep a reference to the attached .dot file for future debugging, in case someone runs into the same problem.

**Comment by sverweij** [comment]
Hi @magland thanks for the heads-up (+ for raising this issue in the first place & the detailed reproduction data. That's been really helpful). 

After some bisecting I found that removing `ordering="out"` ensures this particular graph renders error free. As [ordering](https://www.graphviz.org/docs/attrs/ordering/) puts an extra restriction on the GraphViz' graph layout algorithm it makes sense it triggers boundary conditions earlier. I for the life of me don't remember why it's in, so I've tried leaving it out on some projects (both public and private) and the difference is as pepsi vs coca; it is noticeable, but in the end it's still cola.

For the short term, when you might encounter this problem again:  if you add `ordering: ""` to the graph attributes GraphViz will render graph without errors.

For the medium/ longer term: I'll look into making the empty `ordering` attribute the default and release it as such. It seems to work just fine without, but I want to try it on a reasonable number of repo's first.

> not related to this issue, but in the case of this particular graph you might also want to add `splines: "ortho"` - orthogonal routing will improve the readability of your graph quite a bit.

**Comment by magland** [comment]
Thanks @sverweij that's very helpful!
Regarding "ortho" I agree it's better appearance. However, I have it as spline because I generate graphs in two modes and the second graph is much larger and it takes way too long to generate with "ortho". Wondering if there's a quick way to use one config .js file, but provide switch between ortho/spline at runtime. Not a big deal, but if there were, I'd probably use it.
