### ISSUE TITLE
Question: How to visualize a tree view of folders/files

### ISSUE THREAD

**Issue by rabbl** [sverweij/dependency-cruiser#662]
### Summary

If there is a lot of code in modules, the dependency graph gets bigger and in some cases it's difficult to get relevant information from it, regarding violations. 

### Context

I found a very good visualization for this case in the Book from  ["Carola Lilienthal": Sustainable Software Architecture](https://sustainable-software-architecture.com/) where they're analyzing big codebases:

![image](https://user-images.githubusercontent.com/1965304/190076294-b6c4d633-cc72-4317-8288-ea355e03fb09.png)

Do you think this is possible wit dot?   
Where is the best starting point to develop such a plugin for me and the community? 

Best regards,
Ralf

**Comment by sverweij** [comment]
Hi @rabbl as far as I know this isn't possible with `dot` - but dependency-cruiser's internal data model (and hence the input available to reporter plugins) does have all data available. 

- [FAQ entry on plugins](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/faq.md#as-a-plugin)
- The [stats reporter plugin](https://github.com/sverweij/dependency-cruiser/blob/develop/configs/plugins/stats-reporter-plugin.js) and the [3d reporter plugin](https://github.com/sverweij/dependency-cruiser/blob/develop/configs/plugins/3d-reporter-plugin.js) might be good starting points. Even though both live in the dependency-cruiser repo, it's perfectly possible to have one live in a separate repo.
