### ISSUE TITLE
Feature request: option to disable "showing code on click" in generated html

### ISSUE THREAD

**Issue by JenniferFalkenstein** [sverweij/dependency-cruiser#663]
If you generate an html output with `depcruise-wrap-stream-in-html` and open it, you get an interactive graph of the dependencies. You also have the option to click at one of the rectangles, which redirects you to your file (I guess) and shows the code in your browser. Unfortunately I couldn't find any option to disable this behaviour.

### Context
We use Gitlab Pages to host the generated dependency graph and some typedoc documentation for our codebase. The moment we open the dependency graph and click on one of the rectangles, it redirects to an 404 error page, since Gitlab doesn't know what to do.

### Expected Behavior
Therefore an option to disable this feature would be nice, so the developers in our company won't get confused with the 404.
Another cool feature would be - but I'm not sure how or if it's possible to implement that - to somehow redirect to our typedoc documentation.

### Current Behavior
The current behaviour is like mentioned above: Redirects to an 404 error when hosting it at the Gitlab pages and (as far as I saw) there isn't an option to disable the "on-click"-feature in html.

### Possible Solution
I don't have a solution but maybe it might be a nice idea to put it into the `.dependency-cruiser.js`-configuration-file 🙂

**Comment by sverweij** [comment]
Hi @JenniferFalkenstein it's currently not possible to (really) disable the links, but it _is_ possible to point it to the spot where (a copy of the) code tree lives with the [`prefix`](https://github.com/sverweij/dependency-cruiser/blob/doc/copy-edit-readme/doc/options-reference.md#prefix-prefix-links-in-reports) option (or the [`--prefix`](https://github.com/sverweij/dependency-cruiser/blob/doc/copy-edit-readme/doc/cli.md#--prefix-prefixing-links) command line option), which might make it a bit more useful, as you can point to to e.g. the source code on GitLab (by setting it to something like `https://gitlab.com/youraccount/yourrepo/-/tree/yourmainbranch/`). If TypeDoc uses fully qualified file names in its URLs (it doesn't seem so, from a quick glance, but I might be missing something) it'd be possible to point it there as well.

It's of course possible to add a thing to the dependency-cruiser options to prevent the dot reporter from generating links - but I secretly hope the `prefix` option will prove useful to you in stead ...
