### ISSUE TITLE
Question: Circular dependency at module level leading to false positives

### ISSUE THREAD

**Issue by pdrm6000** [sverweij/dependency-cruiser#671]
Hi, 

I realized that we have some false positive circular dependencies. 
When `Component A` depends on `Component B` and `Component B` is being exported from a TS file that also exports `Component C`, depcruiser thinks that `Component A` also depends on `Component C` and continues exploring the dependency graph of `Component C` which may end up pointing back to `Component A`.

But `Component A` is not really using or depending on `Component C`, is this the expected behavior ? is there a way to configure depcruiser to look only into the used dependency and not the whole module ?

Maybe some code example would help:
`Component A` would have some import like this

``` 
import { componentB } from "somewhere/exporting/many/modules";`
```

`modules.ts` would do something like:

```
export { componentB } from "./components/componentB";
export { componentC } from "./components/componentC";
```

then somewhere inside `componentC` there will be internal dependencies importing `componentA`

**Comment by sverweij** [comment]
hi @pdrm6000 thanks for this question.

If I understand the question well the components you have are spread across a few modules. The components themselves don't seem to have a circular relationship, but the modules do (check?).

dependency-cruiser charts dependencies between modules and the cycles it reports are between modules as well. So if you've got the situation below, you still get a cycle on module level, even though the objects/ components themselves don't. Likewise if you have objects/ components that depend on each other but that are defined within a module, dependency-cruiser won't flag it.
