### ISSUE TITLE
unused/orphaned exports

### ISSUE THREAD

**Issue by waynebrantley** [sverweij/dependency-cruiser#674]
First - Nice tool - is great to use to help keep code clean

The feature I am requesting is unused exports.  Your product will report orphaned modules/files, but if a file exports a symbol and that symbol is not used outside that module - I would like to find that.
### Context
This project does pretty much that:  https://www.npmjs.com/package/ts-unused-exports

I thought this feature would fit right into the capabilities you have now - just down from 'module' level to individual export level.

Thoughts?

**Comment by sverweij** [comment]
hi @waynebrantley thank you for the compliment - and for the suggestion.


dependency-cruiser specialises in doing static checks on the module level. Static checks on exports require operating on a lower level of granularity than the module - and are a different ball game. I try to focus dependency-cruiser to do one thing really well to keep it manageable and maintainable.

I've used both ts-unused-exports and [ts-prune](https://www.npmjs.com/package/ts-prune) in my day job. Seeing they're both doing quite a decent job at detecting unused exports I'm also not sure what dependency-cruiser would be able to add to the mix (but I'd curious to hear if there'd be any!).

**Comment by waynebrantley** [comment]
Understood - was thinking all the same type of features you have - but more at an lower level.  The other tool works well, just be nice to have together!  Thx for considering.
