### ISSUE TITLE
Issue: can't import npm package punycode

### ISSUE THREAD

**Issue by aryzing** [sverweij/dependency-cruiser#678]
### Expected Behavior

The npm module `punycode` should be importable in a web app

### Current Behavior

An error is reported when using 

```
extends: 'dependency-cruiser/configs/recommended',
```

### Possible Solution

not sure

### Steps to Reproduce (for bugs)

1. Install npm module punycode, `yarn add punycode`
2. Attempt to import it while using `recommended`
3. Error when linting

### Context

I'm building a web app, not a node.js app. It doesn't make sense to consider `punycode` a built-in on the web.

**Comment by sverweij** [comment]
Hi @aryzing it's possible to re-configure the `no-deprecated-core` rule in your dependency-cruiser-config. There's various options, depending on how your project looks (see below). 

B.t.w. regardless whether you're using nodejs or not, this seems like a false positive to me. I'll make a small reproduction sample and if my hunch is correct release a patch for it.


#### option 1: disable the rule completely

From your description it seems you're not interested in node core modules at all. In that casesomething simple like this will suffice:

```javascript
module.exports = {
  extends: "dependency-cruiser/configs/recommended",
  forbidden: [
    {
      name: "no-deprecated-core",
      severity: "ignore",
      // no need to specify the from and to, because they're already
      // defined in 'recommended'
    },
    // ... your other rules here
  ],
  options: {
    // .. your options here
  }
};
```

#### option 2: just remove the punycode module from the checked list

```javascript
module.exports = {
  extends: "dependency-cruiser/configs/recommended",
  forbidden: [
    {
      name: "no-deprecated-core",
      // no need to specify the 'from' and 'severity' as they're in 'recommended' already
      to: {
        dependencyTypes: ["core"],
        path: "^(domain|constants|sys|_linklist|_stream_wrap)$",
        // was:
        // path: "^(punycode|domain|constants|sys|_linklist|_stream_wrap)$",
      }
    },
    // ... your other rules here
  ],
  options: {
    // .. your options here
  }
};
```

**Comment by sverweij** [comment]
Hi @aryzing I've dug a bit deeper into the punycode/ punycode situation.On nodejs the string 'punycode' is always resolves to the node core punycode library even when the npm package is installed. On the web this will be different, but if you use any build tools (e.g. webpack) or static analysis tools (e.g. eslint, dependency-cruiser) they typically use nodejs and/ or the nodejs module resolution algorithm and will resolve it to the native module. This might also mean your bundler might use the wrong library as well(!).

The [README of the punycode.js](https://github.com/mathiasbynens/punycode.js) package on npm has a section on it with a suggestion/ warning: require/ import it as `"punycode/"` (with a slash on the end):

> <img width="845" alt="image" src="https://user-images.githubusercontent.com/4822597/197333384-5324c107-b5d1-456e-a273-41f7c38e8d45.png">

**Comment by aryzing** [comment]
Thanks for all the help. I updated my rules and works just fine 👌. And thanks for emphasizing punycode's import recommendations when using `require()`. 

It seems that using ES `import` statements with Webpack works as expected: the node_modules package is used, not Node's built-in.
