### ISSUE TITLE
Question: ...how to deal require path that have variable

### ISSUE THREAD

**Issue by wohugb** [sverweij/dependency-cruiser#679]
If the require path has variable ,how to deal
### Summary

Like this: ```const tools = require(`${config.path.mw}tools.mw`);```

**Comment by sverweij** [comment]
Hi @wohugb - dependency-cruiser does not support that. dependency-cruiser does [static program analysis](https://en.wikipedia.org/wiki/Static_program_analysis). Evaluating variables in dynamic requires and imports means it'd have to execute your program and analyse that. That field of program analysis ([dynamic program analysis](https://en.wikipedia.org/wiki/Dynamic_program_analysis)) is also fun and useful to do, but it's a different ball game.

> see also this [FAQ entry](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/faq.md#q-does-dependency-cruiser-handle-variable-or-expression-requires-and-imports)
