### ISSUE TITLE
Question: Does the "moreUnstable" condition work correctly?

### ISSUE THREAD

**Issue by Daumel** [sverweij/dependency-cruiser#683]
Hello,

I'm testing dependency cruiser on an open source project called [lokaler-kaufen](https://github.com/lokaler-kaufen/lokaler-kaufen-app). I'm not sure if the condition "moreUnstable" for testing against the Stable Dependencies Principle works correctly.

I use following rule in the forbidden section:
![Rule](https://user-images.githubusercontent.com/44206289/200804466-a88acede-2ccd-4d3d-bc72-d4c0d3b111fd.PNG)

The output is:
![Error](https://user-images.githubusercontent.com/44206289/200804462-7742dcf6-0180-48fd-acc5-7be177237b6d.PNG)

I don't understand what the values mean. I expected them to be between 0 and 1.

- Version used: 11.18.0
- Node version: 16.15.1

**Comment by sverweij** [comment]
hi @Daumel thanks for your question!

Indeed the stability metric as defined/ popularised by Robert C. Martin has values between 0 and 1. For readability dependency-cruiser multiplies them by 100 - so what you see is the SDP expressed as a percentage.

Your question makes me realise this isn't documented yet - I'll rectify that + maybe add a `%` sign to the reporters so it's more clear (and arguably more correct as well).
