### ISSUE TITLE
Question: Resolved names in yarn monorepo

### ISSUE THREAD

**Issue by devcorraliza** [sverweij/dependency-cruiser#684]
### Summary
Applying a dependency analysis at a yarn monorepo dependencies to other workspaces are named as relative physical paths instead as workspace relative. 
With this workspace structure:
Workspace1: @libraries/lib1 at ./libs/library1
Workspace2: @libraries/lib2 at ./libs/library2

When analizing library1 it has imports from @libraries/lib2 but at reports and graphs these imports are shown as .. (relative physical path).

Is there a way to make results been shown as @libraries/lib2, using workspaces names?

### Environment
- Version used: 11.18.0
- Node version: 14.19.3
- Yarn version: 3.2.4
- Operating System and version: OSX

**Comment by sverweij** [comment]
Hi @devcorraliza thanks for your question.

At this time dependency-cruiser uses the 'real' path exclusively. It's the only way to ensure it doesn't mistake the same module for several others. 

That said, it is possible to introduce a 'display name' for modules that have aliases (/ workspace names/ name mappings/ etc). 
- We would have to find a way to resolve conflicts when there's more than one alias assigned to a folder (i.e. pick one, don't use any when there's > 1, throw an error). 
- We'd probably want to put it behind another option (showAliasedDisplayNames or something like that) in order not to break backwards compatiblitty.
- In reporters with a bit more visual space we might want to show both the display name and the real path.
