### ISSUE TITLE
Feature request: Support `$ref` from JSON Schema and Open API

### ISSUE THREAD

**Issue by daniel-white** [sverweij/dependency-cruiser#696]
### Context

we are looking to adopt dependency cruiser in our code base. we have a ton of JSON Schema and Open API files that could benefit from managing `$ref`s to other files. Would you consider this as a feature as its technically not JS code, but very adjacent.

### Expected Behavior

`$ref`s could be interpreted as `import`s or `require` calls. dc would be able to evaluate whether the ref is reasonably valid.

### Current Behavior

n/a

### Possible Solution

we have a lot of ref libraries that might be able to help.

### Considered alternatives

writing our own tool, but it would feel disjointed from dc.

**Comment by sverweij** [comment]
hi @daniel-white thank you for this suggestion.
