### ISSUE TITLE
[Question] Mark as orphan if imported from `__test__` dir.

### ISSUE THREAD

**Issue by RickCarlino** [sverweij/dependency-cruiser#70]
Greetings! Thanks so much for maintaining this great library- I really like it so far!

I have a question:

 * My [Typescript project](https://github.com/FarmBot/Farmbot-Web-App) places unit tests in a number of [\_\_tests\_\_ directories](https://github.com/FarmBot/Farmbot-Web-App/tree/staging/webpack/__tests__).
 * After large refactors, we sometimes end up with orphaned modules that don't  show up as orphans because they have unit tests.

Is there a way to mark a module as an orphan if it is only used in a path containing the word `__tests__`?

Example:

 * `foo.ts` exports `function bar() {}`
 * `__tests__/foo_test.ts` imports `bar` from `../foo.tx`
 * function `bar()` is an orphan, even though it is imported by `__tests__/foo_test.ts`

**Comment by sverweij** [comment]
Hi @RickCarlino - thanks for your interest in dependency-cruiser :-) 

The first thing that comes to mind is to exclude the `__tests__` directories entirely from being cruised. Maybe in a separate dependency-cruiser config (specific to orphan detection?), maybe in the overall one (depending how important the rules that _are_ on `__tests__` are)  or with a command line parameter (`--exclude "__tests__"` will exclude all directories in the tree called that way).

Another option could be to expand dependency-cruiser's _when to consider x an orphan_ logic. E.g. with the ability to disregard relations to or from other dependencies/ directories. Your example is a good one for this - but I'm also thinking of an 'orphaned' file that solely depends on node_modules (or node standard library modules). Both can be attained with _exclude_, but then again keeping just one .dependency-cruiser (/ one command to run all rules in one go) might be worthwhile ...

Let me know what would work best for your situation...

B.t.w. - I've checkout out your repo (side note: seriously cool product!) and set up dependency-cruiser for it to test the `exclude` suggestion out. Here's the `options` section of the `.dependency-cruiser.json` in case it might be helpful: 
```json
    "options": {
        "doNotFollow": "node_modules",
        "exclude" : "__tests__",
        "tsPreCompilationDeps": true,
        "tsConfig": {
            "fileName": "./tsconfig.json"
        },
        "webpackConfig": {
            "fileName": "./config/webpack.prod.js"
        }
    }
```
(If you want a hand with the setup let me know - I'd be glad to.)

**Comment by RickCarlino** [comment]
Thanks, @sverweij I will give it a look!
