### ISSUE TITLE
Issue: Dependency cruiser does not work with style preprocessors in Svelte

### ISSUE THREAD

**Issue by irvin93d** [sverweij/dependency-cruiser#713]
I am trying to use dependency cruiser to some projects that uses Svelte with Vite bundler. Some of them uses postcss and some uses scss. I only get dependency-cruiser to work if the style has no pre-processor. But when I add non-vanilla CSS syntax, dependency-cruiser seems to break.

### Expected Behavior

Dependency cruiser should run without errors.

### Current Behavior

Dependency cruiser throws `Identifier is expected` for any file where I use style preprocessors

### Possible Solution

I don't have any suggestion for fixes, but if this is just config issue I am happy to make a PR to update the docs :)!

### Steps to Reproduce (for bugs)

1. Set up a new Vite + TS + Svelte project
   ```
   $ npm init vite
   ✔ Project name: … vite-project
   ✔ Select a framework: › Svelte
   ✔ Select a variant: › TypeScript
   $ cd vite-project
   ```
2. Init dependency cruiser
   ```
   npm install --save-dev dependency-cruiser
   npx depcruise --init
   ✔ Where do your source files live? … src
   ✔ Do your test files live in a separate folder? … no
   ✔ Looks like you're using a 'tsconfig.json'. Use that? … yes
   ✔ Full path to your 'tsconfig.json › tsconfig.json
   ✔ Also regard TypeScript dependencies that exist only before compilation? … yes
   ``` 
3. Install sass:
   ```
   npm install sass
   ```
5. Add some styles to the sample component `Counter.svelte`
   ```
   <script lang="ts">
     let count: number = 0
     const increment = () => {
       count += 1
     }
   </script>

   <style lang="scss">
     button {
       background-color: blue;
       &:button {
         background-color: red;
       }
     }
   </style>

   <button on:click={increment}>
     count is {count}
   </button>
   ```

Now `npm run dev` and `npm run build` behaves correctly. However, dep-cruiser throws the following error:
```
$npx depcruise --config .dependency-cruiser.cjs src

  ERROR: Extracting dependencies ran afoul of...

  Identifier is expected
... in src/lib/Counter.svelte
```

### Context

I only breaks after I've added the non-vanilla CSS syntax:
```css
 &:button {
   background-color: red;
 }
```
If I use vanilla css, it seems to work fine.

### Your Environment

- Version used: 12.2.0
- Node version: v18.12.1
- Npm version: 8.19.2
- Operating System and version: Mac 12.6 (Monterey)

**Comment by sverweij** [comment]
Hi @irvin93d thanks for raising this issue; I'm looking at it. From a first investigation it looks like the svelte compiler (which dependency-cruiser uses under the hood) doesn't like the source very much and neither does the svelte online repl (see below) 

-> Does the example code work in the first place? If so - how is the svelte compiler (and/ or preprocessor) instructed to understand it?


```javascript
const svelteCompiler = require("svelte/compiler");

// 'script lang="ts" part translated to javascript for simplicity
const source = `<script lang="js">
  let count = 0
  const increment = () => {
    count += 1
  }
</script>

<style lang="scss">
  button {
    background-color: blue;
    &:button {
      background-color: red;
    }
  }
</style>

<button on:click={increment}>
  count is {count}
</button>`;

try {
  const abstractSyntaxTree = svelteCompiler.compile(source);
  console.dir(abstractSyntaxTree, {depth: 10})
} catch (e) {
  console.error(e);
}
```

Which yields

```
CompileError [ParseError]: Identifier is expected
    at error (/Users/jdoe/try-the-svelte/node_modules/svelte/compiler.js:16675:20)
    at Parser$1.error (/Users/jdoe/try-the-svelte/node_modules/svelte/compiler.js:16753:10)
    at Object.read_style [as read] (/Users/jdoe/try-the-svelte/node_modules/svelte/compiler.js:13325:21)
    at tag (/Users/jdoe/try-the-svelte/node_modules/svelte/compiler.js:15701:34)
    at new Parser$1 (/Users/jdoe/try-the-svelte/node_modules/svelte/compiler.js:16712:22)
    at parse$I (/Users/jdoe/try-the-svelte/node_modules/svelte/compiler.js:16844:21)
    at Object.compile (/Users/jdoe/try-the-svelte/node_modules/svelte/compiler.js:46605:18)
    at REPL27:2:45
    at Script.runInThisContext (node:vm:129:12)
    at REPLServer.defaultEval (node:repl:571:29) {
  code: 'css-syntax-error',
  start: { line: 11, column: 5, character: 157 },
  end: { line: 11, column: 5, character: 157 },
  pos: 157,
  filename: undefined,
  frame: ' 9:   button {\n' +
    '10:     background-color: blue;\n' +
    '11:     &:button {\n' +
    '         ^\n' +
    '12:       background-color: red;\n' +
    '13:     }'
}
```

On the svelte online REPL (https://svelte.dev/repl/) this yields the same error:

<img width="583" alt="Screenshot from the above code in the REPL" src="https://user-images.githubusercontent.com/4822597/209855119-0c11ad31-3cfa-4d1c-876c-71ce665ae910.png">

**Comment by irvin93d** [comment]
Thanks @sverweij !

> -> Does the example code work in the first place? If so - how is the svelte compiler (and/ or preprocessor) instructed to understand it?

My bad, I actually added an error to my code when I tried it again the second time from scratch. It yielded the same error, so I didn't notice.

The correct code:
```tsx
<script lang="ts">
  let count: number = 0;
  const increment = () => {
    count += 1;
  };
</script>

<button on:click={increment}>
  count is {count}
</button>

<style lang="scss">
  button {
    background-color: blue;
    &:active {
      background-color: red;
    }
  }
</style>
```

It would be equivalent to 

```
<style lang="scss">
  button {
    background-color: blue;
  }
  button:active {
    background-color: red;
  }
</style>
```
with vanilla css.

Yes, this works. But it requires a preprocessor (sass in this case) to work. Not sure if preprocessors can be added to REPL? I noticed that typescript doesn't seem to be supported on REPL either!

**Comment by sverweij** [comment]
hi @irvin93d 

Did a bit of digging in a vite setup and it's apparently magic'd away behind a svelte plugin for vite ([vite-plugin-svelte/packages/vite-plugin-svelte/src/preprocess.ts](https://github.com/sveltejs/vite-plugin-svelte/blob/main/packages/vite-plugin-svelte/src/preprocess.ts)) which supports no less than 8 types of css preprocessors (and a ts-to-js one). 

There's two routes dependency-cruiser can take here:
- support the svelte plugin ('preprocessor') mechanism 
This will be a bit involved but the most elegant of the two - if it can be pulled off.

- ignore tags/ languages it doesn't understand
This is the easiest and will at least fix this issue without loss of functionality (the css/ styling is ignored in dependency analysis a.t.m.).

I'll have a peek at the svelte processing code in dependency-cruiser to see if I can at least implement the latter.

**Comment by sverweij** [comment]
Hi @irvin93d I've just published `dependency-cruiser-12.3.0-beta-1` under the beta tag on npmjs (sha-sum: `9a483d3a723361375cf375097635d69f21c3cafe`) which should fix the issue. Can you confirm? If it does I'll release it as a regular version (likely v12.3.0) in the coming days.

> When you check the [ci result](https://github.com/sverweij/dependency-cruiser/actions/runs/3796540782) you'll see there's a small thing to iron out in the tests on the windows platform because of classic `\n`/ `\r\n` shenanigans - but the fix is functioning as expected.

**Comment by irvin93d** [comment]
@sverweij, tried it in a few different projects with different setups. Your fix did wonders 🚀

**Comment by sverweij** [comment]
Hi @irvin93d thanks for your feed back! I'll merge the PR and release it (probably in the weekend).

**Comment by sverweij** [comment]
Release 12.3.0 with the fix for this issue is up on npmjs since a few minutes.
