### ISSUE TITLE
Question: How to show full dep path when forbidden validate

### ISSUE THREAD

**Issue by JerryLyu93** [sverweij/dependency-cruiser#718]
### Summary

When I wrote a forbidden rule and get a validate result, i can see what file direct import the issue module，but how to check the whole dep chain for this issue module?  Because I must know what file(in /src/) indirect import the issue module.

![image](https://user-images.githubusercontent.com/14296911/210523721-1c1df8a5-6e41-45d1-962e-b88bad9e59b3.png)

Any suggestions would help, thanks!

### Context

None

### Environment

- Version used: unnecessary
- Node version: unnecessary
- Operating System and version: unnecessary
- Link to your project: unnecessary

**Comment by sverweij** [comment]
Hi @JerryLyu93 you're looking for a rule that no only checks whether a module in `src` does not (directly) depends on `@seiue/ui` but one that also checks whether modules depend on it _via via_.

You can do that by adding a [reachable](https://github.com/sverweij/dependency-cruiser/blob/develop/doc/rules-reference.md#reachable---detecting-dead-wood-and-transient-dependencies) attribute to the rule. The default reporter (as well as most others) will print (one of) the complete path(s).

Example

Say, you hypothetically wanted to prevent the `cli` modules from reaching the `cache` modules. In that case you'd write:

```javascript
    //...
    {
      name: "cache-not-reachable-from-cli",
      severity: "error",
      from: {
        path: "^src/cli"
      },
      to: {
        path: "^src/cache",
        reachable: true
      }
    },
    // ...
```

The default reporter will report violations in this fashion:

```
  error report-not-reachable-from-cli: src/cli/index.js → src/cache/utl.js
      src/cli/index.js →
      src/main/index.js →
      src/cache/cache.js →
      src/cache/utl.js
```

HTH

**Comment by JerryLyu93** [comment]
@sverweij Thanks a lot! It's helpful!!!

Then I get another question: 
In my project, a lot of issue { not-reachable } import come from typescript { import type from }, that would be detect by cruiser forbidden but in metro it would be fine.(because it just a type)

I try to set { dependencyTypesNot } to forbidden, but when I set forbidden:reachable, it seem like can not set any other property but  path.

Can I ignore type reachable? 

Any suggestions would help, thanks!

**Comment by sverweij** [comment]
Hi @JerryLyu93 yep - _reachable_ and other properties than _path_  and _pathNot_ indeed not be  combined (yet). I _do_ intend to expand this with other attributes at some time (and  because of your question the  _type_ of the relation will likely be a  first candidate for it) - but to be  honest I can't  promise  a  timeline  for  it.
