### ISSUE TITLE
`pnpx depcruise --init` doesn't work

### ISSUE THREAD

**Issue by mikib0** [sverweij/dependency-cruiser#725]
### Summary

I noticed that the command used in the README to run `dependency-cruiser` is incorrect. The command `npx depcruise [args]` doesn't work, the command that worked for me is `npx dependency-cruiser [args]`

### Context

I ran into this issue when I was trying install  `dependency-cruiser` using pnpm to analyze my project's dependencies. The command listed in the README, `npx depcruise [args]` (which in my case would be `pnpx depcruise [args]` ), did not work, and I had to use `pnpx dependency-cruiser [args]`.

### Environment

- Version used: ^12.4.0
- Node version: v16.13.0
- Operating System and version: Ubuntu 20.04 LTS

**Comment by sverweij** [comment]
Hi @mikib0 thanks for the feedback! You're right - if dependency-cruiser isn't installed yet in a (preferably local) `node_modules` folder `npx depcruise` won't work, but `npx dependency-cruiser` will. I'll see if I can make this more obvious in the README. 

B.t.w. I do recommend installing dependency-cruiser locally in any case (also see the [FAQ entry](https://github.com/sverweij/dependency-cruiser/blob/v12.5.0/doc/faq.md#q-should-i-run-dependency-cruiser-as-a-global-install-with-npx-or-as-as-local-development-dependency))

**Comment by mikib0** [comment]
Thanks for the quick response @sverweij. I think there is really nothing unclear in the guide provided in the README. Because following the guide,  I had dependency-cruiser installed locally before I ran `pnpx depcruise`. I found that pnpx doesn't run binaries of installed dependencies. It ONLY tries to fetch the package and then execute the default binary it exposes. And so when I ran `pnpx depcruise` it threw out an error because there was no package named depcruise in the npm registry. The correct command would have been `pnpm exec depcruise` which does run a binary of a project's dependency. I think if there is anything to note in the README, it should be this and i can help with that.

**Comment by sverweij** [comment]
Hi @mikib0 I've added a footnote to the README outlining the use of running with alternatives to `npx` (`yarn` and `pnpx` are two I now know of) that should prevent next persons that come after us from bumping into this issue.

Thanks again for reporting!
