### ISSUE TITLE
GraphViz error: keep consoling %0 1

### ISSUE THREAD

**Issue by lqzerogg** [sverweij/dependency-cruiser#729]
### Expected Behavior
It should draw the svg successfully

### Current Behavior
keep consoling info below:

```bash
  %0 2
        %0 1
        %0 1
        %0 1
        %0 1
        %0 1
        %0 1
        %0 1
        %0 1
        %0 1
        %0 1
        %0 1
        %0 1
        %0 1
        %0 1
        %0 1
        %0 1
        %0 1
        %0 1
        %0 1
        %0 1
        %0 1
        %0 1
        %0 2
        %0 1
        %0 1
        %0 1
        %0 1
        %0 1
        %0 1
        %0 1
        %0 4
        %0 1
        %0 1
        %0 1
        %0 1
        %0 1
```

### Possible Solution
When I run command in a large project, this bug occurs. Maybe memory leaks?

### Steps to Reproduce (for bugs)

1. init steps: 
✔ Where do your source files live? … src
✔ Do your test files live in a separate folder? … yes
✔ Where do your test files live? … build
✔ Looks like you're using a 'tsconfig.json'. Use that? … yes
✔ Full path to your 'tsconfig.json › tsconfig.json
✔ Also regard TypeScript dependencies that exist only before compilation? … yes
  ✔ Successfully created '.dependency-cruiser.js'
2. options configurations:
```JSON
{
  options: {

    /* conditions specifying which files not to follow further when encountered:
       - path: a regular expression to match
       - dependencyTypes: see https://github.com/sverweij/dependency-cruiser/blob/master/doc/rules-reference.md#dependencytypes-and-dependencytypesnot
       for a complete list
    */
    doNotFollow: {
      path: 'node_modules'
    },
    "includeOnly": "^src/",
  }
}
```
3. run command line

npx dependency-cruise src -c .dependency-cruiser.js -T dot | dot -T svg > internal-dependency-graph.svg

### Context

just want to know how to get rid of this problem, or avoid of such problem

### Your Environment

- Version used: 12.5.0
- Node version: v18.12.1
- Operating System and version: macOS Monterey
- Link to your project:

**Comment by sverweij** [comment]
Hi @lqzerogg this has the same root cause (and workarounds) as #728 - the error message is from GraphViz dot, and the coping mechanism is typically to reduce the size/ abstraction level of the graph.
