### ISSUE TITLE
Question: How to specify resolve alias in Vue.js 3/Vite project

### ISSUE THREAD

**Issue by bo-pedersen** [sverweij/dependency-cruiser#743]
### Summary
How do I specify a resolve alias in a Vue.js 3 project with Vite builder? An resolve alias is only described for a Webpack configuration.

### Context
I added Dependency Cruiser to an Vue.js 3 project with Vite. I can generate the graph but some of the dependencies are missing. Running the rules checks gives a bunch of errors like:
`  error not-to-unresolvable: src/scripts/utils.ts → @/components/Alert`

The culprit here is the @ alias defined in vite.config.ts. 
`  resolve: { alias: { '@': fileURLToPath(new URL('./src', import.meta.url)) } },`
Changing the imports using the @ alias to relative paths gives the expected dependencies.

I tried to add a dummy webpack.config.js with a resolve alias and use that in the Dependency Cruiser configuration, but was only able to get the following error:
`  ERROR: The supplied configuration is not valid: data/options/webpackConfig must NOT have additional properties.`

Is it possible to configure the @ alias in a Vite project?

### Environment

NPM: 9.2.0
├── dependency-cruiser@12.7.0
├── typescript@4.9.5
├── vite-plugin-vuetify@1.0.2
├── vite@3.2.5
├── vue-router@4.1.6
├── vue-tsc@1.0.24
├── vue@3.2.47
Windows 10

**Comment by sverweij** [comment]
Hi @bo-pedersen thanks for your question! Currently dependency-cruiser doesn't have explicit support for vite (or parcel, which it seems to be using under the hood). I wasn't aware vite/ parcel _also_ took a stab on aliasses, on top what is already available in e.g. jsconfig/ tsconfig. A complicating factor for supporting this in dependency-cruiser is that vite uses ES modules _for configuration_, which means we'll need some advanced trickery to read them.

I'll have a closer look at vite in the near future.

In the mean time - dependency-cruiser _does_ understand path aliases. The TypeScript ([tsconfig.json](https://www.typescriptlang.org/tsconfig#paths)), JavaScript (jsconfig.json - same format) and webpack ones can be passed dependency-cruiser without modifications. Example config:


```tsconfig.json
{
  "compilerOptions: {
    // ...
    // other options omitted for brevity
    // ...
    "baseUrl": "./",
    "paths": {
      "@*": ["src*"] 
    }
  }
}
```

```.dependency-cruiser.cjs
{
  // rules: [], 
  options: {
    tsConfig: { fileName: "./tsconfig.json" }
  }
}
```

**Comment by bo-pedersen** [comment]
Great, thank you for the pointer to tsconfig.json. My tsconfig.json actually sets the path alias, but in a referenced configuration file. This is part of the standard setup generated by the CLI project initialisation.
```
// tsconfig.json
{
  "files": [],
  "references": [
    {
      "path": "./tsconfig.vite-config.json"
    },
    {
      "path": "./tsconfig.app.json"
    },
    {
      "path": "./tsconfig.vitest.json"
    }
  ]
}
```

The tsconfig.app.json contains the path alias:
```
// tsconfig.app.json
 "compilerOptions": {
    // ...
    "baseUrl": ".",
    "paths": { "@/*": ["./src/*"] }, 
    // ...
  }
```

Moving this definition to the main tsconfig.json enables dependency-cruiser to resolve the dependencies. I suppose, dependency-cruiser doesn't follow these references.

I then have one dependency error from a shims:
```
  error not-to-unresolvable: src/shims.d.ts → vite/client
```
```
// shims.d.ts
/// <reference types="vite/client" />
```

The vite module is in node_modules and contains a client.d.ts file. I excluded vite/client in .dependency-cruiser.js. As all other references to node_modules are not followed, there might be a problem with these type references.

Thanks again for the help, very much appreciated.

**Comment by bo-pedersen** [comment]
Instead of moving the compilerOptions to the outer tsconfig.app, a better solution is to specify tsconfig.app.json in .dependency-cruiser.js.
