### ISSUE TITLE
Question: rule to enforce module encapsulation

### ISSUE THREAD

**Issue by jrnail23** [sverweij/dependency-cruiser#75]
### Expected Behavior

I'd like to create a rule that would warn when a module imports/requires something directly from another folder that isn't exported in that folder's `index.js`/`index.ts` file.

**Comment by sverweij** [comment]
hi @jrnail23 thanks for raising this question. 

I'll try to come up with a sample over the weekend - it's this type of rules I wrote dependency-cruiser for, so it should totally be possible.

**Comment by sverweij** [comment]
@jrnail23 - if understand correctly you want this:

- modules other than `index.js` can only depend on modules called `index.js` ...
- (except when they're modules from npm or core modules)
- modules can depend on any module in their own folder

The way I found is to use translate it 1:1 into the `allowed` rule in .dependency-cruiser.json:
```json
{
  "allowed": [
    {
      "from": {},
      "to": {
        "path": "index\\.js$"
      }
    },
    {
      "from": {},
      "to": {
        "dependencyTypes": [
          "npm",
          "core"
        ]
      }
    },
    {
      "from": {
        "path": "(.+)/[^/]+\\.js$"
      },
      "to": {
        "path": "$1/[^/]+\\.js$"
      }
    }
  ],
  "allowedSeverity": "warn",
  "options": {
    "doNotFollow": "node_modules"
  }
}
```

> If you're using typescript replace the `.js` with `.ts` - if both with `(.js|.ts)`

I ran it against a sample repo ([issue-75-sample-package.zip](https://github.com/sverweij/dependency-cruiser/files/2635707/issue-75-sample-package.zip)), which gave me:


<img width="534" alt="sample" src="https://user-images.githubusercontent.com/4822597/49325471-29efde80-f543-11e8-8fdb-f602039c71ef.png">

=> Was this what you were looking for?

**Comment by jrnail23** [comment]
@sverweij, this looks like exactly what I wanted!  I'll take it for a spin and let you know how it works.
Thanks for this!
