### ISSUE TITLE
Issue: npm ERR! 404 Not Found - GET https://registry.npmjs.org/depcruise - Not found

### ISSUE THREAD

**Issue by jezmck** [sverweij/dependency-cruiser#753]
I attempted to run `npx depcruise --init`, but got the above error.

Is this a node version issue?
For this project I have to be using node v14.

- Version used: 12.10.0
- Node version: 14.21.2
- Operating System and version: macOS 13.2.1

**Comment by sverweij** [comment]
Hi @jezmck `npx depcruise` will only work when dependency-cruiser is installed, so if you `npm install dependency-cruiser` before running `npx depcruise` it should work.

(If you used a different package  manager like yarn or pnpm to install dependency-cruiser the run command might differ a bit; your package manager's documentation should have documentation about  it).
