### ISSUE TITLE
Feature request: show core modules when using `includeOnly`

### ISSUE THREAD

**Issue by connorjs** [sverweij/dependency-cruiser#758]
Add a `protocols` field to the `includeOnly` (`IIncludeOnlyType`) option.

This would allow including specific dependency protocols (e.g. `node:`). It could be used in `exclude` (`IExcludeType`) too for the opposite use cases that I assume could exist.

### Context

Goal: Generate dependency diagrams. _My motivation is purely on reports, not validation._

I am tinkering with dependency cruiser to generate dependency diagrams. Right now, I generate diagrams with all of my code, plus `node_modules` dependencies (`foo` and `@bar/baz` variants). I realized that my diagrams did not include Node.js built in modules (`http`, `fs`, etc).

Requirement: I am using `includeOnly`, which leads to these Node.js modules disappearing. I need to show them again.

I do not have much context on other protocols, but could see other utility (`https` for deno, or I saw some mention of `virtual:`) today or in the future of the ecosystem.

### Expected Behavior

I expect dependency cruiser to provide a "recipe" to easily match Node.js built-in modules, similar to `node_modules` dependencies, so that I can use `includeOnly` and _not_ lose build-in modules.

### Current Behavior

I do not know how to use `includeOnly` and keep built-in Node.js modules without enumerating them by hand (error-prone).

### Possible Solution

I propose `protocols` as a solution to this problem because I noticed the JSON results already have `protocol`, so I figured it may be “simply” (😉) wiring up some pattern logic with existing data model and new config keys.

Current

```ts
export interface IIncludeOnlyType {
  /**
   * regular expression describing which dependencies the function
   * should cruise - anything not matching this will be skipped
   */
  path?: string | string[];
}
```

Proposed

```ts
export interface IIncludeOnlyType {
  /**
   * regular expression describing which dependencies the function
   * should cruise - matched by path (name) - anything not matching
   * this (or other include options) will be skipped
   */
  path?: string | string[];

  /**
   * regular expression describing which dependencies the function
   * should cruise - matched by protocol - anything not matching
   * this (or other include options) will be skipped
   * 
   * Include `""` (empty string) to match dependencies without
   * protocols (e.g. `foo` or `./bar`). For example, passing
   * `["node:"]` would exclude `foo` and `./bar`, while passing
   * `["", "node:"]` would include them.
   * 
   */
  protocols?: string | string[];
}
```

_Note: While writing the proposal, I realized we have to decide how the "no protocol" case interacts with this feature. I could (hypothetically) see a use case to ONLY match `node:` packages (or some other protocol), so we probably want to handle that. I tentatively proposed `""` (empty string), but do not know the specifics of the regex matching. Feel free to propose other handling here!_

### Considered alternatives

N/A - But happy to hear ideas or existing solutions

**Comment by connorjs** [comment]
I renamed the issue after re-reading <https://github.com/sverweij/dependency-cruiser/blob/develop/doc/rules-reference.md#dependencytypes-and-dependencytypesnot>. Using `core` dependency type would work for me too. The crux of the request is, "still show core modules when using include only," which I cannot figure out how to do right now.

**Comment by sverweij** [comment]
Hi @connorjs includeOnly currently indeed only supports matching strings to (resolved) module names. Something that'll work right now is to play on the property that nodejs modules resolve to a unique pattern. E.g. if you want to match everything under the `src` folder + all node core modules (but none of what is in node_modules), something to this tune should work:

```javascript
// ...
  includeOnly: {
    path: [
      "^src/",
      "^[a-z/_0-9]+$" // matches e.g. fs, os, but also path/win32, worker_threads
    ]
  }
// ...
```


- That said, a more conceptually obvious way (like `protocol` or `dependencyTypes`) to do this would certainly be better. It will require some thought, though. `protocol` and `dependencyTypes` are properties of the dependency, not of the module. And because includeOnly (currently) works on properties of the module...
- Adding the usage pattern above as a recipe is a good suggestion, I'll do that.
