### ISSUE TITLE
Documentation: --config parameter is needed or no violations are found

### ISSUE THREAD

**Issue by indy5858** [sverweij/dependency-cruiser#798]
The documentation on the default branch (develop) currently says that
`npx depcruise src`
will trigger a scan. However, leaving out the `--config .dependency-cruiser.js` option does not work. It results in no violations being reported.

### Possible Solution

- Either make sure that the default `.dependency-cruiser.js` works without additional configuration parameter
- Or update the docs to include the parameter `--config .dependency-cruiser.js`

### Context

It took quite a while to figure out, why dependency-cruiser was not reporting any violations, albeit having processed all the modules. People trying out dependency-cruiser will probably stumble upon this (given they have the same environment as me) and not continue working with the tool.

### Your Environment

- Version used: 12.11.3
- Node version: v16.13.2
- Operating System and version: Windows 10
- Link to your project: N.A.

**Comment by sverweij** [comment]
Hi @indy5858 thanks for taking the time to investigate and to raise this issue!

In version 13 ([currently in beta](https://github.com/sverweij/dependency-cruiser/issues/794)) the --config parameter isn't needed anymore, unless you want to use an alternative name or location for the configuration. In v12 (latest stable) you indeed still need to pass it.

I'll make updates to the README to prevent future users from bumping into this.
