### ISSUE TITLE
exclude patterns exclude more than expected

### ISSUE THREAD

**Issue by sverweij** [sverweij/dependency-cruiser#80]
### Expected Behavior
passing an exclude pattern only exludes modules matching that pattern

### Current Behavior
orphans (and maybe other modules?) don't show up in the output

### Steps to Reproduce (for bugs)
```sh
depcruise -T dot src | dot -T png -Gdpi=192 > fixture.png
```
result:
![fixture](https://user-images.githubusercontent.com/4822597/49599546-97f03780-f981-11e8-8728-ce7e31c629c3.png)

Adding an exclude parameter e.g. like this
```sh
depcruise --exclude "^[a-z]+$" -T dot src | dot -T png -Gdpi=192 > less
.png
```
yields not only the exclusion of `/^[a-z]+$/`, but also of the orphans that are left after excluding:
![less](https://user-images.githubusercontent.com/4822597/49599694-ec93b280-f981-11e8-95d3-00053682a91f.png)

### Context
see #61 

### Your Environment
* Version used: 4.7.0
* Node version: 10
* Operating System and version: NR

**Comment by sverweij** [comment]
@OlegAlexander as you can see above I'm working on it . There is a beta version on npm that includes a fix - you can already try it out if you're on linux or OSX/macOS (dependency-cruiser@4.7.1-beta-0 - later betas & 4.7.1 will also work correctly on ms windows).

**Comment by OlegAlexander** [comment]
I have tested dependency-cruiser@4.7.1-beta-0 on Windows 10 and can confirm that it's doing the right thing now. Thank you so much for fixing this issue so quickly!
