### ISSUE TITLE
Question: Does resolving absolute paths with TypeScript work out of the box?

### ISSUE THREAD

**Issue by smikheiev** [sverweij/dependency-cruiser#808]
`cruiser` fails with the error `not-to-unresolvable` when using absolute paths with TypeScript. From what I saw, it should work out of the box, so I wonder if I am missing anything 🤔 

This is a simple sandbox example to reproduce it: https://codesandbox.io/p/sandbox/boring-aj-qmbp8f?file=%2Ftsconfig.json%3A20%2C33

It's a small TS project with `index.ts` and two dependencies - `featA` and `featB` in `features` folder.
`baseUrl` is set to `./` in `tsconfig`.
`featA` and `featB` are imported with absolute paths (`import ... from "features/featA"`).
running `cruiser` with `depcruise --config .dependency-cruiser.js .` fails with errors
```
error not-to-unresolvable: index.ts → features/featB
error not-to-unresolvable: index.ts → features/featA
```
if to use relative paths for imports (`import ... from "./features/featA"`) then `cruiser` passes.

**Comment by sverweij** [comment]
Hi @smikheiev thanks for this issue & the sandbox, that makes things easier to troubleshoot & explain!

And yes, this works out of the box - provided dependency-cruiser is told to use the TypeScript configuration - adding an `options.tsConfig` to `.dependency-cruiser.js` should get you set.


- you might want to run the `--init` option to scaffold your .dependency-cruiser.js - it detects any tsconfig.json (/ babel/ webpack/ ...) configurations and automatically add them to .dependency-cruiser.js
- I've [forked the sandbox](https://codesandbox.io/p/sandbox/clever-pike-sz2yw9?file=%2F.dependency-cruiser.js%3A6%2C33) and made some minimal updates to `.dependency-cruiser.js` to make it work as you'd expect it.

**Comment by smikheiev** [comment]
thanks @sverweij! now I see what I was doing wrong 🙈 

I run `--init` option and checked the generated config file, but wanted to start from scratch to learn better how the tool works. I was trying to add `tsConfig` option to the config file too, but I think I missed that it's a part of `options` 🤦🏻 

thanks for the fast reply and for helping to figure this out!
