### ISSUE TITLE
Question: Could it draw changes dependencies graph

### ISSUE THREAD

**Issue by WangChloe** [sverweij/dependency-cruiser#816]
### Summary
Could it draw changes dependencies graph?

### Context

There's a feature we want: draw a dependency graph when we commit everytime, the graph only related to the commit row changes. 
In this way, we can clearly know the impact of this change and solve the problem of testing black boxes

At present, what we see is related to the specified file, how to associate with each submission, and accurate to each line.

Thanks

**Comment by sverweij** [comment]
Hi @WangChloe thanks for your question. And yes, it is possible to use dependency-cruiser to emit a graph that gives some overview for e.g. a pull request, a single commit, or a comparison between branches. And there's so many possibilities!

To facilitate this I wrote `watskeburt` - a tiny module that emits all changed modules between two 'revisions' as a single regular expression. Most of dependency-cruiser's command line parameters that act as filters can use that regular expression directly.


In a branch on dependency-cruiser I'm currently working on `watskeburt` gives this as an output:
```shell
$ npx watskeburt main
# ^(package\.json|src/cli/listeners/performance-log/format-helpers\.mjs|src/extract/get-dependencies\.mjs|src/extract/index\.mjs|src/extract/parse/to-javascript-ast\.mjs|src/extract/parse/to-typescript-ast\.mjs|src/extract/transpile/index\.mjs|src/main/cruise\.mjs|test/extract/ast-extractors/extract-amd-deps\.spec\.mjs|test/extract/ast-extractors/extract-cjs-deps\.spec\.mjs|test/extract/ast-extractors/extract-es6-deps\.spec\.mjs|test/extract/ast-extractors/extract-typescript-commonjs\.spec\.mjs|test/extract/ast-extractors/extract-typescript-dynamic-imports\.spec\.mjs|test/extract/ast-extractors/extract-typescript-exotics\.spec\.mjs|test/extract/ast-extractors/extract-typescript-exports\.spec\.mjs|test/extract/ast-extractors/extract-typescript-imports\.spec\.mjs|test/extract/ast-extractors/extract-typescript-triple-slash-directives\.spec\.mjs|test/extract/ast-extractors/extract-typescript-type-imports-and-exports\.spec\.mjs|test/extract/ast-extractors/extract-typescript\.utl\.mjs|test/extract/get-dependencies\.amd\.spec\.mjs|test/extract/get-dependencies\.cjs\.spec\.mjs|test/extract/get-dependencies\.odds-and-ends\.spec\.mjs|test/extract/index\.cachebusting\.spec\.mjs|test/extract/index\.donotfollow\.spec\.mjs|test/extract/index\.exclude\.spec\.mjs|test/extract/index\.maxdepth\.spec\.mjs|test/extract/parse/to-javascript-ast\.spec\.mjs|test/extract/run-get-dependencies-fixture\.utl\.mjs|test/extract/transpile/index\.spec\.mjs)$
```

A few ways you can use this below. Hope this helps!


### Only show the changed modules

```shell
depcruise src --include-only "$(npx watskeburt)" --output-type dot | dot -T svg > graph.svg
```

![include-only](https://github.com/sverweij/dependency-cruiser/assets/4822597/eeb45e34-49e0-4d10-a549-5b012b6ba378)



### Show the complete graph, but with the changed modules highlighted

```shell
depcruise src --highlight "$(npx watskeburt)" --output-type dot | dot -T svg > graph.svg
```

<details>

<summary>expand to see the relatively large complete graph</summary>

![everything](https://github.com/sverweij/dependency-cruiser/assets/4822597/f6f4893e-578e-42b5-bbdb-20e50598f64f)

</details>

### Show the changed modules & their direct surroundings ('focus')

```shell
depcruise src --focus "$(npx watskeburt)" --highlight "$(npx watskeburt)" --output-type dot | dot -T svg > graph.svg
```

<details>

<summary>expand to see the relatively large 'focus' graph</summary>

![focus](https://github.com/sverweij/dependency-cruiser/assets/4822597/6e60bf7a-2e35-420b-8f19-dcac88900406)

</details>

### Show  the changed modules & all modules that can reach them (directly or indirectly; 'reaches')

```shell
depcruise src --reaches "$(npx watskeburt)" --highlight "$(npx watskeburt)" --output-type dot | dot -T svg > graph.svg
```

![reaches](https://github.com/sverweij/dependency-cruiser/assets/4822597/31f09cbf-276e-4331-b475-9d6b14ced42f)

**Comment by WangChloe** [comment]
Thanks for your patience.

There is still a problem, here is still the perspective of the whole 'file', whether it is possible to trace the dependency tree from the perspective of 'function'.

Looking forward to your reply~

**Comment by sverweij** [comment]
Hi @WangChloe dependency-cruiser targets dependencies between modules (or 'files'). A finer granularity (classes, functions, variables, constants, ...) is not part of its scope.

You're not the first to ask :-) . The finer granularity would definitely be interesting as well - but it's also _a lot_ of work to do well. Because the time I have is limited I've chosen to focus dependency-cruiser on module dependencies only and make it does a good job there well.
