### ISSUE TITLE
Issue: Dependency Update of watskeburt package introduces new engine requirement

### ISSUE THREAD

**Issue by FrecksterGIT** [sverweij/dependency-cruiser#817]
yarn install breaks for node versions which should be supported:

the updated watskeburt dependency requires node ^16.19||^18.11||>=20, while this package requires ^16.14||>=18.

### Expected Behavior

installation should work as expected for supported node versions.

### Current Behavior

yarn install fails if running on incorrect version of node.

error watskeburt@0.11.3: The engine "node" is incompatible with this module. Expected version "^16.19||^18.11||>=20". Got "18.4.0"

### Possible Solution

Either replace watskeburt or change required node versions for dependency-cruiser.

### Steps to Reproduce (for bugs)

try yarn install on node >=16.14 and <16.19 or >=18 and <18.11

**Comment by sverweij** [comment]
Hi @FrecksterGIT good point - thanks for raising this. Fix is coming up. 

The ^16.19 and ^18.11 in watskeburt are only necessary for its CLI. The watskeburt _library_ is probably  backwards compatible to node 14.

Out of curiosity: what is the reason you've bumped into (or even use?) an environment that isn't on the latest version of node 16 or 18?

**Comment by sverweij** [comment]
Hi again @FrecksterGIT - this issue is resolved in dependency-cruiser@13.0.4, which has been published a few minutes ago [to npmjs](https://www.npmjs.com/package/dependency-cruiser/v/13.0.4)
