### ISSUE TITLE
Question: Is it possible to collapse on dynamic import boundary?

### ISSUE THREAD

**Issue by tnightingale** [sverweij/dependency-cruiser#824]
### Summary

Is it possible to configure the collapse rules to collapse the children of dynamic imports (I would like to see the dynamically imported module but ideally it's children would be collapsed)?

### Context

We are trying to optimize our application's code-splitting/chunking and depcruiser is very useful to visualize some of the patterns that are inhibiting this (barrel files, circular imports, etc) but currently the graph is very noisy. Dynamic imports are a natural "seam" for isolating individual branches of the graph (and they correspond nicely to the resulting chunk/bundle files).

To take it a step further, I could imagine the `archi` reporter providing the ability to click-through/expand a particular dynamic import's sub-tree.

**Comment by sverweij** [comment]
Hi @tnightingale thanks for your question - and its context!

At this time it's only possible to 'collapse' based on (file) name patterns. I think it's a good idea to add something based on whether a dependency is dynamic, though! To take it one step further it maybe should make its way into the [doNotFollow]() and/ or [exclude]() filters as well. 

A more interactive graphical representation (where you can collapse/ expand to your heart's content) is on my wish-list as well.

**Comment by tnightingale** [comment]
Thanks for the clarification! I had figured as much, and yeah, after closely reading through the documentation I figured surfacing the dynamic attribute in the exclude rules would be a logical place to start. Perhaps I can carve out some time to make a contribution :)
