### ISSUE TITLE
Question: zsh: command not found: depcruise-wrap-stream-in-html

### ISSUE THREAD

**Issue by rickvian** [sverweij/dependency-cruiser#835]
### Summary
i cannot generate as html, i got this error 
zsh: command not found: depcruise-wrap-stream-in-html

### Context

i can generate SVG file, fine,

but when i try with this command:
depcruise -v -T dot src | dot -T svg | depcruise-wrap-stream-in-html > dependency-graph.html

i got error 
`zsh: command not found: depcruise-wrap-stream-in-html`

do i need to configure anything?

### Environment

- Version used: 13.1.5
- Node version: v16.18.1, 
- Operating System and version: MacOS, m2, 
- Link to your project:

**Comment by rickvian** [comment]
found the answer

turns out i need to add NPX behind the depcruise-wrap-stream-in-html

`npx depcruise -v -T dot src | dot -T svg | npx depcruise-wrap-stream-in-html > dependency-graph.html`

**Comment by busla** [comment]
the above threw an error but this worked

```bash
yarn depcruise src --output-type dot | dot -T svg | npx depcruise-wrap-stream-in-html > depgraph.html
```
