### ISSUE TITLE
Question: How to change edges pendwidth?

### ISSUE THREAD

**Issue by rickvian** [sverweij/dependency-cruiser#836]
we can change the pendwith of node border,
but how to do that for edge?

**Comment by sverweij** [comment]
Hi @rickvian that's possible with the same mechanism as setting node borders (like you probably found in [the options reference](https://github.com/sverweij/dependency-cruiser/blob/main/doc/options-reference.md#theme-dot-ddot-and-archi-reporters)) e.g.





```javascript
module.exports = {
  // ...
  options: {
    reporterOptions: {
      dot: {
        theme: {
          graph: {
            // ...
          },
          node: {
            // ...
            penwidth: "2.0",
            // ...
          },
          edge: {
            // ...
            penwidth: "2.0",
            // ...
          },
          modules: [
            // ...
          ],
          dependencies: [
            // ...
          ],
        },
      },
    },
  },
};
```

- For more examples see the [theming examples](https://github.com/sverweij/dependency-cruiser/blob/main/doc/options-reference.md#theming-examples) in the options reference
- You can use  all graph, node and edge attributes GraphViz supports (see [their official documentation](https://graphviz.org/doc/info/attrs.html))
