### ISSUE TITLE
Question: How to resolve ES Modules (package.json 'module' field instead of 'main')

### ISSUE THREAD

**Issue by JakeSidSmith** [sverweij/dependency-cruiser#843]
It doesn't appear (though correct me if there's an option I've missed) that this package will resolve to ES modules for packages that define a `module` in their package.json, even when the source files are also of `type: module`

### Context

I am creating a tool that builds to ES modules for use in the browser (no bundling). As part of this I need to copy node modules into a public directory (and convert them where only commonjs modules are available). The way many modules are exported does not allow for me to easily convert them from commonjs to esm, however those problematic modules all appear to provide ES modules as well, but dependency-cruiser only resolves to the problematic commonjs modules.

It would be ideal if there was an option to resolve to the ES modules where possible.

### Expected Behavior

Modules that provide a "module" should resolve to ES modules.

### Current Behavior

There is no option. Only commonjs modules are resolved.

### Possible Solution

An option to resolve to ES modules where possible, resulting in `dependency.resolved` pointing to an ES module (if this were defined in the package.json) instead of commonjs modules.

### Considered alternatives

Alternatively, an additional `resolvedEs` (or something) property containing the ES module in addition to the commonjs module may prove more useful.

Further note: very happy to have a look at implementing this myself if it's not something that's already possible.

**Comment by sverweij** [comment]
Hi @JakeSidSmith resolving ES modules should work out of the box without any configuration. If it doesn't work as such there's something interesting going on. Could you share an example (/  minimal reproduction setup) where the module resolution for ES modules isn't working as expected?

**Comment by JakeSidSmith** [comment]
It may very well be that I've misunderstood something, but here's a reasonably simple example with roughly the setup I have in my project: https://github.com/JakeSidSmith/dependency-cruiser-esm-example

Notes:
- The code that is running dependency-cruiser is compiled from typescript
- Included some augmented types as there were a couple of issues
- Tried with both node 18 and 20
- Have included both `type: module` and `.mjs` extensions

**Comment by JakeSidSmith** [comment]
Follow up: tried explicitly providing the input type with the same results.

```shell
cat build/index.mjs | node --input-type=module
```

**Comment by sverweij** [comment]
Hi @JakeSidSmith - thanks for the example, it helped finding quickly what is going on. TL;DR: by default dependency-cruiser uses the `main` field in  package.json, but it can be configured to use others, like `module` as well. At the moment this is still a (one time) configuration but I'll seek to make that automatic.

> I've created a PR on the minimal repro repo that shows a way to do this:
> https://github.com/JakeSidSmith/dependency-cruiser-esm-example/pull/1/files

Dependency-cruiser uses webpack's `enhanced-resolve` for module resolution. It works well and is hyper configurable, which is needed to support the ever growing wood of possibilities to resolve JavaScript modules to disk. For resolving what file to use in a node_modules package,  it looks at the `main` field by default. It _can_ look at other ones as well. For TypeScript the `types` and/ or `typings` fields can be aded. For ESM the `module` field. B.t.w. even within ESM there's multiple ways to specify what an entry point should be. `exports` fields seem to be the latest rage (and by default dependency-cruiser's `--init` scaffolded has configuration for that as well).

Of course, I'd rather this not be a thing you'd have to worry about so I'll find a way to prevent that for the future (first at least in the `--init` scaffolding, by peeking at `"type": "module"` and relatedd signs, and later likely by taking this into account dynamically), so thanks for raising this issue!

**Comment by JakeSidSmith** [comment]
Awesome. Just dropped that exact config into my project and it works a treat. 😁 

Thank you very much.

**Comment by JakeSidSmith** [comment]
@sverweij not totally related to this issue, but I have another question that I couldn't figure out from looking at the resolve options:

Is there a way to prioritize resolving modules to those in `node_modules` rather than core NodeJS modules e.g. https://www.npmjs.com/package/path is published separately for use in the browser, but I can't seem to get dep-cruiser to resolve to anything but the core path module.
