### ISSUE TITLE
Feature request: Remove top-level awaits

### ISSUE THREAD

**Issue by mrmckeb** [sverweij/dependency-cruiser#844]
### Context

We currently package a tool using `dependency-cruiser` as ESM and CJS, as one of our targets _requires_ CJS. Unfortunately, build tools like esbuild, can't process top-level awaits when targeting CJS.

Example issue:
https://github.com/evanw/esbuild/issues/253

As of v13/14 we are unable to build for that target.

If this feature/change request is approved, I'm happy to do the work.

### Expected Behavior

Top-level awaits are removed in favour of async functions.

### Current Behavior

The top-level awaits prevent esbuild from building to CJS targets.

### Possible Solution

Instead of top-level await, the calling functions could be async.

For example, taking this simplified version of `extract/transpile/babel-wrap.mjs`:
```ts
import tryImport from "semver-try-require";
import meta from "../../meta.js";

// const babel = await tryImport("@babel/core", meta.supportedTranspilers.babel);
let babel;
const getBabel = async () => {
  babel = await tryImport("@babel/core", meta.supportedTranspilers.babel);
};

export default {
  // isAvailable: () => babel !== false,
  isAvailable: async () => (await getBabel()) !== false,
  transpile: (pSource, pFileName, pTranspileOptions = {}) =>
    babel.transformSync(pSource, {
      /* ... */
    }).code,
};
```

### Considered alternatives

We can use pnpm patch to remove these ourselves, but it's a little cumbersome.

**Comment by sverweij** [comment]
Hi @mrmckeb one of the reasons dependency-cruiser is now an ESM package is so it can use reasonably modern javascript features like top level awaits. Top level awaits have been in nodejs for more than 3 years now according to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await#browser_compatibility), so I'm not a fan of downgrading to older constructs.

Although I understand the intricacies of translating modern features to legacy commonjs, it's a pity esbuild after all this time still doesn't support it fully yet. 

Why does one of your targets require commonjs? (and what is the tool you're packaging?)

**Comment by mrmckeb** [comment]
Hi @sverweij. Part of our code ends up in a closed-source VS Code extension, and VS Code extensions need to be CJS. There are a number of issues around this, and it looks like it'll require updates to Electron (which I think just shipped), and then updates and refactors within VS Code to support ESM - so TLDR; it's probably going to stay this way for a while.
https://github.com/microsoft/vscode/issues/130367

I'm 100% with you on the need for us (the community/ecosystem) to move on from CJS, and this my team have tried to find other solutions to this problem. There won't be any hard feelings if you don't want to make this change.
