### ISSUE TITLE
Question: can i override a node's prefix via criteria ?

### ISSUE THREAD

**Issue by CaptainQuirk** [sverweij/dependency-cruiser#852]
I would like to change the prefix or the href for specific nodes

### Summary

- I'm perfectly fine with how things work for code under version control and can add the URL to my gitlab instance in the configuration file under the `prefix` option BUT I would like to be able to link to node packages when the dependency type is npm

### Environment

- Version used: 14.1.1
- Node version: 18.17.0
- Operating System and version: alpine node
- Link to your project: <private>

**Comment by sverweij** [comment]
Hi @CaptainQuirk thanks for this suggestion. It's not possible (yet), but it makes a lot of sense. Likewise it would probably make more sense to link core to the node.js documentation.

I've made a (quick, very dirty, very non-configurable, not-yet-publishable) hack to gauge the possibilities - example output for the `dot` reporter (the hack works in other reporters as well) run against [virtual-code-owners](https://github.com/sverweij/virtual-code-owners):

https://sverweij.github.io/examples/dependency-cruiser/links-to-different-targets.html

- links npm (regular, dev, optional, peer, unknown) modules to `https://www.npmjs.com/package/${packageName}` 
- links node core modules to ~ `https://nodejs.org/api/${pModule.source}.html`

### Questions
-> Would this work for you? 
-> Would the hard coded URL prefixes for these be sufficient or would it need to be configurable?

**Comment by CaptainQuirk** [comment]
Hi !

Well, that's exactly what I had in mind !

There may be a need for dynamic URL prefixes though: for example, I'm wondering how it would work with custom npm package registries. Gitlab has them.
For those particular packages, what would you link to ? Probably the source code. But, maybe the source code of such a dependency is hosted on a different git service than the main project.
What do you think ?

**Comment by sverweij** [comment]
hmm yeah - configurable makes sense for alternative registries indeed (private or not). + they'll typically be mixed with the public packages from e.g. npmjs.

I thought to use fields from package.json (e.g. `repository`, `homepage`) but they're too inconsistent. they're not mandatory & nothing stops authors from filling out https://youtu.be/dQw4w9WgXcQ. Or worse.

I'll ponder some solutions to facilitate a split, but I guess as a first step having separate urls for core modules & npm modules would already be an improvement.

> The hover feature on this example is great by the way !

Merci :-) It's the result of a little postprocessing on the generated svg - the script to do that is packaged with dependency-cruiser - see [doc/cli.md#depcruise-wrap-stream-in-html](https://github.com/sverweij/dependency-cruiser/blob/main/doc/cli.md#depcruise-wrap-stream-in-html) if you also want to use it.

**Comment by CaptainQuirk** [comment]
I agree with the first step approach ! Having links to the npm registry and the built-in node js module is sufficient for my use cases so far !

**Comment by sverweij** [comment]
@CaptainQuirk the (slightly cleaned up version) of the feature that has separate urls for core & npm modules has been shipped as part dependency-cruiser@15.0.0.

**Comment by CaptainQuirk** [comment]
:+1:
