### ISSUE TITLE
Feature request: Allow to have rules checking Typescript types but also rules that ignore Typescript types

### ISSUE THREAD

**Issue by mx-bernhard** [sverweij/dependency-cruiser#899]
In our code base we want to prevent that Typescript types are used that are defined in package.json `devDependencies`. Setting `tsPreCompilationDeps` to `specify` does solve this. But now lots of circular dependencies are reported for Typescript `type` `import`s which are not an issue as they are carefully written so that Typescript does not trip over them. We would like to:

* prevent `devDependencies` from being used regardless whether they are types or values
* ignore Typescript types when detecting circular dependencies

Once `tsPreCompilationDeps` is enabled, there is no way for the entire dep-cruiser run to ignore Typescript types for specific rules, because both `preCompilationOnly: true` and `preCompilationOnly: false` take Typescript types into account. We are missing a third option, although `preCompilationOnly` would be a bad name for it.

We are considering executing dependency-cruiser twice for two different configs, but this would have the drawback of being slower.

**Comment by sverweij** [comment]
Hi @mx-bernhard you might want to look into using the `dependencyTypes` and `dependencyTypesNot` attributes in rules to denote exceptions for e.g. type-only  rules. E.g. to ensure type-only dependencies are not taken  into account in cycles you could use:

```
// log an error for all circular dependencies which consist of only 
// dependencies that are _not_ declared as explicitly type-only
{
  name: 'no-circular-at-runtime',
  severity: 'error',
  from: {
  },
  to: {
    circular: true,
    viaOnly: {
      // 'type-only - _explicitly_ declared as type only import
      dependencyTypesNot: ['type-only'],
      // if you use `preCompilationOnly: 'specify'` this will
      // also work, and exclude _everything_ that isn't relevant
      // at runtime
      // dependencyTypesNot: ['pre-compilation-only'],
    }
  }
},
```
>  Also see [the example on this in the rules reference](https://github.com/sverweij/dependency-cruiser/blob/main/doc/rules-reference.md#example-allow-cycles-that-have-a-type-only-dependency-in-them).

**Comment by mx-bernhard** [comment]
I started introducing dependency-cruiser two months ago and was still on the 15.3.0. I feel stupid not to check for updates. 15.x didn't have this option yet. That was the missing piece, thx! 😂
