### ISSUE TITLE
Question: A dependency view of each "TYPE" or "INTERFACE"

### ISSUE THREAD

**Issue by PorcoRosso85** [sverweij/dependency-cruiser#901]
### Summary

To visualize relations of each type | interface declaration.
like `&` `extends` `implements` and inside of child definition.

### Context

I think I maybe understand the concept of dependency-cruiser, but I dare to ask.
Can we  visualize relations of each type | interface declaration?
The reason why I ask because I believe that this library should be utilized more in the design phase, not just in the CI and testing phase.

If not available,
can we add info like `Jsdoc` in the top of each file to view?
For example,
I want add comment or doc on each file to exported one like yours: https://sverweij.github.io/dependency-cruiser/dependency-cruiser-dependency-graph.html

### Environment
any

#### p.s.
reference: https://github.com/demike/TsUML2

**Comment by sverweij** [comment]
Hi @PorcoRosso85 thanks for this suggestions!. 

The space of statically analyzing the contents of modules (including, but not limited to classes, types and interfaces) is very interesting. It's quite complex and time consuming to do though. This is why I've made the decision to focus on dependencies between modules only and to do that as well as possible. 

Regarding jsdoc comments: do you mean that each node in the graph either directly or on hover showed the contents of the jsdoc on top of the module it's associated with? It's an interesting idea. What would be in that jsdoc? (b.t.w. not promising anything - I'm not even sure the parsers dependency-cruiser currently use give access to comments in their output).

**Comment by PorcoRosso85** [comment]
@sverweij 

Thanks.
As you understood, 
What I expect is 'inside of file, especially for type and interface' dependency.
I now understand what you focus is 'btw dir/file and each other'

If depcruise will focus 'btw dir/file',
I was hoping that when I mouse over each file in your sample html, a description of that file by jsdoc would hover.
This is a conversation about the functionality of the output html style script rather than the functionality of depcruise, and is not a high priority, so no problem.
