### ISSUE TITLE
Question: monorepo, combinedDependencies & not-dev-dep

### ISSUE THREAD

**Issue by boneskull** [sverweij/dependency-cruiser#902]
The default `not-dev-dep` rule catches a devDep in the monorepo root which is _also_ defined as a dep in a workspace.  How to avoid?

### Summary

In my root `package.json`, I have:

```json
{
  "devDependencies": {
    "foo": "1.0.0"
  },
  "overrides": {
    "foo": "$foo"
  }
}
```

The reason for the devdep is so that I can use it in `overrides` in this manner; otherwise I'd omit it.  I could potentially hard-code the version in `overrides`, but that may have unintended consequences with other tooling (Renovate).

In `packages/floof/package.json`, I have:

```json
{
  "dependencies": {"foo": "1.0.0"}
}
```

`foo` is referenced "non-exotically" in the source for `packages/floof`.

Because, presumably, I have `combinedDependencies` enabled, the `not-dev-dep` rule fails, because `foo` is considered _both_ a devDep and a dep within the "combined" package manifest.

I looked into enabling `moreThanOneDependencyType`, but that seems like kind of a crude solution. It would presumably miss _any_ case where a workspace in `packages/` contains multiple dependency types, and I don't want that.

I could add `node_modules/foo` to the `to.pathNot` array, but this allows use of `foo` in `packages/floof` (or any other package) without it appearing in `dependencies` at all, which is not what I want.  `foo` is not e.g., a type-only package, and must be proper dependency of `floof`.

Could group matching help here?  What would be the smartest way to avoid this?  Do I need a new rule entirely?

Thank you!

### Context

In my PR linked below, `packages/floof` is `packages/webpack` and `foo` is `ses`.

### Environment

- Version used: 15.5.0
- Node version: 20.10.0
- Operating System and version: macOS Sonoma
- Link to your project: https://github.com/lavamoat/lavamoat/pull/820

**Comment by sverweij** [comment]
Hi @boneskull - one way to address this might be to expand the `dependencyTypesNot` condition in the `not-to-dev-dep` with a condition so if it appears as an `npm` (so prod) dependency as well it doesn't get flagged, like so:

```javascript
    {
      "name": "not-to-dev-dep",
      "severity": "error",
      "comment": "In production code do not depend on external ('npm') modules not declared in your package.json's dependencies - otherwise a production only install (i.e. 'npm ci') will break. If this rule triggers on something that's only used during development, adapt the 'from' of the rule in the dependency-cruiser configuration.",
      "from": {
        "pathNot": ["^test/", "^tools/"]
      },
      "to": {
        "dependencyTypes": ["npm-dev"],
        "exoticallyRequired": false,
        "dependencyTypesNot": [
          "type-only",                    // already in LavaMoat/LavaMoat#820 
          "type-import",                  // not sure whether in use, but maybe good to prevent future false positives as well
          "triple-slash-type-reference",  // kind of obscure, but these types of deps will also disappear at runtime
          "npm-peer",                     // already in LavaMoat/LavaMoat#820 
          "npm"                           // added to prevent deps that are both prod and dev
        ],
        "pathNot": ["node_modules/@types/"]
      }
    },
```

Would this work in the LavaMoat setup?

> I bet that in `packages/floof` the import (or require) to `foo` is resolving to `packages/floof/node_modules/foo/somethingsomething`, using entry in the `packages/floof/package.json`. A good future improvement for dependency-cruiser would be to get that precise as well.

**Comment by boneskull** [comment]
@sverweij Thank you for your help. It looks like what I needed was the `npm` in `dependencyTypesNot`.  Now, if I remove `ses` from e.g., `packages/webpack/package.json`, the rule fails, which is what I want.  

I still don't quite understand what `npm` implies here, but it looks like it works for my purposes.
