### ISSUE TITLE
What am I missing about rcdot? "'rcdot' is not a valid output type"

### ISSUE THREAD

**Issue by iftheshoefritz** [sverweij/dependency-cruiser#906]
### Summary

The rcdot output type seems like what I want for insights into my code, but I get this error when I try to use it:

```
yarn -s depcruise --include-only "^app" --exclude "test|mock|asset|icon" --focus "Checkout" --focus-depth 2 --output-type rcdot --ts-config ./tsconfig.json . | dot -T svg > graph.svg
ERROR: 'rcdot' is not a valid output type.
```

Do I have to install anything special to use `--output-type rcdot`?

Cheeky bonus issue: where can I find an explanation of what the different colours mean?

### Context

I'm a beginner at dependency-cruiser. I'm just running it on my project, and can see the potential. Hints in the docs about finding dead code etc seem like they could be useful.

### Environment

- Version used: 13.1.2 (I know it's old, I went to a random old version that would work with my version of node)
- Node version:  18.14.2
- Operating System and version: MacOS Ventura 13.6.4

**Comment by sverweij** [comment]
Hi @iftheshoefritz up to version 5 (~4.5 years ago) _rcdot_ was only an alias for the _dot_ reporter. So you can use `--output-type dot` in stead. 

I had to look that up in the git history as I had forgotten this even existed. Where did you find out about the rcdot reporter?

> where can I find an explanation of what the different colors mean?

It's not documented outside the source code. The default theme uses this, at the moment:
- By default the modules are colored by extension (e.g. typescript (.ts, .cts, .mts, .tsx)  - light blue, javascript  & json light yellow (.js, .cjs, .mjs, .jsx,  .json), vue green, and also svelte, livescript and coffeescript  have their own base colors). 
- Things in node_modules have a light red background.
- Orphans are a sickly (zombie) lightgreen.
- Modules that match [highlight](https://github.com/sverweij/dependency-cruiser/blob/main/doc/cli.md#--highlight-highlight-modules) are fluorescent green
- [consolidated/ collapsed](https://github.com/sverweij/dependency-cruiser/blob/main/doc/cli.md#--collapse-summarize-to-folder-depth-or-pattern) modules have a box3d shape
- modules that match [doNotFollow](https://github.com/sverweij/dependency-cruiser/blob/main/doc/options-reference.md#donotfollow-dont-cruise-modules-any-further) have a folder shpae
- lines (for dependencies) and outlines (for modules) are shades of black, unless there's a transgression, in which case they're red, orange or blue for respectively error, warning and info. 
- dependencies that are part of a circular relationship have a little circle at the 'to' side of the relationship.

Note to self: not a  bad idea to put this in the _theme_ section of the reporter options documentation.

The default [theme](https://github.com/sverweij/dependency-cruiser/blob/main/doc/options-reference.md#theme-dot-ddot-and-archi-reporters) is in [src/report/dot/default-theme.mjs](https://github.com/sverweij/dependency-cruiser/blob/main/src/report/dot/default-theme.mjs)

> Hints in the docs about finding dead code etc seem like they could be useful.

Agree. The documentation could use more practical patterns. There is a little  collection in the  [recipes section](https://github.com/sverweij/dependency-cruiser/blob/main/doc/rules-tutorial.md#recipes) of the  rules tutorial you might find  helpful already. 

> Version used: 13.1.2 (I know it's old, I went to a random old version that would work with my version of node)
The latest version (dependency-cruiser@16.1.0) is compatible with node ^18.17.0 - and that node version is backwards compatible to the version of node you're on. I do recommend using the latest version of dependency-cruiser as well of node (even if you stay on node 18, than the latest 18 (18.19 right now it looks)). Unless there's a very good reason to stay on the older node 18.14.2, that is ...
