### ISSUE TITLE
Q: Dep Graph for each file

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [sverweij/dependency-cruiser#911]
Is it possible to have an output for each file in the dependency graph if the dependency graph as a whole is to overwhelming? Or is it possible to stretch the graph that there is not so much overlap?
Or is there a way to make it more navigatable?

**Comment by sverweij** [comment]
Hi @sschneider-ihre-pvs [this FAQ entry might be of help](https://github.com/sverweij/dependency-cruiser/blob/main/doc/faq.md#q-the-graph-dependency-cruiser-generates-is-humongous-and-i-cant-follow-the-lines-very-well-what-can-i-do).

Not yet mentioned in that FAQ entry are other strategies:
- You can point dependency-cruiser at one file and let it cruise from there, with or without specifying 
- You can filter the graph to show modules and dependencies that only [reach](https://github.com/sverweij/dependency-cruiser/blob/main/doc/cli.md#--reaches-show-modules-and-their-transitive-dependents) modules
- You can [collapse](https://github.com/sverweij/dependency-cruiser/blob/main/doc/cli.md#--collapse-summarize-to-folder-depth-or-pattern) related modules together by  specifying a pattern.
- Dot's default graph layout is known to _work_ for sure, but it's not always the most beautiful or (for larger graphs) clean one. For  smaller  graphs you can switch on orthogonal routing (see the  comment in the .dependency-cruiser.js you generated  with `--init` for  how to get  that) which is _a lot_ cleaner.
- [depcruise-wrap-stream-in-html](https://github.com/sverweij/dependency-cruiser/blob/main/doc/cli.md#depcruise-wrap-stream-in-html) packaged with dependency-cruiser will make the graph a little more interactive.

See e.g. [this graph](https://sverweij.github.io/dependency-cruiser/assets/berry-high-level-dependencies.html) of  yarn, that combines a few of the above strategies - how that's done is described in [real-world-samples.md](https://github.com/sverweij/dependency-cruiser/blob/main/doc/real-world-samples.md#yarn-2-berry). 

Hope this helps!
