### ISSUE TITLE
Feature request: Allow type only imports to be omitted entirely from the dependency graph (typescript)

### ISSUE THREAD

**Issue by brocef** [sverweij/dependency-cruiser#943]
Type only imports are always included in the output graph, even if you mark them to not be followed via the `doNotFollow` option. It would be nice if there was either a way to exclude them entirely from the graph, or perhaps to filter them out via the dot output filters.

### Context

Typescript project

Trying to build a dependency graph of files which are _actually_ imported after transpilation to verify the exact runtime dependencies of certain files.

### Expected Behavior

n/a

### Current Behavior

n/a

### Possible Solution

I feel like an output filter is probably the easiest, since the output contains relevant information about the edge connecting two nodes in the graph.

### Considered alternatives

Filter the dot output manually via shell script then generate image

**Comment by sverweij** [comment]
Hi @brocef thanks for this suggestion!

It looks like your use case is a good fit to set the [tsPrecompilationDeps](https://github.com/sverweij/dependency-cruiser/blob/main/doc/options-reference.md#tsprecompilationdeps) option to `false` - dependency-cruiser will then _first_ compile typescript down to javascript and after that determine which dependencies exist. 


If you create a dependency-cruiser configuration with `--init` in a TypeScript project/ repo it'll ask _Also regard TypeScript dependencies that exist only before compilation?_ . If answered with `Yes` (which is the default), that option will be switched to _true_ in .dependency-cruiser.js. 

To switch that back, in your .dependency-cruiser.js:


```javascript
//
  options: {
    // ...
    tsPreCompilationDeps: false,
    // ...
  } 
//
```


>> Type only imports are always included in the output graph, even if you mark them to not be followed via the doNotFollow option.
>
> `doNotFollow` can be a bit confusing. It still includes whatever matches it (as
> you found). However, it doesn't follow any dependencies it would have. This is
> useful for e.g. to see _that_ you have a dependency on something in node_modules
> but are not interested in whatever that pulls in.

**Comment by brocef** [comment]
Thank you, that change in config is just what I was looking for!
