### ISSUE TITLE
Question: How to generate a dependency graph of only module names in a monorepo?

### ISSUE THREAD

**Issue by robert-westenberger** [sverweij/dependency-cruiser#957]
Say I have a pnpm monorepo where i have two workspace packages like this:

```json
{
  "name": "@depcruiser-testing/package-a",
  "version": "0.0.1",
  "type": "module",
  "exports": "./src/index.ts",
  "types": "./src/index.ts",
  "dependencies": {
    "@depcruiser-test/package-b": "workspace:"
  },
  "devDependencies": {
    "@depcruiser-testing/tsconfig": "workspace:*",
    "typescript": "catalog:"
  }
}
```

```json
{
"name": "@depcruiser-test/package-b",
"version": "0.0.1",
"type": "module",
"exports": "./src/index.ts",
"types": "./src/index.ts",
"devDependencies": {
  "@depcruiser-testing/tsconfig": "workspace:*",
  "typescript": "catalog:"
  }
}
```
(`package-a` depends on `package-b`.)

and their indexes are:

**package-a/src/index.ts:**
```typescript
import {hello} from "@depcruiser-test/package-b";

console.log(`${hello()} world`);
```

**package-b/src/index.ts:**
```typescript
// package-b src/index.ts
export function hello() {
    return "hello";
}
```

I have this `.dependency-cruiser.js` file.

```js
/** @type {import('dependency-cruiser').IConfiguration} */
module.exports = {
  options: {
    doNotFollow: {
      path: ['node_modules']
    },
    enhancedResolveOptions: {
      exportsFields: ["exports"],
      conditionNames: ["import", "require", "node", "default", "types"],
      mainFields: ["main", "types", "typings"],
    },
    reporterOptions: {
      dot: {
        collapsePattern: '^packages/([^/]+)/.*$',
      },
    }
  }
};
```

And I run this command

```shell
pnpm exec depcruise --config .dependency-cruiser.js packages -T dot | dot -T svg > dependencygraph.svg
```

This graph is generated:

![dependencygraph](https://github.com/user-attachments/assets/bd63f202-e502-44b7-b60e-198345b5aee1)

But I want it to be like this:

![desiredDependencygraph](https://github.com/user-attachments/assets/b957a43c-026c-4d48-bf56-27c262c4bdfd)

Although it would be good if I could also annotate why two nodes have a relationship, like this:
![desiredDependencygraphWithText](https://github.com/user-attachments/assets/db050d67-c7a8-4f1b-8c3e-4c8aaf34c856)

Is that possible with dependency-cruiser?

#### What I'm trying to accomplish
- I want to generate a directed acyclic graph of relationships in my pnpm monorepo.
- I want to show only relationships between my workspace packages, not any of the files within the packages.
- I want to annotate the relationships between the packages by putting text on the edge between two nodes ("Package Foo is a dependency of Package Bar because XYZ")
- This is optional, but it would be nice to add other external nodes that aren't in my actual codebase so they could be graphed. Is there any way to annotate this, perhaps manually? For example, if `package-baz` makes a request to some REST API, I'd like to be able to add another node labelled `REST API` or something that `package-baz` points to.

#### What I've tried
- Using the [maxDepth](https://github.com/sverweij/dependency-cruiser/blob/main/doc/options-reference.md#maxdepth) option to set `maxDepth: 1` but it still shows files inside the packages, not the package name itself.
- I've tried using the archi reporter to generate a "high level dependency graph" (https://github.com/sverweij/dependency-cruiser/blob/main/doc/faq.md#high-level-dependency-graph-archi-reporter) but it's still at a level of granularity that is slightly below what I am going for.

(Code for the dummy repo I made for this question: https://github.com/robert-westenberger/dependency-cruiser-test )

### Environment
```text
## System:
 - OS: macOS 14.1
 - CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
 - Memory: 585.00 MB / 32.00 GB
 - Shell: 5.9 - /bin/zsh
## Binaries:
 - Node: 20.16.0 - ~/.nvm/versions/node/v20.16.0/bin/node
 - npm: 10.8.1 - ~/.nvm/versions/node/v20.16.0/bin/npm
 - pnpm: 9.10.0 - ~/.nvm/versions/node/v20.16.0/bin/pnpm
 - Watchman: 2024.03.18.00 - /usr/local/bin/watchman
## Browsers:
 - Edge: 129.0.2792.65
 - Safari: 17.1
 - Safari Technology Preview: 18.0
## npmPackages:
 - dependency-cruiser: catalog: => 16.4.2 
## npmGlobalPackages:
 - corepack: 0.28.2
 - npm: 10.8.1
```

**Comment by sverweij** [comment]
Hi @robert-westenberger

## summarizing on package level

For emitting summarized graphs there's a few  options:
- the [ddot reporter](https://github.com/sverweij/dependency-cruiser/blob/main/doc/cli.md#ddot---summarise-on-folder-level) summarizes on folder level. See [this command & output on the dependency-cruiser code base](https://github.com/sverweij/dependency-cruiser/blob/main/doc/real-world-samples.md#folder-level-overview-ddot) as an example. Depending on your repo this might still show more than what you need.
- the [`--collapse`](https://github.com/sverweij/dependency-cruiser/blob/main/doc/options-reference.md#collapse-summarize-to-folder-depth-or-pattern) command line option, that you can use with most non-validating output, but works best with the `dot` reporter. You can either use a collapse depth or a regular expression to summarize the dependencies. I.e. in a mono repo that has packages exclusively directly under the `packages` folder you could use 
  ```
  depcruise packages --include-only ^packages --collapse "^packages/[^/]+" -T dot | dot -Tsvg > graph.svg
  ```
  or 
  ```
  depcruise packages --include-only ^packages --collapse 2 -T dot | dot -Tsvg > graph.svg
  ```

## relationship annotations

Dependency-cruiser does not have direct support for that. Indirectly/ slightly hacky:
- On hover the dependency-graph shows the _from_ and _to_ of the dependency and
- If a rule is violated, the dependency is annotated with the (abbreviation of that) rule. 

You could (mis)use that e.g. by defining an info level rule like so

```javascript
    {
      name: "my cool annotation for the dependency between foo/bar.js and bar/baz.js",
      severity: "info",
      from: { path: "foo/bar[.]js$" },
      to: {
        path: "bar/baz[.]js$",
      },
    },
```

## showing dependencies outside the code base

If the dependencies are outside the code base, but still javascript (or javascript-ish, like typescript, coffeescript etc) e.g. in the node_modules folder, then that's possible. You can tell dependency-cruiser to scan these, but to not follow them with the [--do-not-follow cli option](https://github.com/sverweij/dependency-cruiser/blob/main/doc/cli.md#--do-not-follow-dont-cruise-modules-adhering-to-this-pattern-any-further) or the [doNotFollow configuration option](https://github.com/sverweij/dependency-cruiser/blob/main/doc/options-reference.md#donotfollow-dont-cruise-modules-any-further). Out of the box dependency-cruiser 'collapses' these things in graphical output.

If it's other languages or systems not expressed in javascript(-ish) there's currently no option for that

**Comment by robert-westenberger** [comment]
Thank you @sverweij I will try that tomorrow. Awesome tool by the way.

**Comment by sverweij** [comment]
Hi @robert-westenberger it should already be possible to collapse down to the folders directly below `/packages` by adapting either the pattern or the number behind the `--collapse` cli option and the dot reporter. E.g. 
```
depcruise  --include-only ^packages --collapse packages/[^/]+ --output-type dot | dot -Tsvg > graph.svg
```

should do the trick. You can even make it the default for the dot or the archi reporters (the archi reporter is a dot reporter with a pre-configured collapse pattern - that can be overriden) in your repo, by [configuring it in a .dependency-cruiser.js for that type of reporter](https://github.com/sverweij/dependency-cruiser/blob/main/doc/options-reference.md#summarising-collapsepattern-dot-and-archi-reporters)

## Annotating dependencies

If I'd bake this into dependency-cruiser I'd probably use as much what is already in place, at a short glance there's two options:
- provide it as the 'hack' described above
  potentially with an additional 'severity' level called _annotation_, on top of the current _error_, _warning_, and _info_ levels; or even by reusing the _info_ level for it. In that last case it'd be a matter of adding a paragraph in [the recipes section of the tutorial](https://github.com/sverweij/dependency-cruiser/blob/main/doc/rules-tutorial.md#recipes) that ~copied the trick from my previous comment.
- Some syntactic sugar that translated into the 'hack' above.
  I.e. a separate `annotate` section in .dependency-cruiser.js next to the `forbidden`, `allowed` and `required` rule sections, that under the hood translates into a bunch of `forbidden` rules with either severity `info` or `annotation`.

For now I'm most in favor of that first option, also to learn a bit about how it can be used and what interesting issues we might bump into.


## annotating dependencies outside the code base

Indeed a somewhat larger ask. I guess the easiest way would be to supplement the cruise-result (which is a javascript object adhering to a [json schema](https://github.com/sverweij/dependency-cruiser/blob/main/src/schema/cruise-result.schema.json) 'manually' with some additional `module` entries and add some `dependencies` from the real generated ones to the 'manually' added ones.

Before adding it into dependency-cruiser (with or without syntactic sugar) I'd first try and prototype it out with a json manipulation tool like `jq` e.g.

- Make dependency-cruiser emit json (cli: `--output-type json`)
- process the json with `jq` (or any other json manipulation tool or script)
- feed the json into [depcruise-fmt])https://github.com/sverweij/dependency-cruiser/blob/main/doc/cli.md#depcruise-fmt) (which ships with dependency-cruiser)

Another option is to create a [reporter plugin](https://github.com/sverweij/dependency-cruiser/blob/main/doc/faq.md#expanding-dependency-cruiser). Reporter plugins take a json adhering to the cruise-result schema and manipulate it into something useful. In this case you could make it to include new data.

**Comment by robert-westenberger** [comment]
@sverweij After using the command you gave me, I now get this

which is exactly what I want.
![graph](https://github.com/user-attachments/assets/7ad13bae-1613-41f1-b410-6b35c32b04e8)


I'll experiment with the [theme reporterOption](https://github.com/sverweij/dependency-cruiser/blob/main/doc/options-reference.md#theme-dot-ddot-and-archi-reporters) to see if i can prevent the annotation text from overlapping.

For now, I think annotating dependencies and external dependencies in the way you recommended meets my use case. Closing this issue.
