### ISSUE TITLE
Question:  moduleResolution and extend tsconfig

### ISSUE THREAD

**Issue by kwonoj** [sverweij/dependency-cruiser#958]
### Summary

I have a base tsconfig sets a new moduleResolution for tsc

```
{
... 
  "compilerOptions": {
     "moduleResolution": "Bundler",
      ...
  }
}
```

and there is a tsconfig that `extends` above config.

Running dependency cruiser with those tsconfig gives an error

```
 ERROR: ../tsconfig/tsconfig.json(11,25): error TS6046: Argument for '--moduleResolution' option must be: 'node', 'classic', 'node16', 'nodenext'.
```

and if I try to override tsconfig

```
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
     "moduleResolution": "NodeNext",
  }
}
```

Still gives a same error, only goes away if I update base tsconfig's value or do not extend base tsconfig have an incompatible module resolution.

2 questions - 

1. Is it possible to support new module resolutions like `Bundler`?
2. How does tsconfig resolving works in case of extending base config? Is there a way to honor overridden value in tsconfig other than base one?

### Environment

- Version used: latest
- Node version: 20.15
- Operating System and version: mac
- Link to your project:

**Comment by sverweij** [comment]
> 1. Is it possible to support new module resolutions like Bundler?

It's  already supported.

Dependency-cruiser uses the TypeScript compiler it finds in the place it's installed in for parsing tsconfigs.

The error (TS6046) you see is from  the TypeScript compiler dependency-cruiser found Apparently that version of the TypeScript compiler doesn't support the _Bundler_ moduleResolution type. Support for the 'bundler' module resolution type I believe was introduced into typescript with version 5 of their compiler.

- if it's the same typescript compiler used in the project, transpiling with the typescript compiler will yield the same error. In that case upgrading the typescript compiler to one that does support the bundler resolution type will fix the issue.
- if it's a typescript compiler different from the one used in your project you're probably running a dependency-cruiser that is installed in a different spot than your project is. Installing it in your project (as a devDependency) and ensuring you run that instance will fix the issue.

> 2. How does tsconfig resolving works in case of extending base config? Is there a way to honor overridden value in tsconfig other than base one?

It should work the same as it works in the TypeScript compiler without configuration as, under the hood, dependency-cruiser _uses_ the TypeScript compiler for this.

**Comment by kwonoj** [comment]
Ok, sounds like version conflict issue. Our repo have 4.x and the latest tsc both in a monorepo structure. But the package I run depcruise have tsc@5 as devdep correctly. 

How can I confirm what tsc version depcruise uses / and specify one explicitly?

**Comment by kwonoj** [comment]
Peeking bit, it looks like https://github.com/sverweij/dependency-cruiser/blob/802ff6fa3ee11a7d4e52e2c89cd6b714e060e02d/src/utl/try-import.mjs#L33 resolves to the root regardless of workspace package's version and curious if there's way to pick a version instead.

**Comment by sverweij** [comment]
The `extractRootModuleName` is there to check if the version of the module tryImport angles in is within the range dependency-cruiser supports, so we can gracefully handle breaking changes in external transpilers.

The import of all transpilers happens via the `tryImport` function, specifically line 62, which is a plain old import:

https://github.com/sverweij/dependency-cruiser/blob/802ff6fa3ee11a7d4e52e2c89cd6b714e060e02d/src/utl/try-import.mjs#L62

E.g. used in the function that parses typescript with the typescript compiler:

https://github.com/sverweij/dependency-cruiser/blob/802ff6fa3ee11a7d4e52e2c89cd6b714e060e02d/src/extract/tsc/parse.mjs#L9-L12

... and in the thing that makes tsconfigs digestible to the typescript compiler:

https://github.com/sverweij/dependency-cruiser/blob/802ff6fa3ee11a7d4e52e2c89cd6b714e060e02d/src/config-utl/extract-ts-config.mjs#L5-L8

So dependency-cruiser plainly `import`s the typescript compiler a la `import('typescript');` which relies on nodes module resolution. This should yield the one that is installed in the folder dependency-cruiser is installed in.

Having two versions of the typescript compiler around in the same monorepo is not something I'd have anticipated ever happening, so I'm curious - what's keeping your monorepo's root folder on a different (older) version of the typescript compiler than the packages folder?

> - As it's software, it's likeley possible to make the path to the typescript compiler configurable. But I'd like to understand whether it's a common occurrence/ there's good reasons to do so.
> - A workaround could be installing dependency-cruiser in the subfolder that does contain the right version of the typescript compiler.

**Comment by kwonoj** [comment]
> root folder on a different (older) version of the typescript compiler than the packages folder?

I am also very hesitant to have these kind of thing. We are on the 4.9 as main, and recent 5.5 and beyond deprecates `suppressImplicitAnyIndexErrors` which we now have to fix 2-3000 errors in the root's main app. For the gradual fix for the non root apps under monorepo packages we have 5.6 and root still remains on 4.9.
