### ISSUE TITLE
Question: How to track script inclusion as a WebWorker?

### ISSUE THREAD

**Issue by louwers** [sverweij/dependency-cruiser#966]
### Summary

I found yet another type of dependency that I'm not sure how to track.

I realize this may be a bit specific. Is it possible to customize dependency extraction by writing a plugin or something?

### Context

Web workers are typically created by referring to some other script.

```js
new Worker("/path/to/worker.js", {
  module: true
});
```

This is a dependency of one file on another, so it might be in scope of dependency cruiser at some point. However, if you use a bundler, they all have slightly different syntax (e.g. [see Vite](https://v3.vitejs.dev/guide/features.html#web-workers)). Note also that there are other types of workers. e.g. [`SharedWorker`](https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker).

**Comment by sverweij** [comment]
Hi @louwers - it might be that [exotic requires](https://github.com/sverweij/dependency-cruiser/blob/main/doc/options-reference.md#exotic-ways-to-require-modules---exoticrequirestrings) fits that. It's written with function calls in mind, so not sure it out of the box detects a class definition - but if it doesn't it should be doable to expand the code to include that.

> The approach vite has with _new URL_ and _import.meta.url_ looks the same as the construct used to import non-js (i.e. .json ...) in ESM modules. 

Extraction (/ resolution/ enrichment) don't take plugins a.t.m. - that currently only works for the reporting step. I've played with the thought and refactored extraction code to have a uniform interface, so it's easier to add a new parser but haven't taken the step to have plugins for it - it takes

**Comment by louwers** [comment]
Interesting. I'll have a look at that.

I'm playing around with [scanning all string literals to see if they mention a filename](https://github.com/sverweij/dependency-cruiser/commit/579d8dd1149ca6f5a66d5c2746de1f82d9465637).
