### ISSUE TITLE
Question: Having the function call graph

### ISSUE THREAD

**Issue by anaelChardan** [sverweij/dependency-cruiser#974]
### Summary

Hi! I would like to know if it is possible to see the graph at function level and not module level ?

Like we give a file and a function name and it give the call graph (as you already do with module)

Thanks a lot!

**Comment by sverweij** [comment]
Hi @anaelChardan good question - and an interesting topic, but it's beyond dependency-cruiser's scope. 

Related [FAQ: does dependency-cruiser support granularity finer that modules?](https://github.com/sverweij/dependency-cruiser/blob/main/doc/faq.md#q-does-dependency-cruiser-support-granularity-finer-than-modules-eg-classes-functions-variables-)

**Comment by anaelChardan** [comment]
Thanks a lot for your answer! Out of curiosity, do you know any tools doing that ? :)
