### ISSUE TITLE
* in lhs of tsconfig paths don't get processed correctly

### ISSUE THREAD

**Issue by alecf** [sverweij/dependency-cruiser#99]
I love the idea of this project and have some ideas for further contributions!

But I can't seem to make it work. I'm not sure why, but NONE of my dependencies are found, specifically every `import` hits the included `not-to-unresolvable` rule. My project is 100% typescript.

It fails for:
1) modules in node_modules
2) local, relative dependencies
3) inter-module dependencies (like `uf/foo/bar` imports `uf/base/xhr`, 

All of these should be resolvable using the `paths` settings in `tsconfig.json`

### Expected Behavior
I expect it to find these dependencies.

### Current Behavior

All imports are marked invalid:
code like this:
```
import superagent from 'superagent';
import Swagger from 'swagger-client';
import { UFApiClient } from 'uf-api';
import { UFApiClient as UFManagementApiClient } from 'uf-api-management';
import warning from 'warning';
```
results in errors like this:
```
  error not-to-unresolvable: uf/base/xhr.ts → superagent
  error not-to-unresolvable: uf/base/xhr.ts → swagger-client
  error not-to-unresolvable: uf/base/xhr.ts → uf-api
  error not-to-unresolvable: uf/base/xhr.ts → uf-api-management
  error not-to-unresolvable: uf/base/xhr.ts → warning
```

### Possible Solution
No idea!

### Steps to Reproduce (for bugs)
Our project is quite large, our setup is as follows:

1. `package.json` has `"name": "uf"`
2. source code is in the directory `uf`
3. There are other directories here: `uf-api` and `uf-api-management` - I realize these should be separate packages but they aren't right now.
3. tsconfig has paths:
```
    "paths": {
      "*": ["types/*"],
      "integration/*": ["integration/*"],
      "uf-api-management": ["uf-api-management"],
      "uf-api-management/*": ["uf-api-management/*"],
      "uf-api": ["uf-api"],
      "uf-api/*": ["uf-api/*"],
      "uf/*": ["uf/*"]
    },
```

### Context

Just trying it by installing globally, and also installing directly into the project.

### Your Environment
* Version used: 4.13.1
* Node version: 10.15.1
* Operating System and version: OSX
* Link to your project: (not open source)

**Comment by alecf** [comment]
FYI: doing this: `    moduleSystems: ['tsd'],` seems to make the modules resolve (maybe?) but complains that basically every file encountered is an orphan.

**Comment by sverweij** [comment]
hi @alecf  - from the looks of it dependency-cruiser isn't looking to your `tsconfig.json`. There's two ways to tell it where it lives; via command line and in the config. As you also seem to have generated a dependency-cruiser config, the easiest way is to add a `tsConfig` key to the `options` section in there:
```json
    "options": {
    ...
        , "tsConfig": {
            "fileName": "./tsconfig.json"
        }
}
```
(If you generated the config with `--init` uncommenting the same in the options section should do the trick)

If this indeed solves your issue, you're the second one bitten by it - which means I'll have to up my documentation game and/ or have to make --init smarter.

Note: the `tsd` module system is there for the more esoteric typescript dependency references (e.g. triple slash references) - you typically want to stay with "es6" and "cjs" .

If this doesn't resolve your issue could you share the dependency-cruiser config & the command line invocation you use to kick off dependency-cruiser?

**Comment by alecf** [comment]
I tried both with and without various versions of specifying my tsconfig.json - both on the command line and in the file. our file is just called tsconfig.json, nothing special.

```
./node_modules/.bin/depcruise --validate .dependency-cruiser.js uf
```

Most recently this is failing (all vanilla rules, so I'm just posting `options` here
```
  options: {
    /* pattern specifying which files not to follow further when encountered
           (regular expression)
         */
    doNotFollow: 'node_modules',

    /* pattern specifying which files to exclude (regular expression) */
    //exclude: '.*.css',

    /* list of module systems to cruise */
    moduleSystems: ['es6', 'cjs'],

    /* prefix for links in html and svg output (e.g. https://github.com/you/yourrepo/blob/develop/) */
    // , prefix: ''

    /* if true detect dependencies that only exist before typescript-to-javascript compilation */
    // , tsPreCompilationDeps: false

    /* if true combines the package.jsons found from the module up to the base
           folder the cruise is initiated from. Useful for how (some) mono-repos
           manage dependencies & dependency definitions.
         */
    combinedDependencies: true,

    /* if true leave symlinks untouched, otherwise use the realpath */
    // , preserveSymlinks: false

    /* Typescript project file ('tsconfig.json') to use for
           (1) compilation and
           (2) resolution (e.g. with the paths property)

           The (optional) fileName attribute specifies which file to take (relative to
           dependency-cruiser's current working directory). When not provided
           defaults to './tsconfig.json'.
         */
    tsConfig: {
      fileName: './tsconfig.json',
    },

    /* Webpack configuration to use to get resolve options from.

          The (optional) fileName attribute specifies which file to take (relative to dependency-cruiser's
          current working directory. When not provided defaults to './webpack.conf.js'.

          The (optional) `env` and `args` attributes contain the parameters to be passed if
          your webpack config is a function and takes them (see webpack documentation
          for details)
         */
    // , webpackConfig: {
    //    fileName: './webpack.conf.js'
    //    , env: {}
    //    , args: {}
    // }
  },
};
// generated: dependency-cruiser@4.13.1 on 2019-02-18T03:26:23.566Z
```

this is the tsconfig:
```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "noUnusedLocals": true,
    "baseUrl": ".",
    "paths": {
      "*": ["types/*"],
      "integration/*": ["integration/*"],
      "uf-api-management": ["uf-api-management"],
      "uf-api-management/*": ["uf-api-management/*"],
      "uf-api": ["uf-api"],
      "uf-api/*": ["uf-api/*"],
      "uf/*": ["uf/*"]
    },
    "jsx": "react",
    "lib": ["es2017", "dom"],
    "moduleResolution": "node",
    "module": "esnext",
    "sourceMap": true,
    "target": "es6"
  },
  "include": ["vendor.d.ts", "uf/**/*", "uf-api/**/*", "integration/**/*"]
}
```

Things that might be affecting this: `baseUrl`, `moduleResolution`, `module`, `allowSyntheticDefaultImports`?

I also dug around in the issues and found mention of a `basePath` configuration - messed with that, but didn't make any difference.

So far the ONLY thing that seems to work is switching from 'es6' to 'tsd' - so perhaps there is a subtlety to how `tsd` works?

**Comment by alecf** [comment]
oh! removing `"*": ["types/*"],` fixed the 3rd party libraries

We have that in there because we have type definitions for some third party libraries that don't provide their own via DefinitelyTyped. 

but I'm still getting dinged for any package-based imports of our project, i.e. this line:

```
import { parseServerJSON } from 'uf/base/json';
```
in `uf/base/swagger.ts` still generates this:
```
  error not-to-unresolvable: uf/base/swagger.ts → uf/base/json
```

**Comment by sverweij** [comment]
Hi @alecf thanks for the detailed configs - I've made a minimal reproduction sample, and reproduced the issue.

- It seems dependency-cruiser resolver doesn't handle `paths` with wildcards on the lhs correctly - that'll probably have to be fixed upstream (probably in `awesome-typescript-loader`; [this issue](https://github.com/s-panferov/awesome-typescript-loader/issues/604) (and [this](https://github.com/s-panferov/awesome-typescript-loader/issues/346), [this](https://github.com/s-panferov/awesome-typescript-loader/issues/319) and [this](https://github.com/s-panferov/awesome-typescript-loader/issues/311)) seem related), by switching to another typescript loader (`ts-loader`) or by writing my own one - anyway; I'll do some research.

- The `uf-api/*` and `uf-api` keys in paths look seem to express the same thing - what's the reason you have both of them?

I did manage to get correct module resolution results when I changed the paths to this (with the exception of the stuff in types :-/)
```json
    "paths": {
      // "*": ["types/*"],
      "integration": ["integration"],
      "uf-api-management": ["uf-api-management"],
      "uf-api": ["uf-api"],
      "uf": ["uf"]
    }
```

So - to be continued ...

**Comment by sverweij** [comment]
@alecf the fix was easier to do then anticipated - I'm now using ts-loaders paths plugin instead of the awesome-typescript-loader one, and that seems to resolve the issue (both in the unit tests I added and in the minimal reproduction sample). 

I've put it as a beta on npm (version `dependency-cruiser@4.13.2-beta-1`) just now.

=> Can you give that version a spin and let me know how it works for you before I publish it as regular version?

**Comment by alecf** [comment]
trying it out now!
...and, it worked perfectly, thanks!

(the reason for the seemingly duplicate entries was issues importing from both `'uf-api'` as well as `'uf-api/foo/bar'` - I might be able to remove them..)

**Comment by sverweij** [comment]
@alecf version 4.13.2 that includes the fix for this issue is on npm since a few minutes. Thanks again for raising the issue and your detailed & complete reports - it definitely helped speed up fixing this issue!
